frappe.pages['amazon-finance'].on_page_load = function (wrapper) {
    const page = frappe.ui.make_app_page({ parent: wrapper, title: 'Amazon 财务交易中心', single_column: true });
    wrapper.amazon_finance = new AmazonFinancePage(page);
};
frappe.pages['amazon-finance'].on_page_show = wrapper => wrapper.amazon_finance?.load();

class AmazonFinancePage {
    constructor(page) {
        this.page=page; this.pageNo=1; this.pageSize=50; this.charts=[]; this.loading=false;
        this.renderShell(); this.bindEvents();
    }
    renderShell() {
        const today=frappe.datetime.get_today(), from=frappe.datetime.add_days(today,-29);
        $(this.page.main).html(`<div class="af-root">
          <section class="af-hero"><div><span>AMAZON FINANCE INTELLIGENCE</span><h1>财务交易中心</h1><p>销售、退款、税费、平台费用与结算批次，穿透至店铺、SKU和ERPNext物料。</p></div><div><button class="btn af-refresh-bind">重新匹配物料</button><button class="btn btn-primary af-refresh">刷新数据</button></div></section>
          <section class="af-filter-panel"><div class="af-ranges">${[7,30,90,180,365].map(n=>`<button data-days="${n}" class="af-range ${n===30?'active':''}">${n===365?'1年':n+'天'}</button>`).join('')}</div><div class="af-filters">
            ${this.input('date_from','开始日期','date',from)}${this.input('date_to','结束日期','date',today)}${this.select('store','店铺')}${this.select('marketplace_id','站点')}${this.select('country','国家')}${this.select('currency_code','币种')}${this.select('transaction_type','交易类型')}${this.select('transaction_status','状态')}
            <label>交易归属<select data-filter="scope"><option value="">全部</option><option value="product">商品级交易</option><option value="store">店铺级费用</option></select></label><label>物料绑定<select data-filter="binding"><option value="">全部</option><option value="bound">已绑定</option><option value="unbound">未绑定</option></select></label><label class="af-search-label">搜索<input data-filter="search" placeholder="订单号 / SKU / ASIN / 费用内容 / 物料 / 结算ID"></label></div></section>
          <div class="af-loading"><i></i>正在分析财务交易…</div><main class="af-content"><section class="af-kpis"></section><section class="af-currencies"></section>
          <section class="af-grid af-grid-2"><article class="af-card af-wide"><header><h2>净额与费用趋势</h2><span>按记账日期与币种</span></header><div id="af-trend" class="af-chart"></div></article><article class="af-card"><header><h2>费用构成</h2><span>负值代表扣费</span></header><div id="af-fees" class="af-chart"></div></article></section>
          <section class="af-grid af-grid-2"><article class="af-card"><header><h2>交易类型</h2><span>金额与笔数</span></header><div id="af-types" class="af-chart"></div></article><article class="af-card"><header><h2>店铺贡献</h2><span>店铺净额</span></header><div id="af-stores" class="af-chart"></div></article></section>
          <section class="af-grid af-grid-2"><article class="af-card"><header><h2>SKU 与物料表现</h2><span>未绑定商品可直接绑定</span></header><div class="af-products"></div></article><article class="af-card"><header><h2>结算批次</h2><span>最近200个批次</span></header><div class="af-settlements"></div></article></section>
          <section class="af-card af-table-card"><header><div><h2>完整交易明细</h2><span class="af-table-count"></span></div><div class="af-pages"></div></header><div class="af-table-wrap"><table><thead><tr><th>时间</th><th>店铺 / 站点</th><th>交易 / 订单</th><th>交易内容</th><th>物料 / 费用归属</th><th>类型 / 状态</th><th>币种</th><th>净额</th><th>销售额</th><th>费用</th><th>结算ID</th></tr></thead><tbody></tbody></table></div></section></main></div>`);
        this.$=$(this.page.main).find('.af-root');
    }
    input(n,l,t,v){return `<label>${l}<input type="${t}" data-filter="${n}" value="${v}"></label>`}
    select(n,l){return `<label>${l}<select data-filter="${n}"><option value="">全部</option></select></label>`}
    bindEvents(){
        this.$.on('click','.af-refresh',()=>this.load()).on('click','.af-refresh-bind',()=>this.refreshBindings());
        this.$.on('click','.af-range',e=>{let n=+e.currentTarget.dataset.days,to=frappe.datetime.get_today();this.$.find('.af-range').removeClass('active');$(e.currentTarget).addClass('active');this.$.find('[data-filter=date_to]').val(to);this.$.find('[data-filter=date_from]').val(frappe.datetime.add_days(to,-n+1));this.pageNo=1;this.load()});
        let timer;this.$.on('change','[data-filter]:not([data-filter=search])',()=>{this.pageNo=1;this.load()}).on('input','[data-filter=search]',()=>{clearTimeout(timer);timer=setTimeout(()=>{this.pageNo=1;this.load()},400)});
        this.$.on('click','[data-page]',e=>{this.pageNo=+e.currentTarget.dataset.page;this.load()}).on('click','.af-bind',e=>this.bindItem($(e.currentTarget).data())).on('click','[data-copy]',e=>{frappe.utils.copy_to_clipboard(String($(e.currentTarget).data('copy')||''));frappe.show_alert({message:'已复制',indicator:'green'})});
        $(window).on('resize.amazon-finance',()=>this.charts.forEach(c=>c?.resize()));
    }
    filters(){const r={};this.$.find('[data-filter]').each((_,e)=>{if(e.value)r[e.dataset.filter]=e.value});return r}
    async load(){if(this.loading)return;this.loading=true;this.$.addClass('is-loading');try{const r=await frappe.call({method:'fengjing_app.fengjing_business.page.amazon_finance.amazon_finance.get_finance_dashboard_data',args:{filters:this.filters(),page:this.pageNo,page_size:this.pageSize}});this.data=r.message||{};this.render()}catch(e){console.error(e);frappe.msgprint({title:'财务页面加载失败',message:e.message||'请检查后台日志',indicator:'red'})}finally{this.loading=false;this.$.removeClass('is-loading')}}
    render(){this.fillOptions();this.renderKpis();this.renderCurrencies();this.renderCharts();this.renderProducts();this.renderSettlements();this.renderTable()}
    fillOptions(){['store','marketplace_id','country','currency_code','transaction_type','transaction_status'].forEach(k=>{const e=this.$.find(`[data-filter=${k}]`),v=e.val(),o=(this.data.options?.[k]||[]).map(x=>`<option value="${this.esc(x)}">${this.esc(this.translate(x))}</option>`).join('');e.html(`<option value="">全部</option>${o}`).val(v)})}
    renderKpis(){const s=this.data.summary||{},a=[['交易记录',s.row_count,'筛选范围内全部明细'],['财务交易',s.transaction_count,'每笔交易只计一次'],['商品级交易',s.product_count,'带SKU、ASIN或订单商品ID'],['店铺级费用',s.store_fee_count,'仓储、订阅、运输等'],['已绑定物料',s.bound_count,`${s.binding_rate||0}% 商品交易已识别`],['未绑定商品',s.unbound_count,'仅商品交易需要绑定']];this.$.find('.af-kpis').html(a.map((x,i)=>`<article class="af-kpi c${i}"><span>${x[0]}</span><strong>${this.num(x[1])}</strong><small>${x[2]}</small></article>`).join('')+(s.truncated?'<div class="af-warning">数据达到10万行，请缩小日期范围。</div>':''))}
    renderCurrencies(){const a=Object.entries(this.data.summary?.currencies||{});this.$.find('.af-currencies').html(`<div class="af-section-title"><h2>多币种资金总览</h2><span>不同币种不混加，避免错误总额</span></div><div class="af-currency-grid">${a.map(([c,v])=>`<article class="af-currency"><div class="af-currency-head"><span>${this.flag(c)}</span><strong>${c}</strong></div><div class="af-net ${v.net>=0?'positive':'negative'}">${this.money(v.net,c)}</div><div class="af-money-grid"><span>流入<b>${this.money(v.inflow,c)}</b></span><span>流出<b>${this.money(v.outflow,c)}</b></span><span>销售<b>${this.money(v.sales,c)}</b></span><span>平台费用<b>${this.money(v.fees,c)}</b></span></div></article>`).join('')||'<div class="af-empty">暂无金额数据</div>'}</div>`)}
    async renderCharts(){if(typeof echarts==='undefined'){await this.loadEcharts();return this.renderCharts()}this.charts.forEach(c=>c?.dispose());this.charts=[];const d=this.data.daily||{},dates=Object.keys(d),cs=[...new Set(dates.flatMap(x=>Object.keys(d[x])))];this.chart('af-trend',{tooltip:{trigger:'axis',appendToBody:true},legend:{top:4},grid:{left:65,right:20,top:50,bottom:50},xAxis:{type:'category',data:dates},yAxis:{type:'value'},dataZoom:[{type:'inside'},{type:'slider',height:17,bottom:8}],series:cs.map(c=>({name:`${c} 净额`,type:'line',smooth:true,showSymbol:false,data:dates.map(x=>d[x][c]?.net||0),lineStyle:{width:3},areaStyle:{opacity:.06}}))});const c=this.$.find('[data-filter=currency_code]').val()||Object.keys(this.data.fees||{})[0],fees=this.data.fees?.[c]||{};this.chart('af-fees',{tooltip:{trigger:'item',appendToBody:true},legend:{bottom:0,type:'scroll'},series:[{type:'pie',radius:['40%','68%'],center:['50%','43%'],data:Object.entries(fees).map(([name,value])=>({name,value:Math.abs(value)}))}]});this.bar('af-types',this.data.types?.[c]||{},x=>x.amount,'#377cf5');this.bar('af-stores',this.data.stores?.[c]||{},x=>x.amount,'#16bba4')}
    bar(id,obj,value,color){const a=Object.entries(obj).sort((x,y)=>Math.abs(value(y[1]))-Math.abs(value(x[1]))).slice(0,15);this.chart(id,{tooltip:{trigger:'axis',appendToBody:true},grid:{left:165,right:25,top:15,bottom:25},xAxis:{type:'value'},yAxis:{type:'category',data:a.map(x=>this.translate(x[0])),axisLabel:{width:150,overflow:'truncate'}},series:[{type:'bar',data:a.map(x=>value(x[1])),itemStyle:{borderRadius:[0,7,7,0],color}}]})}
    chart(id,o){const e=this.$.find('#'+id)[0];if(e){const c=echarts.init(e);c.setOption(o);this.charts.push(c)}}
    loadEcharts(){if(!this.echartsPromise)this.echartsPromise=new Promise((ok,bad)=>frappe.require('/assets/fengjing_app/js/Amazon_Order_Map/主体-echarts.js',ok,bad));return this.echartsPromise}
    renderProducts(){this.$.find('.af-products').html(`<div class="af-scroll-list">${(this.data.products||[]).slice(0,100).map((p,i)=>`<div class="af-product"><span class="af-rank">${i+1}</span><img src="${this.image(p.image)}"><div class="af-product-main"><b>${this.esc(p.item_name||p.product_name||p.sku||'未命名商品')}</b><small><button data-copy="${this.esc(p.asin||'')}">${this.esc(p.asin||'无ASIN')}</button> · <button data-copy="${this.esc(p.sku||'')}">${this.esc(p.sku||'无SKU')}</button></small><small>${this.esc(p.store||'未归属')} · 数量 ${this.num(p.quantity)} · ${p.transactions}条</small></div><div class="af-product-money">${Object.entries(p.amounts||{}).map(([c,v])=>`<b class="${v>=0?'positive':'negative'}">${this.money(v,c)}</b>`).join('')}</div>${p.item?`<a class="af-bound" href="/app/item/${encodeURIComponent(p.item)}">${this.esc(p.item)}</a>`:`<button class="btn btn-xs btn-primary af-bind" ${this.bindData(p)}>绑定物料</button>`}</div>`).join('')||'<div class="af-empty">暂无商品交易</div>'}</div>`)}
    renderSettlements(){this.$.find('.af-settlements').html(`<div class="af-scroll-list">${(this.data.settlements||[]).map(s=>`<div class="af-settlement"><i>结</i><div><b>${this.esc(s.settlement_id)}</b><small>${this.esc(s.store||'未归属')} · ${s.count}条 · ${this.date(s.last_date)}</small></div><strong class="${s.amount>=0?'positive':'negative'}">${this.money(s.amount,s.currency)}</strong></div>`).join('')||'<div class="af-empty">暂无结算批次</div>'}</div>`)}
    renderTable(){
        const p=this.data.pagination||{};
        this.$.find('.af-table-count').text(`共 ${this.num(p.total)} 条 · 第 ${p.page}/${p.pages} 页`);
        this.$.find('.af-pages').html(`<button class="btn btn-xs" data-page="${p.page-1}" ${p.page<=1?'disabled':''}>上一页</button><button class="btn btn-xs" data-page="${p.page+1}" ${p.page>=p.pages?'disabled':''}>下一页</button>`);
        this.$.find('tbody').html((this.data.rows||[]).map(r=>{
            const fees=(r.selling_fees||0)+(r.fba_fees||0)+(r.other_transaction_fees||0);
            const product=Boolean(r.is_product);
            const content=product
                ? `<div class="af-table-product"><img src="${this.image(r.item_image)}"><span><b>${this.esc(r.product_name||r.sku||'未命名商品')}</b><small>${this.esc(r.asin||'无ASIN')} · ${this.esc(r.sku||'无SKU')}</small></span></div>`
                : `<div class="af-fee-content"><span class="af-fee-icon">${this.feeIcon(r.description,r.transaction_type)}</span><span><b>${this.esc(this.translate(r.description||r.transaction_type||'店铺级费用'))}</b><small>${this.esc(this.translate(r.transaction_type||'未分类'))} · 不对应具体SKU</small></span></div>`;
            const assignment=product
                ? (r.corresponding_item?`<a href="/app/item/${encodeURIComponent(r.corresponding_item)}">${this.esc(r.item_name||r.corresponding_item)}</a><small class="af-scope-tag product">商品级交易</small>`:`<button class="btn btn-xs btn-primary af-bind" ${this.bindData(r)}>绑定物料</button><small class="af-scope-tag product">商品级交易</small>`)
                : `<span class="af-no-item">${this.esc(this.feeGroup(r.description,r.transaction_type))}</span><small class="af-scope-tag store">店铺级费用 · 无需绑定物料</small>`;
            return `<tr class="${product?'af-product-row':'af-fee-row'}"><td>${this.date(r.posted_date)}</td><td><b>${this.esc(r.store||'—')}</b><small>${this.esc(this.translate(r.country||''))} · ${this.esc(this.translate(r.marketplace_id||''))}</small></td><td><button data-copy="${this.esc(r.transaction_id||'')}">${this.esc(r.transaction_id||'—')}</button><small>${this.esc(r.amazon_order_id||'无订单号')}</small></td><td>${content}</td><td>${assignment}</td><td><b>${this.esc(this.translate(r.transaction_type||'未分类'))}</b><small>${this.esc(this.translate(r.transaction_status||''))}</small></td><td>${this.esc(r.currency_code||'—')}</td><td class="num ${r.net_amount>=0?'positive':'negative'}">${this.money(r.net_amount,r.currency_code)}</td><td class="num">${this.money(r.product_sales,r.currency_code)}</td><td class="num ${fees<0?'negative':''}">${this.money(fees,r.currency_code)}</td><td>${this.esc(r.settlement_id||'—')}</td></tr>`;
        }).join('')||'<tr><td colspan="11" class="af-empty">暂无交易</td></tr>')
    }
    feeIcon(description,type){const v=String(description||type||'');if(/Storage|Warehouse/i.test(v))return '仓';if(/Transportation|Shipment|Inbound/i.test(v))return '运';if(/Ads|Coupon|Promotion/i.test(v))return '推';if(/Subscription/i.test(v))return '订';if(/Transfer|Disbursement/i.test(v))return '款';if(/Adjustment|Reserve/i.test(v))return '调';return '费'}
    feeGroup(description,type){const v=String(description||type||'');if(/Storage|Warehouse/i.test(v))return '仓储及库存费用';if(/Transportation|Shipment|Inbound/i.test(v))return '物流及入库费用';if(/Ads|Coupon|Promotion/i.test(v))return '广告及推广费用';if(/Subscription/i.test(v))return '店铺订阅费用';if(/Transfer|Disbursement/i.test(v))return '平台资金账户';if(/Adjustment|Reserve/i.test(v))return '平台调整款';return '店铺公共费用'}
    bindData(p){return `data-store="${this.esc(p.store||'')}" data-marketplace_id="${this.esc(p.marketplace_id||'')}" data-asin="${this.esc(p.asin||'')}" data-sku="${this.esc(p.sku||'')}"`}
    bindItem(d){const x=new frappe.ui.Dialog({title:'绑定到 ERPNext 物料',fields:[{fieldtype:'HTML',fieldname:'x',options:`<div class="af-bind-summary"><b>ASIN：</b>${this.esc(d.asin||'—')}<br><b>SKU：</b>${this.esc(d.sku||'—')}<br><b>店铺：</b>${this.esc(d.store||'—')}</div>`},{fieldtype:'Link',fieldname:'item',label:'对应物料',options:'Item',reqd:1}],primary_action_label:'保存并回填历史交易',primary_action:async v=>{await frappe.call({method:'fengjing_app.fengjing_business.page.amazon_finance.amazon_finance.bind_finance_item',freeze:true,freeze_message:'正在建立物料映射…',args:{...d,item:v.item}});x.hide();frappe.show_alert({message:'物料绑定成功',indicator:'green'});this.load()}});x.show()}
    async refreshBindings(){const r=await frappe.call({method:'fengjing_app.fengjing_business.page.amazon_finance.amazon_finance.refresh_finance_item_bindings',freeze:true,freeze_message:'正在重新匹配历史财务交易…'});frappe.msgprint(`已检查 ${r.message.total} 条，更新 ${r.message.updated} 条。`);this.load()}
    translate(v){return ({ATVPDKIKX0DER:'美国站 Amazon.com',A2ZV50J4W1RKNI:'美国站非商城交易',A2EUQ1WTGCTBG2:'加拿大站 Amazon.ca',A1AM78C64UM0Y8:'墨西哥站 Amazon.com.mx',A2Q3Y263D00KWC:'巴西站 Amazon.com.br','United States':'美国',Canada:'加拿大',Mexico:'墨西哥',Brazil:'巴西',Shipment:'发货交易',Refund:'退款交易',ServiceFee:'服务费',Adjustment:'调整交易',DebtRecovery:'欠款回收',FBAInventoryReimbursement:'FBA库存赔偿',ProductAdsPayment:'广告付款',RemovalShipment:'移除货件',Retrocharge:'追溯扣款',Transfer:'资金划转',ShipmentEvent:'发货交易',RefundEvent:'退款交易',ServiceFeeEvent:'服务费',AdjustmentEvent:'调整交易',ChargebackEvent:'拒付交易',RELEASED:'已释放',DEFERRED:'延期释放',DEFERRED_RELEASED:'延期后已释放',Released:'已释放',Pending:'待处理',Deferred:'延期',Amazon:'亚马逊配送',Merchant:'卖家配送','Order Payment':'订单销售回款',Refund:'退款','FBAInboundConvenience':'FBA入库便利服务费','AGSGlobalInboundTransportation':'亚马逊全球入库运输费','AWDProcessingFee':'AWD处理费','AWDTransportationFee':'AWD运输费','FBAStorageBilling':'FBA月度仓储费','STARStorageBilling':'STAR仓储费','FBALongTermStorageBilling':'FBA长期仓储费','FBAPostInboundTransportation':'FBA入库后运输费','FBAShipmentInjectionFulfillmentFee':'FBA货件注入履约费','FBADisposal':'FBA库存销毁费','FulfillmentAdjustment':'履约费用调整','Subscription':'店铺订阅费','ProductAdsPayment':'广告付款','CouponParticipationEvent':'优惠券参与费','CouponPerformanceEvent':'优惠券使用费','LabmanLabelPurchase':'标签购买费','LabmanLabelReturn':'标签退回费','LabmanLabelChargeBack':'标签费用追回','LabmanLabelRefund':'标签费退款','Disbursement':'平台提现划转','DebtPayment':'欠款偿还','Reserve':'平台预留款','Retrocharge':'追溯扣款','RecommerceAfterMarketplaceShipmentItem':'移除货件再销售收入','REVERSAL_REIMBURSEMENT':'赔偿冲销','COMPENSATED_CLAWBACK':'赔偿追回','WAREHOUSE_LOST':'仓库丢失赔偿','AWD_WAREHOUSE_LOST_MANUAL':'AWD仓库丢失人工赔偿','MISSING_FROM_INBOUND':'入库缺失赔偿','FREE_REPLACEMENT_REFUND_ITEMS':'免费换货退款赔偿'})[v]||v}
    money(v,c){return `${c||''} ${Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`}
    num(v){return Number(v||0).toLocaleString('zh-CN')}
    date(v){return v?String(v).replace('T',' ').replace(/\.\d+$/,'').slice(0,19):'—'}
    flag(c){return ({USD:'🇺🇸',CAD:'🇨🇦',MXN:'🇲🇽',BRL:'🇧🇷',EUR:'🇪🇺',GBP:'🇬🇧',JPY:'🇯🇵',CNY:'🇨🇳'})[c]||'💱'}
    image(v){return v||'/assets/frappe/images/default-avatar.png'}
    esc(v){return frappe.utils.escape_html(String(v??''))}
}
