frappe.pages["ozon_financial_stora"].on_page_load = function (wrapper) {
	const page = frappe.ui.make_app_page({ parent: wrapper, title: "Ozon 财务记录表", single_column: true });
	wrapper.__ozon_finance = new OzonFinanceDashboard(page, wrapper);
};

frappe.pages["ozon_financial_stora"].on_page_show = wrapper => {
	const dashboard = wrapper.__ozon_finance;
	if (dashboard?.fullscreenKeyHandler) document.addEventListener('keydown', dashboard.fullscreenKeyHandler);
	dashboard?.load();
};

class OzonFinanceDashboard {
	constructor(page, wrapper) {
		this.page = page; this.wrapper = wrapper; this.pageNo = 1; this.pageSize = 50; this.charts = []; this.loaded = false; this.bookedChanges = new Map(); this.accountCodeChanges = new Map(); this.costCenterChanges = new Map(); this.autoSaveTimer = null; this.savingChanges = false; this.activeAccrualType = ''; this.summaryPanelOpen = false; this.summaryTableRows = []; this.selectedMonths = new Set([this.currentMonthKey()]); this.monthSelectionStarted = false; this.sortField = 'accrual_type'; this.sortDirection = 'asc';
		this.render(); this.bind(); this.applyMonthSelection(false);
	}
	render() {
		$(this.page.main).html(`<style>.ozf-expand{float:left;display:grid;place-items:center;width:23px;height:23px;margin:0 7px 0 0;border:1px solid #cbdaf0;border-radius:7px;background:#edf4ff;color:#2868cb;font-size:20px;line-height:1;transition:.18s}.ozf-expand.open{transform:rotate(90deg);background:#2868cb;color:#fff}.ozf-has-children{background:#fbfdff}.ozf-child-row{background:#f4f8fe}.ozf-child-row td{border-bottom-color:#dfe9f6!important}.ozf-child-line{display:block;height:1px;margin-left:28px;background:linear-gradient(90deg,#7ba6e8,transparent)}.ozf-operation-id{padding:4px 8px!important;border:1px solid #cfe0f6!important;border-radius:7px!important;background:#f1f6fd!important;color:#2264bd!important;font-weight:700}</style><div class="ozf-root">
		<section class="ozf-hero"><div><span>OZON FINANCE INTELLIGENCE</span><h1>Ozon 财务交易中心</h1><p>销售、退款、佣金、配送、推广、服务费与罚款，穿透至店铺、SKU和ERPNext物料。</p></div><div><button id="ozf-rematch">重新匹配物料</button><button id="ozf-refresh">刷新数据</button></div></section>
		<section class="ozf-filter"><div class="ozf-range"><span>月份</span><div id="ozf-month-range"></div></div><div class="ozf-filter-grid">
		${this.input('date_from','开始日期','date')}${this.input('date_to','结束日期','date')}${this.select('store','店铺')}${this.select('category','财务大类')}${this.select('direction','收支方向')}${this.select('currency','币种')}${this.select('status','状态')}${this.select('sync_type','同步类型')}${this.select('binding','物料绑定',[['','全部'],['bound','已绑定'],['unbound','未绑定'],['store','店铺级费用']])}<label class="wide">搜索<input data-filter="search" placeholder="交易ID / 订单 / SKU / 物料 / 结算号"></label></div></section>
		<div class="ozf-loading"><i></i><span>正在整理 Ozon 财务数据…</span></div><div class="ozf-content">
		<section class="ozf-card ozf-table-card"><header><div><h3>完整财务交易明细</h3><span id="ozf-count">—</span></div><div class="ozf-table-actions"><button id="ozf-toggle-summary" disabled title="请先选择一个具体类型">显示筛选汇总</button><button id="ozf-save-booked" disabled>保存记账状态</button><div id="ozf-pages"></div><button id="ozf-table-fullscreen" class="ozf-icon-button" title="全屏查看" aria-label="全屏查看">${this.fullscreenIcon(false)}</button></div></header><div id="ozf-type-filter" class="ozf-type-filter"></div><div class="ozf-table-layout"><div class="ozf-table-wrap"><table><thead><tr>${this.sortHead('is_booked','已记账','ozf-booked-head')}${this.sortHead('order_product','订单 / 商品','ozf-product-head')}${this.sortHead('manual_item','记账物料','ozf-manual-head')}${this.sortHead('accrual_type','应计项目类型（摘要）','ozf-accrual-head')}${this.sortHead('net_amount','净额','num')}${this.sortHead('accruals_for_sale','销售应计','num')}${this.sortHead('coinvestment_amount','合作伙伴计划应计','num')}${this.sortHead('posting_number','应计费用ID')}${this.sortHead('operation_date','发生时间')}${this.sortHead('sync_type','同步')}</tr></thead><tbody></tbody></table></div><aside id="ozf-filter-summary" class="ozf-filter-summary" hidden></aside></div></section>
		<section id="ozf-kpis" class="ozf-kpis"></section><section><div class="ozf-title"><h2>多币种资金全景</h2><span>各币种独立统计，不直接混合相加</span></div><div id="ozf-currencies" class="ozf-currencies"></div></section>
		<section class="ozf-grid"><article class="ozf-card span-8"><header><div><h3>资金趋势</h3><span>每日流入、流出与净额</span></div></header><div id="ozf-trend" class="ozf-chart tall"></div></article><article class="ozf-card span-4"><header><div><h3>财务大类</h3><span>当前币种构成</span></div></header><div id="ozf-category" class="ozf-chart tall"></div></article>
		<article class="ozf-card span-4"><header><div><h3>费用拆分</h3><span>佣金、配送、推广与服务费</span></div></header><div id="ozf-fees" class="ozf-chart"></div></article><article class="ozf-card span-4"><header><div><h3>店铺贡献</h3><span>净额与交易数</span></div></header><div id="ozf-stores" class="ozf-chart"></div></article><article class="ozf-card span-4"><header><div><h3>结算批次</h3><span>报告归集与最新发生时间</span></div></header><div id="ozf-statements" class="ozf-list"></div></article>
		<article class="ozf-card span-12"><header><div><h3>SKU 财务表现</h3><span>数量、净额与ERPNext物料绑定</span></div></header><div id="ozf-products" class="ozf-products"></div></article></section></div></div>`);
	}
	input(id,label,type){return `<label>${label}<input type="${type}" data-filter="${id}"></label>`;}
	select(id,label,options=[['','全部']]){return `<label>${label}<select data-filter="${id}">${options.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label>`;}
	sortHead(field,label,className=''){return `<th class="${className}"><button class="ozf-sort-head ${field===this.sortField?'active':''}" data-sort="${field}"><span>${label}</span><i>${field===this.sortField?(this.sortDirection==='asc'?'↑':'↓'):'↕'}</i></button></th>`;}
	bind() { const r=$(this.page.main),imageSelector='.ozf-product img,.ozf-related-product img,.ozf-summary-item-image'; r.on('click','[data-month]',e=>this.selectMonth(e.currentTarget.dataset.month));r.on('click','[data-sort]',e=>this.toggleSort(e.currentTarget.dataset.sort));r.on('click','#ozf-refresh',()=>{this.pageNo=1;this.load();});r.on('change','.ozf-filter [data-filter]',e=>{if(['date_from','date_to'].includes(e.currentTarget.dataset.filter)){this.selectedMonths.clear();this.monthSelectionStarted=false;this.renderMonthButtons();}this.pageNo=1;this.load();});let timer;r.on('input','[data-filter=search]',()=>{clearTimeout(timer);timer=setTimeout(()=>{this.pageNo=1;this.load();},450);});r.on('click','#ozf-pages button',e=>{this.pageNo=+e.currentTarget.dataset.page;this.load();});r.on('click','[data-copy]',e=>{navigator.clipboard.writeText(e.currentTarget.dataset.copy||'');frappe.show_alert({message:'已复制',indicator:'green'});});r.on('click','.ozf-bind',e=>this.bindItem({...e.currentTarget.dataset}));r.on('click','.ozf-finance-item-bind',e=>this.openFinancialItemDialog([e.currentTarget.dataset.name],e.currentTarget.dataset.item||''));r.on('click','.ozf-summary-item-bind',e=>{const row=this.summaryTableRows[Number(e.currentTarget.dataset.row)];if(row)this.openFinancialItemDialog(row.recordNames,row.manualItem||'');});r.on('click','#ozf-rematch',()=>this.rematch());r.on('change','.ozf-summary-booked-row',e=>this.setSummaryRowBooked(Number(e.currentTarget.dataset.row),e.currentTarget.checked));r.on('change','.ozf-summary-booked-all',e=>this.setAllSummaryBooked(e.currentTarget.checked));r.on('click','#ozf-toggle-summary',()=>this.toggleFilterSummary());r.on('click','.ozf-summary-copy-head',e=>this.copySummaryColumn(e.currentTarget.dataset.column));r.on('change','.ozf-summary-account-all',e=>this.setAllSummaryAccounts(e.currentTarget));r.on('change','.ozf-summary-account-row',e=>this.setSummaryRowAccount(Number(e.currentTarget.dataset.row),e.currentTarget.value));r.on('change','.ozf-summary-cost-all',e=>this.setAllSummaryCostCenters(e.currentTarget));r.on('change','.ozf-summary-cost-row',e=>this.setSummaryRowCostCenter(Number(e.currentTarget.dataset.row),e.currentTarget.value));r.on('focus','.ozf-searchable-choice',e=>e.currentTarget.select());r.on('click','#ozf-save-booked',()=>this.saveBookedStatus(false));r.on('click','#ozf-table-fullscreen',()=>this.toggleTableFullscreen());r.on('click','.ozf-type-button',e=>{const value=e.currentTarget.dataset.type||'';if(value===this.activeAccrualType)return;this.activeAccrualType=value;if(!value)this.summaryPanelOpen=false;this.pageNo=1;this.load();});r.on('mouseenter',imageSelector,e=>this.showImagePreview(e)).on('mousemove',imageSelector,e=>this.moveImagePreview(e)).on('mouseleave',imageSelector,()=>this.hideImagePreview());this.fullscreenKeyHandler=e=>{if(e.key==='Escape'&&this.tableFullscreen)this.toggleTableFullscreen(false);};document.addEventListener('keydown',this.fullscreenKeyHandler);}
	currentMonthKey(){return frappe.datetime.get_today().slice(0,7);}
	availableMonths(){const months=this.data?.available_months||[];return months.length?months:[this.currentMonthKey()];}
	monthBounds(month){const [year,value]=String(month).split('-').map(Number),lastDay=new Date(year,value,0).getDate();return {from:`${year}-${String(value).padStart(2,'0')}-01`,to:`${year}-${String(value).padStart(2,'0')}-${String(lastDay).padStart(2,'0')}`};}
	renderMonthButtons(){const months=this.availableMonths(),html=months.map(month=>{const label=Number(month.slice(5))+'月';return `<button data-month="${this.esc(month)}" class="${this.selectedMonths.has(month)?'active':''}">${label}</button>`;}).join('');$(this.page.main).find('#ozf-month-range').html(html);}
	selectMonth(month){const months=this.availableMonths();if(!months.includes(month))return;if(!this.monthSelectionStarted||!this.selectedMonths.size){this.selectedMonths=new Set([month]);this.monthSelectionStarted=true;}else if(this.selectedMonths.has(month)){if(this.selectedMonths.size>1)this.selectedMonths.delete(month);}else{this.selectedMonths.add(month);}const indexes=months.map((value,index)=>this.selectedMonths.has(value)?index:-1).filter(index=>index>=0);if(indexes.length){const first=Math.min(...indexes),last=Math.max(...indexes);this.selectedMonths=new Set(months.slice(first,last+1));}this.applyMonthSelection(true);}
	applyMonthSelection(reload=true){const months=[...this.selectedMonths].sort();if(!months.length)return;const first=this.monthBounds(months[0]),last=this.monthBounds(months[months.length-1]),r=$(this.page.main);r.find('[data-filter=date_from]').val(first.from);r.find('[data-filter=date_to]').val(last.to);this.renderMonthButtons();if(reload){this.pageNo=1;this.load();}}
	toggleSort(field){if(!field)return;if(this.sortField===field)this.sortDirection=this.sortDirection==='asc'?'desc':'asc';else{this.sortField=field;this.sortDirection=field==='accrual_type'?'asc':'desc';}this.updateSortHeaders();this.pageNo=1;this.load();}
	updateSortHeaders(){const r=$(this.page.main);r.find('[data-sort]').each((_,button)=>{const active=button.dataset.sort===this.sortField;$(button).toggleClass('active',active).find('i').text(active?(this.sortDirection==='asc'?'↑':'↓'):'↕');});}
	filters(){const f={};$(this.page.main).find('[data-filter]').each((_,x)=>f[x.dataset.filter]=$(x).val());f.accrual_type=this.activeAccrualType;f.sort_field=this.sortField;f.sort_direction=this.sortDirection;return f;}
	async load(){if(this.loading){this.reloadPending=true;return;}this.loading=true;const r=$(this.page.main).find('.ozf-root').addClass('loading');try{const response=await frappe.call({method:'fengjing_app.fengjing_business.page.ozon_financial_stora.ozon_financial_stora.get_dashboard_data',args:{filters:this.filters(),page:this.pageNo,page_size:this.pageSize}});this.data=response.message||{};this.fillOptions();this.draw();this.loaded=true;if(this.data.summary?.limited)frappe.show_alert({message:'当前日期范围超过5万条，请缩小日期范围。',indicator:'orange'},8);}catch(e){frappe.msgprint({title:'Ozon财务页面读取失败',message:e.message||'请查看错误日志',indicator:'red'});}finally{r.removeClass('loading');this.loading=false;if(this.reloadPending){this.reloadPending=false;this.load();}}}
	fillOptions(){const map={store:'stores',category:'categories',direction:'directions',currency:'currencies',status:'statuses',sync_type:'sync_types'},r=$(this.page.main);Object.entries(map).forEach(([field,key])=>{const el=r.find(`[data-filter=${field}]`),old=el.val();el.html('<option value="">全部</option>'+((this.data.options?.[key]||[]).map(v=>`<option value="${this.esc(v)}">${this.esc(v)}</option>`).join('')));el.val(old);});}
	draw(){this.renderMonthButtons();this.renderKpis();this.renderCurrencies();this.renderCharts();this.renderStatements();this.renderProducts();this.renderTable();}
	renderKpis(){const s=this.data.summary||{},cards=[['财务记录',s.records||0,'当前筛选范围'],['商品级交易',s.product_records||0,`${s.store_records||0} 条店铺级费用`],['物料绑定率',`${s.binding_rate||0}%`,`${s.bound||0} 已绑定 / ${s.unbound||0} 未绑定`],['退款记录',s.refunds||0,'根据Ozon返回标记'],['币种',Object.keys(s.currencies||{}).length,Object.keys(s.currencies||{}).join(' / ')||'暂无'],['同步异常',s.errors||0,s.errors?'请查看明细':'当前数据正常']];$(this.page.main).find('#ozf-kpis').html(cards.map((x,i)=>`<article class="c${i}"><span>${x[0]}</span><b>${this.esc(x[1])}</b><small>${this.esc(x[2])}</small></article>`).join(''));}
	renderCurrencies(){const data=this.data.summary?.currencies||{};$(this.page.main).find('#ozf-currencies').html(Object.entries(data).map(([c,v])=>`<article><header><i>${this.flag(c)}</i><div><b>${this.esc(c)}</b><span>当地币种</span></div></header><strong class="${v.net>=0?'positive':'negative'}">${this.money(v.net,c)}</strong><div><span>流入<b>${this.money(v.inflow,c)}</b></span><span>流出<b>${this.money(v.outflow,c)}</b></span><span>销售应计<b>${this.money(v.sales,c)}</b></span><span>费用绝对值<b>${this.money(v.fees,c)}</b></span></div></article>`).join('')||'<p class="empty">暂无金额数据</p>');}
	async renderCharts(){if(typeof echarts==='undefined'){await new Promise((ok,bad)=>frappe.require('/assets/fengjing_app/js/图表-echarts.js',ok,bad));}this.charts.forEach(c=>c.dispose());this.charts=[];const daily=this.data.daily||{},dates=Object.keys(daily),currencies=[...new Set(dates.flatMap(d=>Object.keys(daily[d])))];this.chart('ozf-trend',{tooltip:{trigger:'axis',appendToBody:true},legend:{top:5,type:'scroll'},grid:{left:75,right:25,top:50,bottom:48},xAxis:{type:'category',data:dates},yAxis:{type:'value'},dataZoom:[{type:'inside'},{type:'slider',height:16,bottom:7}],series:currencies.flatMap(c=>[{name:`${c} 流入`,type:'line',smooth:true,showSymbol:false,data:dates.map(d=>daily[d][c]?.inflow||0)},{name:`${c} 流出`,type:'line',smooth:true,showSymbol:false,data:dates.map(d=>daily[d][c]?.outflow||0)},{name:`${c} 净额`,type:'bar',data:dates.map(d=>daily[d][c]?.net||0)}])});const currency=$(this.page.main).find('[data-filter=currency]').val()||Object.keys(this.data.categories||{})[0],categories=this.data.categories?.[currency]||{};this.chart('ozf-category',{tooltip:{trigger:'item',appendToBody:true},legend:{bottom:4,type:'scroll'},series:[{type:'pie',radius:['38%','68%'],center:['50%','43%'],data:Object.entries(categories).map(([name,v])=>({name,value:Math.abs(v.amount),signed:v.amount}))}]});this.bar('ozf-fees',this.data.fees?.[currency]||{},v=>Math.abs(v),'#ff7657');this.bar('ozf-stores',this.data.stores?.[currency]||{},v=>v.amount,'#356fe5');}
	bar(id,obj,value,color){const rows=Object.entries(obj).sort((a,b)=>Math.abs(value(b[1]))-Math.abs(value(a[1]))).slice(0,20);this.chart(id,{tooltip:{trigger:'axis',appendToBody:true},grid:{left:150,right:25,top:15,bottom:25},xAxis:{type:'value'},yAxis:{type:'category',data:rows.map(x=>x[0]),axisLabel:{width:138,overflow:'truncate'}},series:[{type:'bar',barMaxWidth:20,data:rows.map(x=>value(x[1])),itemStyle:{color,borderRadius:[0,8,8,0]}}]});}
	chart(id,option){const el=$(this.page.main).find('#'+id)[0];if(!el)return;const chart=echarts.init(el);chart.setOption(option);this.charts.push(chart);}
	renderStatements(){const rows=this.data.statements||[];$(this.page.main).find('#ozf-statements').html(rows.map(x=>`<div><i>结</i><span><b>${this.esc(x.statement)}</b><small>${this.esc(x.store||'未归属')} · ${x.count}条 · ${this.date(x.latest)}</small></span><strong class="${x.amount>=0?'positive':'negative'}">${this.money(x.amount,x.currency)}</strong></div>`).join('')||'<p class="empty">暂无结算批次</p>');}
	renderProducts(){const rows=(this.data.products||[]).slice(0,100);$(this.page.main).find('#ozf-products').html(rows.map((x,i)=>`<article><em>${i+1}</em>${x.image?`<img src="${this.esc(x.image)}">`:'<i>O³</i>'}<div><b>${this.esc(x.item_name||x.product_name||x.offer_id||x.sku||'未命名商品')}</b><small><button data-copy="${this.esc(x.sku||'')}">SKU ${this.esc(x.sku||'—')}</button> · ${this.esc(x.store||'未归属')}</small><small>数量 ${this.num(x.quantity)} · ${x.transactions}条财务记录</small></div><aside>${Object.entries(x.amounts||{}).map(([c,v])=>`<strong class="${v>=0?'positive':'negative'}">${this.money(v,c)}</strong>`).join('')}${x.item?`<a href="/app/item/${encodeURIComponent(x.item)}">${this.esc(x.item)}</a>`:`<button class="ozf-bind" data-store="${this.esc(x.store||'')}" data-sku="${this.esc(x.sku||'')}" data-offer_id="${this.esc(x.offer_id||'')}">绑定物料</button>`}</aside></article>`).join('')||'<p class="empty">暂无SKU级财务记录</p>');}
	renderTable(){const p=this.data.pagination||{},r=$(this.page.main),types=this.data.type_filter||{},counts=types.counts||{},booked=types.booked_counts||{},dateFrom=r.find('[data-filter=date_from]').val()||'—',dateTo=r.find('[data-filter=date_to]').val()||'—';if(this.activeAccrualType&&!Object.prototype.hasOwnProperty.call(counts,this.activeAccrualType)){this.activeAccrualType='';this.summaryPanelOpen=false;}const buttons=[['',`全部`,types.total||0,types.booked_total||0],...Object.entries(counts).map(([name,count])=>[name,name,count,booked[name]||0])];r.find('#ozf-type-filter').html(`<span>类型</span>${buttons.map(([value,label,count,bookedCount])=>`<button class="ozf-type-button ${value===this.activeAccrualType?'active':''}" data-type="${this.esc(value)}"><b>${this.esc(label)}</b><em class="${count>0&&bookedCount===count?'booked':'unbooked'}" title="${bookedCount}/${count} 条已记账">${this.num(count)}</em></button>`).join('')}<i class="${types.valid?'valid':'invalid'}">${types.valid?`分类合计已校验：${this.num(types.sum||0)}`:`数量校验异常：${this.num(types.sum||0)} / ${this.num(types.total||0)}`}</i>`);r.find('#ozf-count').text(`共 ${this.num(p.total)} 条 · 第 ${p.page}/${p.pages} 页 · ${dateFrom} 至 ${dateTo}`);r.find('#ozf-pages').html(`<button data-page="${p.page-1}" ${p.page<=1?'disabled':''}>上一页</button><button data-page="${p.page+1}" ${p.page>=p.pages?'disabled':''}>下一页</button>`);r.find('.ozf-table-wrap>table>tbody').html((this.data.rows||[]).map(x=>this.financeRows(x)).join('')||'<tr><td colspan="10" class="empty">当前条件下暂无财务记录</td></tr>');this.updateSortHeaders();this.renderFilterSummary();this.syncBookedCheckboxes();}
	renderFilterSummary(){
		const r=$(this.page.main),button=r.find('#ozf-toggle-summary'),panel=r.find('#ozf-filter-summary'),summary=this.data.filtered_type_summary;
		if(!this.activeAccrualType||!summary){this.summaryTableRows=[];button.prop('hidden',false).prop('disabled',true).removeClass('active').attr('title','请先选择一个具体类型').text('显示筛选汇总');panel.prop('hidden',true).empty();return;}
		button.prop('hidden',false).prop('disabled',false).attr('title','').toggleClass('active',this.summaryPanelOpen).text(this.summaryPanelOpen?'关闭筛选汇总':'显示筛选汇总');
		panel.prop('hidden',!this.summaryPanelOpen);
		if(!this.summaryPanelOpen)return;
		this.summaryTableRows=this.buildSummaryTableRows(summary);
		const sections=(summary.currencies||[]).map(group=>{
			const equation=summary.is_sales_commission?`<div class="ozf-summary-total-equation"><b>${this.amountNumber(group.sale_total)}</b><i>+</i><b>${this.amountNumber(group.commission_total)}</b><i>=</i><b>${this.amountNumber(group.total)}</b><em class="${group.equation_valid?'valid':'invalid'}">${group.equation_valid?'验算通过':`差额 ${this.amountNumber(group.equation_difference)}`}</em></div>`:'';
			const total=`<div class="ozf-summary-total"><span>总金额 · ${this.esc(group.currency)}</span><strong class="${group.total>=0?'positive':'negative'}">${this.money(group.total,group.currency)}</strong><small>${this.num(group.count)} 条记录</small>${equation}</div>`;
			const type=`<div class="ozf-summary-type"><span>类型分组</span><button data-copy="${this.esc(summary.type)}" title="点击复制类型分组">${this.esc(summary.type)}</button></div>`;
			const rows=this.summaryTableRows.map((row,index)=>row.currency===group.currency?this.renderSummaryRow(row,index,summary):'').join('');
			return `<section>${total}${type}<div class="ozf-summary-items"><h5>按物料和应计项目类型合计</h5><div class="ozf-summary-table-wrap"><table class="${summary.is_sales_commission?'sales-equation':''}">${this.renderSummaryHead(summary)}<tbody>${rows}</tbody></table></div></div></section>`;
		}).join('');
		panel.html(`${this.renderLookupLists()}<header><div><span>当前筛选汇总</span><h4>${this.esc(summary.type)}</h4></div><div class="ozf-summary-head-actions"><b>${this.num(summary.count)} 条</b></div></header>${sections||'<p class="empty">当前筛选下暂无金额</p>'}`);
		this.syncBookedCheckboxes();
	}
	toggleFilterSummary(){if(!this.activeAccrualType)return;this.summaryPanelOpen=!this.summaryPanelOpen;this.renderFilterSummary();}
	buildSummaryTableRows(summary){const rows=[];for(const group of summary.currencies||[]){for(const item of group.items||[]){rows.push({currency:String(group.currency||''),item:String(item.item||''),itemName:String(item.item_name||item.item||'未明确归属物料'),image:String(item.image||''),manualItem:String(item.manual_item||''),manualItemName:String(item.manual_item_name||item.manual_item||''),manualItemImage:String(item.manual_item_image||''),manualItemMixed:!!item.manual_item_mixed,count:Number(item.count||0),amount:this.plainAmount(item.amount),sale:this.plainAmount(item.sale_amount),commission:this.plainAmount(item.commission_amount),type:String(item.accrual_type||summary.type||''),postingNumbers:item.posting_numbers||[],recordNames:item.record_names||[],bookedNames:item.booked_names||[],accountCode:String(item.account_code||''),accountMixed:!!item.account_mixed,costCenter:String(item.cost_center||''),costCenterMixed:!!item.cost_center_mixed,equationValid:!!item.equation_valid,equationDifference:this.plainAmount(item.equation_difference)});}}return rows;}
	renderLookupLists(){const accounts=(this.data.account_options||[]).map(row=>`<option value="${this.esc(row.name)}">${this.esc(row.code)}</option>`).join(''),centers=(this.data.cost_center_options||[]).map(row=>`<option value="${this.esc(row.value)}">${this.esc(row.label)}</option>`).join('');return `<datalist id="ozf-account-options">${accounts}</datalist><datalist id="ozf-cost-center-options">${centers}</datalist>`;}
	renderSummaryHead(summary){const copy=(column,label,extra='')=>`<th class="${extra}"><button class="ozf-summary-copy-head" data-column="${column}" title="点击一次复制整列${label}">${label}<small>复制整列</small></button></th>`;const choice=(column,label,inputClass,list,placeholder)=>`<th class="ozf-choice-head"><button class="ozf-summary-copy-head" data-column="${column}" title="点击一次复制整列${label}">${label}<small>复制整列</small></button><input class="${inputClass} ozf-searchable-choice" list="${list}" placeholder="${placeholder}" title="搜索并应用到整列"></th>`;const booked='<th class="ozf-summary-booked-head"><label title="全选或取消当前筛选汇总中的全部记录"><input class="ozf-summary-booked-all" type="checkbox"><span>已记账</span></label></th>';const amounts=summary.is_sales_commission?`${copy('sale','销售','num')}<th class="ozf-equation-sign">+</th>${copy('commission','Ozon代理佣金','num')}<th class="ozf-equation-sign">=</th>${copy('amount','商品销售与佣金','num')}`:copy('amount','金额','num');return `<thead><tr>${booked}${choice('costCenter','成本中心','ozf-summary-cost-all','ozf-cost-center-options','搜索并整列设置')}${copy('item','对应物料')}${choice('account','科目代码','ozf-summary-account-all','ozf-account-options','搜索并整列设置')}${amounts}${copy('type','应计项目类型')}${copy('manualItem','记账物料')}</tr></thead>`;}
	renderSummaryRow(row,index,summary){const item=row.item?`<div class="ozf-summary-item-cell">${row.image?`<img class="ozf-summary-item-image" src="${this.esc(row.image)}" alt="">`:'<i>物</i>'}<span><button data-copy="${this.esc(row.item)}" title="点击复制物料ID"><b>${this.esc(row.item)}</b></button><small>${this.esc(row.itemName)} · ${this.num(row.count)} 条</small></span></div>`:`<div class="ozf-summary-item-cell"><i>—</i><span><b>未明确对应物料</b><small>${this.num(row.count)} 条</small></span></div>`,manualLabel=row.manualItemMixed?'多个记账物料':(row.manualItemName||row.manualItem||'未选择记账物料'),manual=`<div class="ozf-summary-item-cell ozf-manual-item-cell">${row.manualItemImage?`<img class="ozf-summary-item-image" src="${this.esc(row.manualItemImage)}" alt="">`:'<i>记</i>'}<span>${row.manualItem?`<button data-copy="${this.esc(row.manualItem)}" title="点击复制记账物料ID"><b>${this.esc(row.manualItem)}</b></button>`:`<b>${this.esc(manualLabel)}</b>`}<small>${row.manualItem?this.esc(row.manualItemName):'独立于对应物料'}</small><button class="ozf-summary-item-bind" data-row="${index}" title="只保存到财务记录，不写入SKU映射">${row.manualItem||row.manualItemMixed?'修改记账物料':'选择记账物料'}</button></span></div>`;const amount=(value,column)=>`<td class="num"><button class="${Number(value)>=0?'positive':'negative'}" data-copy="${this.copyAmount(value)}" title="点击复制不带负号的纯数字${column}"><b>${this.amountNumber(value)}</b><small>${this.esc(row.currency)}</small></button></td>`;const equation=summary.is_sales_commission?`${amount(row.sale,'销售金额')}<td class="ozf-equation-sign">+</td>${amount(row.commission,'Ozon代理佣金')}<td class="ozf-equation-sign ${row.equationValid?'valid':'invalid'}" title="${row.equationValid?'验算通过':`验算差额 ${this.esc(row.equationDifference)}`}">${row.equationValid?'=':'≠'}<small>${row.equationValid?'✓':this.esc(row.equationDifference)}</small></td>${amount(row.amount,'商品销售与佣金')}`:amount(row.amount,'金额');const account=this.summaryRowAccount(row),costCenter=this.summaryRowCostCenter(row),typeValues=this.summaryTypeValues(row),typeCell=typeValues.map(value=>`<button data-copy="${this.esc(value)}" title="点击复制应计项目类型和应计费用ID">${this.esc(value)}</button>`).join('');return `<tr class="${row.item?'':'ozf-summary-unassigned'}"><td class="ozf-summary-booked-cell"><input class="ozf-summary-booked-row" type="checkbox" data-row="${index}" aria-label="已记账"></td><td class="ozf-choice-cell"><input class="ozf-summary-cost-row ozf-searchable-choice" data-row="${index}" list="ozf-cost-center-options" value="${this.esc(costCenter)}" placeholder="${row.costCenterMixed&&!costCenter?'多个成本中心':'搜索成本中心'}" title="当前行可单独搜索和修改成本中心"></td><td>${item}</td><td class="ozf-choice-cell"><input class="ozf-summary-account-row ozf-searchable-choice" data-row="${index}" list="ozf-account-options" value="${this.esc(account)}" placeholder="${row.accountMixed&&!account?'多个科目':'搜索科目代码'}" title="当前行可单独搜索和修改科目代码"></td>${equation}<td><div class="ozf-summary-type-values">${typeCell}</div></td><td>${manual}</td></tr>`;}
	summaryRowAccountCode(row){const pending=row.recordNames.map(name=>this.accountCodeChanges.has(name)?this.accountCodeChanges.get(name):null).filter(value=>value!==null);if(pending.length===row.recordNames.length&&pending.length){const unique=[...new Set(pending)];return unique.length===1?unique[0]:'';}return row.accountMixed?'':row.accountCode;}
	accountOption(value){value=String(value||'').trim();return (this.data.account_options||[]).find(row=>String(row.code)===value||String(row.name)===value);}
	accountDisplay(value){const option=this.accountOption(value);return option?String(option.name):String(value||'');}
	summaryRowAccount(row){return this.accountDisplay(this.summaryRowAccountCode(row));}
	summaryRowCostCenter(row){const pending=row.recordNames.map(name=>this.costCenterChanges.has(name)?this.costCenterChanges.get(name):null).filter(value=>value!==null);if(pending.length===row.recordNames.length&&pending.length){const unique=[...new Set(pending)];return unique.length===1?unique[0]:'';}return row.costCenterMixed?'':row.costCenter;}
	validAccountCode(value){return !value||!!this.accountOption(value);}
	validCostCenter(value){return !value||(this.data.cost_center_options||[]).some(row=>String(row.value)===value);}
	copyAmount(value){return this.plainAmount(Math.abs(Number(value||0)));}
	summaryTypeValues(row){const ids=[...new Set((row.postingNumbers||[]).map(value=>String(value||'').trim()).filter(Boolean))];return [`${row.type}${ids.length?`_${ids.join('_')}`:''}`];}
	summaryBookedState(row){const booked=new Set(row.bookedNames||[]),values=(row.recordNames||[]).filter(Boolean).map(name=>this.bookedChanges.has(name)?Number(this.bookedChanges.get(name)):Number(booked.has(name)));return {checked:values.length>0&&values.every(Boolean),mixed:values.some(Boolean)&&!values.every(Boolean)};}
	setSummaryRowBooked(index,checked,schedule=true){const row=this.summaryTableRows[index];if(!row)return;const booked=new Set(row.bookedNames||[]),value=checked?1:0;for(const name of row.recordNames||[]){if(!name)continue;const original=booked.has(name)?1:0;if(value===original)this.bookedChanges.delete(name);else this.bookedChanges.set(name,value);}this.syncBookedCheckboxes();this.updateSaveButton();if(schedule)this.scheduleAutoSave();}
	setAllSummaryBooked(checked){this.summaryTableRows.forEach((row,index)=>this.setSummaryRowBooked(index,checked,false));this.syncBookedCheckboxes();this.updateSaveButton();this.scheduleAutoSave();}
	syncBookedCheckboxes(){const r=$(this.page.main);r.find('.ozf-booked-input').each((_,input)=>{const name=input.dataset.name,value=this.bookedChanges.has(name)?Number(this.bookedChanges.get(name)):Number(input.dataset.booked||0);$(input).prop('checked',!!value);});this.summaryTableRows.forEach((row,index)=>{const state=this.summaryBookedState(row),input=r.find(`.ozf-summary-booked-row[data-row="${index}"]`);input.prop('checked',state.checked).prop('indeterminate',state.mixed);});const states=this.summaryTableRows.flatMap(row=>{const booked=new Set(row.bookedNames||[]);return (row.recordNames||[]).filter(Boolean).map(name=>this.bookedChanges.has(name)?Number(this.bookedChanges.get(name)):Number(booked.has(name)));}),all=states.length>0&&states.every(Boolean),some=states.some(Boolean),header=r.find('.ozf-summary-booked-all');header.prop('checked',all).prop('indeterminate',some&&!all);}
	summaryColumnValues(column){if(column==='type')return this.summaryTableRows.flatMap(row=>this.summaryTypeValues(row)).filter(Boolean);const amounts=new Set(['sale','commission','amount']);return this.summaryTableRows.map(row=>{if(amounts.has(column))return this.copyAmount(row[column]);if(column==='account')return this.summaryRowAccount(row);if(column==='costCenter')return this.summaryRowCostCenter(row);return String(row[column]??'');}).filter(value=>value!=='');}
	async copySummaryColumn(column){const labels={item:'对应物料',manualItem:'记账物料',sale:'销售',commission:'Ozon代理佣金',amount:this.data.filtered_type_summary?.is_sales_commission?'商品销售与佣金':'金额',type:'应计项目类型',account:'科目代码',costCenter:'成本中心'},values=this.summaryColumnValues(column);if(!labels[column]||!values.length){frappe.show_alert({message:'这一列没有可复制的内容',indicator:'orange'});return;}await navigator.clipboard.writeText(values.join(column==='type'?';':'\n'));frappe.show_alert({message:`已复制整列${labels[column]}，共 ${values.length} 行`,indicator:'green'});}
	setSummaryRowAccount(index,value,schedule=true){const row=this.summaryTableRows[index],input=$(this.page.main).find(`.ozf-summary-account-row[data-row="${index}"]`);if(!row)return;value=String(value||'').trim();if(!this.validAccountCode(value)){input.val(this.summaryRowAccount(row));frappe.show_alert({message:'请选择搜索结果中的有效科目',indicator:'orange'},5);return;}const code=value?this.accountOption(value).code:'';for(const name of row.recordNames){if(!row.accountMixed&&code===row.accountCode)this.accountCodeChanges.delete(name);else this.accountCodeChanges.set(name,code);}input.val(this.accountDisplay(code));this.updateSaveButton();if(schedule)this.scheduleAutoSave();}
	setAllSummaryAccounts(input){const value=String(input.value||'').trim();if(!this.validAccountCode(value)){$(input).val('');frappe.show_alert({message:'请选择搜索结果中的有效科目代码',indicator:'orange'},5);return;}this.summaryTableRows.forEach((row,index)=>this.setSummaryRowAccount(index,value,false));$(input).val('');this.updateSaveButton();this.scheduleAutoSave();frappe.show_alert({message:`已将科目应用到 ${this.summaryTableRows.length} 行，将自动保存`,indicator:'blue'},5);}
	setSummaryRowCostCenter(index,value,schedule=true){const row=this.summaryTableRows[index],input=$(this.page.main).find(`.ozf-summary-cost-row[data-row="${index}"]`);if(!row)return;value=String(value||'').trim();if(!this.validCostCenter(value)){input.val(this.summaryRowCostCenter(row));frappe.show_alert({message:'请选择搜索结果中的有效成本中心',indicator:'orange'},5);return;}for(const name of row.recordNames){if(!row.costCenterMixed&&value===row.costCenter)this.costCenterChanges.delete(name);else this.costCenterChanges.set(name,value);}input.val(value);this.updateSaveButton();if(schedule)this.scheduleAutoSave();}
	setAllSummaryCostCenters(input){const value=String(input.value||'').trim();if(!this.validCostCenter(value)){$(input).val('');frappe.show_alert({message:'请选择搜索结果中的有效成本中心',indicator:'orange'},5);return;}this.summaryTableRows.forEach((row,index)=>this.setSummaryRowCostCenter(index,value,false));$(input).val('');this.updateSaveButton();this.scheduleAutoSave();frappe.show_alert({message:`已将成本中心应用到 ${this.summaryTableRows.length} 行，将自动保存`,indicator:'blue'},5);}
	pendingNames(){return new Set([...this.bookedChanges.keys(),...this.accountCodeChanges.keys(),...this.costCenterChanges.keys()]);}
	updateSaveButton(){const size=this.pendingNames().size,button=$(this.page.main).find('#ozf-save-booked');if(this.savingChanges){button.prop('disabled',true).text('正在自动保存…');return;}button.prop('disabled',size===0).text(size?`立即保存 (${size}) · 自动`:'已自动保存');}
	scheduleAutoSave(){clearTimeout(this.autoSaveTimer);if(!this.pendingNames().size)return;this.autoSaveTimer=setTimeout(()=>this.saveBookedStatus(true),900);}
	financeRows(x){
		const feeId=x.posting_number||'',children=x.breakdown||[],key=String(x.name||'').replace(/[^A-Za-z0-9_-]/g,''),booked=this.bookedChanges.has(x.name)?this.bookedChanges.get(x.name):Number(x.is_booked||0),currency=x.currency_code||'';
		const related=x.related_products||[];
		const manualItem=x.manual_corresponding_item?`<button class="ozf-copy-value" data-copy="${this.esc(x.manual_corresponding_item)}" title="点击复制记账物料ID">${this.esc(x.manual_item_name||x.manual_corresponding_item)}</button>`:'<span class="muted">未选择</span>',manualItemCell=`<div class="ozf-finance-item-cell">${manualItem}<button class="ozf-finance-item-bind" data-name="${this.esc(x.name)}" data-item="${this.esc(x.manual_corresponding_item||'')}" title="只记录当前财务条目的记账物料">${x.manual_corresponding_item?'修改':'选择'}</button></div>`;
		const productCell=x.sku?this.productCard({product_name:x.product_name,offer_id:x.offer_id,sku:x.sku,order_number:x.order_number,quantity:x.quantity,item:x.corresponding_item,item_name:x.corresponding_item_name,image:x.corresponding_item_image}):this.relatedProducts(related);
		const netCell=`<button class="ozf-copy-amount ${x.net_amount>=0?'positive':'negative'}" data-copy="${this.copyAmount(x.net_amount)}" title="点击复制不带负号的净额"><b>${this.amountNumber(x.net_amount)}</b><small>${this.esc(currency)}</small></button>`;
		const salesCell=Number(x.accruals_for_sale||0)!==0?`<b>${this.amountNumber(x.accruals_for_sale)}</b><small>${this.esc(currency)}</small>`:'';
		const coinvestmentCell=Number(x.coinvestment_amount||0)!==0?`<b>${this.amountNumber(x.coinvestment_amount)}</b><small>${this.esc(currency)}</small>`:'';
		const type=this.accrualType(x),reason=this.accrualReason(x);
		const parent=`<tr class="${children.length?'ozf-has-children':''}"><td class="ozf-booked-cell"><input class="ozf-booked-input" type="checkbox" data-name="${this.esc(x.name)}" data-booked="${Number(x.is_booked||0)?1:0}" ${booked?'checked':''} disabled title="请在筛选汇总中修改记账状态" aria-label="已记账（只读）"></td><td class="ozf-product-cell">${productCell}</td><td class="ozf-manual-cell">${manualItemCell}</td><td class="ozf-accrual-cell"><button class="ozf-copy-text" data-copy="${this.esc(type)}" title="点击复制应计项目类型"><b>${this.esc(type)}</b></button><button class="ozf-copy-text" data-copy="${this.esc(reason)}" title="点击复制摘要"><small>${this.esc(reason)}</small></button></td><td class="num">${netCell}</td><td class="num">${salesCell}</td><td class="num">${coinvestmentCell}</td><td>${feeId?`<button class="ozf-operation-id" data-copy="${this.esc(feeId)}">${this.esc(feeId)}</button>`:'<span class="muted">—</span>'}</td><td><b>${this.date(x.operation_date)}</b><small>${this.esc(x.payment_date?'付款 '+this.date(x.payment_date):'')}</small></td><td><b>${this.esc(x.sync_type||'—')}</b><small>${this.esc(x.sync_status||'—')} · v${x.data_version||1}</small></td></tr>`;
		const detail=children.map(child=>{const childCurrency=child.currency||currency,childProduct=this.productCard({product_name:x.product_name||'商品明细',sku:child.sku||x.sku,order_number:x.order_number,quantity:child.quantity,item:x.corresponding_item,item_name:x.corresponding_item_name,image:x.corresponding_item_image});return `<tr class="ozf-child-row" data-parent="${key}"><td></td><td class="ozf-product-cell">${childProduct}</td><td></td><td class="ozf-accrual-cell"><button class="ozf-copy-text" data-copy="${this.esc(child.label)}" title="点击复制应计项目类型"><b>${this.esc(child.label)}</b></button><button class="ozf-copy-text" data-copy="${this.esc(child.detail)}" title="点击复制摘要"><small>${this.esc(child.detail)}</small></button></td><td class="num"><button class="ozf-copy-amount ${child.amount>=0?'positive':'negative'}" data-copy="${this.copyAmount(child.amount)}" title="点击复制不带负号的金额"><b>${this.amountNumber(child.amount)}</b><small>${this.esc(childCurrency)}</small></button></td><td></td><td></td><td></td><td></td><td></td></tr>`;}).join('');
		return parent+detail;
	}
	quantityBadge(quantity){const value=Number(quantity||0);return `<em class="ozf-quantity ${value===1?'one':'many'}">${this.num(value)} 件</em>`;}
	productCard(product,related=false){const item=product.item?`<button class="ozf-product-item" data-copy="${this.esc(product.item)}" title="点击复制对应物料ID">对应物料：${this.esc(product.item_name||product.item)}</button>`:'';return `<div class="ozf-product ${related?'ozf-related-product':''}"><span>${product.image?`<img src="${this.esc(product.image)}" alt="">`:'O³'}</span><div><b>${this.esc(product.product_name||product.offer_id||product.sku||'关联商品')}</b><small>SKU ${this.esc(product.sku||'—')} · ${this.esc(product.order_number||'无订单号')} ${this.quantityBadge(product.quantity)}</small>${related?'<small class="ozf-related-source">来自关联商品</small>':''}${item}</div></div>`;}
	relatedProducts(products){if(!products.length)return '<span class="muted">—</span>';return `<div class="ozf-related-list"><strong>关联商品 ${products.length}</strong>${products.map(product=>this.productCard(product,true)).join('')}</div>`;}
	openFinancialItemDialog(recordNames,currentItem=''){const names=(recordNames||[]).filter(Boolean);if(!names.length)return;const dialog=new frappe.ui.Dialog({title:`选择记账物料 · ${names.length} 条`,fields:[{fieldtype:'HTML',options:'<div class="ozf-dialog">记账物料是独立字段，不会改变“对应物料”，也不会写入 SKU 物料映射。</div>'},{fieldtype:'Link',fieldname:'item',label:'记账物料',options:'Item',default:currentItem}],primary_action_label:'保存记账物料',primary_action:async values=>{if(!values.item){frappe.show_alert({message:'请选择记账物料；需要清除时请使用“清除记账物料”',indicator:'orange'},5);return;}await this.saveFinancialItem(names,values.item);dialog.hide();}});dialog.set_secondary_action_label('清除记账物料');dialog.set_secondary_action(async()=>{await this.saveFinancialItem(names,'');dialog.hide();});dialog.show();}
	async saveFinancialItem(recordNames,item){const response=await frappe.call({method:'fengjing_app.fengjing_business.page.ozon_financial_stora.ozon_financial_stora.bind_financial_item',freeze:true,freeze_message:'正在保存记账物料…',args:{record_names:JSON.stringify(recordNames),item}});frappe.show_alert({message:item?`已保存 ${response.message?.updated||0} 条记录的记账物料`:`已清除 ${response.message?.updated||0} 条记录的记账物料`,indicator:'green'},6);await this.load();}
	async saveBookedStatus(auto=false){if(this.savingChanges){this.scheduleAutoSave();return;}const names=this.pendingNames();if(!names.size)return;clearTimeout(this.autoSaveTimer);const booked=new Map(this.bookedChanges),accounts=new Map(this.accountCodeChanges),centers=new Map(this.costCenterChanges);this.savingChanges=true;this.updateSaveButton();try{const changes=[...names].map(name=>{const row={name};if(booked.has(name))row.is_booked=booked.get(name);if(accounts.has(name))row.account_code=accounts.get(name);if(centers.has(name))row.cost_center=centers.get(name);return row;});const response=await frappe.call({method:'fengjing_app.fengjing_business.page.ozon_financial_stora.ozon_financial_stora.save_booked_status',args:{changes:JSON.stringify(changes)}});for(const [name,value] of booked)if(this.bookedChanges.get(name)===value)this.bookedChanges.delete(name);for(const [name,value] of accounts)if(this.accountCodeChanges.get(name)===value)this.accountCodeChanges.delete(name);for(const [name,value] of centers)if(this.costCenterChanges.get(name)===value)this.costCenterChanges.delete(name);this.savingChanges=false;this.updateSaveButton();const result=response.message||{};frappe.show_alert({message:`${auto?'已自动保存':'已保存'} ${result.updated||0} 条：科目 ${result.account_updated||0} 条，成本中心 ${result.cost_center_updated||0} 条`,indicator:'green'},5);await this.load();if(this.pendingNames().size)this.scheduleAutoSave();}catch(e){this.savingChanges=false;this.updateSaveButton();frappe.msgprint({title:'保存失败',message:e.message||'请查看错误日志',indicator:'red'});}}
	fullscreenIcon(open){return open?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 4v5H4M15 4v5h5M9 20v-5H4M15 20v-5h5"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 4H4v5M15 4h5v5M9 20H4v-5M15 20h5v-5"/></svg>';}
	toggleTableFullscreen(force){const card=$(this.page.main).find('.ozf-table-card'),root=$(this.page.main).find('.ozf-root')[0];const open=typeof force==='boolean'?force:!this.tableFullscreen;this.tableFullscreen=open;if(open){const rect=root?.getBoundingClientRect();card.css('--ozf-fullscreen-left',`${Math.max(0,rect?.left||0)}px`).addClass('ozf-table-fullscreen');$('body').addClass('ozf-table-fullscreen-open');card.find('#ozf-table-fullscreen').attr({'title':'退出全屏','aria-label':'退出全屏'}).html(this.fullscreenIcon(true));}else{card.removeClass('ozf-table-fullscreen').css('--ozf-fullscreen-left','');$('body').removeClass('ozf-table-fullscreen-open');card.find('#ozf-table-fullscreen').attr({'title':'全屏查看','aria-label':'全屏查看'}).html(this.fullscreenIcon(false));}setTimeout(()=>this.charts.forEach(chart=>chart.resize()),80);}
	showImagePreview(e){if(!this.imagePreview)this.imagePreview=$('<div class="ozf-image-preview"><img alt="商品图片预览"></div>').appendTo(document.body);this.imagePreview.find('img').attr('src',e.currentTarget.src);this.imagePreview.show();this.moveImagePreview(e);}
	moveImagePreview(e){if(!this.imagePreview)return;const size=250,gap=18,left=e.clientX+gap+size>window.innerWidth?Math.max(8,e.clientX-size-gap):e.clientX+gap,top=Math.max(8,Math.min(window.innerHeight-size-8,e.clientY-size/2));this.imagePreview.css({left,top});}
	hideImagePreview(){this.imagePreview?.hide();}
	accrualType(x){if(x.accrual_type_label)return x.accrual_type_label;const key=String(x.operation_type_name||x.operation_type||'').trim(),description=String(x.description||'').trim();const byName={POSTING:'商品销售与佣金',Acquiring:'收单服务费',PayPerClick:'按点击付费',RfbsGlobalDelivery:'国际配送服务',RfbsGlobalAgentFee:'Ozon代理佣金',RfbsGlobalIntermediaryService:'国际运输组织合同服务',RfbsGlobalPlatformConnectionService:'Ozon物流平台接入服务',Promotion:'推广服务',DefectFineErrors:'商品缺陷罚款',ReturnFlowLogistic:'退货运费','Обратная логистика':'退货运费'};const byDescription={'Эквайринг':'收单服务费','Оплата за клик':'按点击付费','Услуги международной доставки':'国际配送服务','Агентское вознаграждение Ozon':'Ozon代理佣金','Услуги по заключению договора на организацию международной перевозки':'国际运输组织合同服务','Электронная услуга подключения к логистической Платформе Ozon':'Ozon物流平台接入服务','Обратная логистика':'退货运费'};return byName[key]||byDescription[description]||description||key||'未分类应计项目';}
	accrualReason(x){const reason=String(x.description||'').trim();const translations={'Превышение индекса ошибок':'错误指数超标','Обратная логистика':'退货运费'};return translations[reason]||reason||'-';}
	bindItem(data){const dialog=new frappe.ui.Dialog({title:'绑定 Ozon SKU 到 ERPNext 物料',fields:[{fieldtype:'HTML',options:`<div class="ozf-dialog">SKU：${this.esc(data.sku||'—')}<br>店铺：${this.esc(data.store||'—')}</div>`},{fieldtype:'Link',fieldname:'item',label:'对应物料',options:'Item',reqd:1}],primary_action_label:'保存并回填历史记录',primary_action:async values=>{await frappe.call({method:'fengjing_app.fengjing_business.page.ozon_financial_stora.ozon_financial_stora.bind_item',freeze:true,freeze_message:'正在建立物料映射…',args:{...data,item:values.item}});dialog.hide();frappe.show_alert({message:'物料绑定成功',indicator:'green'});this.load();}});dialog.show();}
	async rematch(){const x=await frappe.call({method:'fengjing_app.fengjing_business.page.ozon_financial_stora.ozon_financial_stora.refresh_item_bindings',freeze:true,freeze_message:'正在重新匹配历史财务记录…'});frappe.msgprint(`已检查 ${x.message.total} 条，更新 ${x.message.updated} 条。`);this.load();}
	money(v,c){return `${c||''} ${Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;}
	amountNumber(v){return Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});}
	plainAmount(v){const n=Number(v||0);return Number.isFinite(n)?n.toFixed(2):'0.00';}
	num(v){return Number(v||0).toLocaleString('zh-CN');}
	date(v){return v?String(v).replace('T',' ').replace(/\.\d+$/,'').slice(0,19):'—';}
	flag(c){return ({RUB:'🇷🇺',CNY:'🇨🇳',USD:'🇺🇸',EUR:'🇪🇺',BYN:'🇧🇾',KZT:'🇰🇿'})[c]||'💱';}
	esc(v){return frappe.utils.escape_html(String(v??''));}
}

frappe.pages["ozon_financial_stora"].on_page_hide = function (wrapper) {
	wrapper.__ozon_finance?.toggleTableFullscreen(false);
	wrapper.__ozon_finance?.imagePreview?.remove();
	if (wrapper.__ozon_finance) wrapper.__ozon_finance.imagePreview = null;
	if (wrapper.__ozon_finance?.fullscreenKeyHandler) document.removeEventListener('keydown', wrapper.__ozon_finance.fullscreenKeyHandler);
	$('body').removeClass('ozf-table-fullscreen-open');
	(wrapper.__ozon_finance?.charts||[]).forEach(chart=>chart.dispose());
};
