frappe.pages["ozon_financial_stora"].on_page_load = function (wrapper) {
	const page = frappe.ui.make_app_page({ parent: wrapper, title: "Ozon 财务记录表", single_column: true });
	wrapper.__ozon_finance = new OzonFinanceDashboard(page, wrapper);
};

frappe.pages["ozon_financial_stora"].on_page_show = wrapper => {
	const dashboard = wrapper.__ozon_finance;
	if (dashboard?.fullscreenKeyHandler) document.addEventListener('keydown', dashboard.fullscreenKeyHandler);
	dashboard?.load();
};

class OzonFinanceDashboard {
	constructor(page, wrapper) {
		this.page = page; this.wrapper = wrapper; this.pageNo = 1; this.pageSize = 50; this.charts = []; this.loaded = false; this.bookedChanges = new Map(); this.activeAccrualType = '';
		this.render(); this.bind(); this.setRange(30);
	}
	render() {
		$(this.page.main).html(`<style>.ozf-expand{float:left;display:grid;place-items:center;width:23px;height:23px;margin:0 7px 0 0;border:1px solid #cbdaf0;border-radius:7px;background:#edf4ff;color:#2868cb;font-size:20px;line-height:1;transition:.18s}.ozf-expand.open{transform:rotate(90deg);background:#2868cb;color:#fff}.ozf-has-children{background:#fbfdff}.ozf-child-row{background:#f4f8fe}.ozf-child-row td{border-bottom-color:#dfe9f6!important}.ozf-child-line{display:block;height:1px;margin-left:28px;background:linear-gradient(90deg,#7ba6e8,transparent)}.ozf-operation-id{padding:4px 8px!important;border:1px solid #cfe0f6!important;border-radius:7px!important;background:#f1f6fd!important;color:#2264bd!important;font-weight:700}</style><div class="ozf-root">
		<section class="ozf-hero"><div><span>OZON FINANCE INTELLIGENCE</span><h1>Ozon 财务交易中心</h1><p>销售、退款、佣金、配送、推广、服务费与罚款，穿透至店铺、SKU和ERPNext物料。</p></div><div><button id="ozf-rematch">重新匹配物料</button><button id="ozf-refresh">刷新数据</button></div></section>
		<section class="ozf-filter"><div class="ozf-range">${[7,30,90,180,365].map(d=>`<button data-days="${d}" class="${d===30?'active':''}">${d===365?'1年':d+'天'}</button>`).join('')}</div><div class="ozf-filter-grid">
		${this.input('date_from','开始日期','date')}${this.input('date_to','结束日期','date')}${this.select('store','店铺')}${this.select('category','财务大类')}${this.select('direction','收支方向')}${this.select('currency','币种')}${this.select('status','状态')}${this.select('sync_type','同步类型')}${this.select('binding','物料绑定',[['','全部'],['bound','已绑定'],['unbound','未绑定'],['store','店铺级费用']])}<label class="wide">搜索<input data-filter="search" placeholder="交易ID / 订单 / SKU / 物料 / 结算号"></label></div></section>
		<div class="ozf-loading"><i></i><span>正在整理 Ozon 财务数据…</span></div><div class="ozf-content">
		<section id="ozf-kpis" class="ozf-kpis"></section><section><div class="ozf-title"><h2>多币种资金全景</h2><span>各币种独立统计，不直接混合相加</span></div><div id="ozf-currencies" class="ozf-currencies"></div></section>
		<section class="ozf-grid"><article class="ozf-card span-8"><header><div><h3>资金趋势</h3><span>每日流入、流出与净额</span></div></header><div id="ozf-trend" class="ozf-chart tall"></div></article><article class="ozf-card span-4"><header><div><h3>财务大类</h3><span>当前币种构成</span></div></header><div id="ozf-category" class="ozf-chart tall"></div></article>
		<article class="ozf-card span-4"><header><div><h3>费用拆分</h3><span>佣金、配送、推广与服务费</span></div></header><div id="ozf-fees" class="ozf-chart"></div></article><article class="ozf-card span-4"><header><div><h3>店铺贡献</h3><span>净额与交易数</span></div></header><div id="ozf-stores" class="ozf-chart"></div></article><article class="ozf-card span-4"><header><div><h3>结算批次</h3><span>报告归集与最新发生时间</span></div></header><div id="ozf-statements" class="ozf-list"></div></article>
		<article class="ozf-card span-12"><header><div><h3>SKU 财务表现</h3><span>数量、净额与ERPNext物料绑定</span></div></header><div id="ozf-products" class="ozf-products"></div></article></section>
		<section class="ozf-card ozf-table-card"><header><div><h3>完整财务交易明细</h3><span id="ozf-count">—</span></div><div class="ozf-table-actions"><button id="ozf-save-booked" disabled>保存记账状态</button><div id="ozf-pages"></div><button id="ozf-table-fullscreen" class="ozf-icon-button" title="全屏查看" aria-label="全屏查看">${this.fullscreenIcon(false)}</button></div></header><div id="ozf-type-filter" class="ozf-type-filter"></div><div class="ozf-table-wrap"><table><thead><tr><th class="ozf-booked-head">已记账</th><th>应计费用ID</th><th>订单 / 商品</th><th>对应物料</th><th>财务分类</th><th>应计项目类型</th><th>净额</th><th>销售应计</th><th>店铺</th><th>发生时间</th><th>同步</th></tr></thead><tbody></tbody></table></div></section></div></div>`);
	}
	input(id,label,type){return `<label>${label}<input type="${type}" data-filter="${id}"></label>`;}
	select(id,label,options=[['','全部']]){return `<label>${label}<select data-filter="${id}">${options.map(x=>`<option value="${x[0]}">${x[1]}</option>`).join('')}</select></label>`;}
	bind() { const r=$(this.page.main),imageSelector='.ozf-product img,.ozf-related-product img'; r.on('click','[data-days]',e=>{r.find('[data-days]').removeClass('active');$(e.currentTarget).addClass('active');this.setRange(+e.currentTarget.dataset.days);this.pageNo=1;this.load();});r.on('click','#ozf-refresh',()=>{this.pageNo=1;this.load();});r.on('change','.ozf-filter [data-filter]',()=>{this.pageNo=1;this.load();});let timer;r.on('input','[data-filter=search]',()=>{clearTimeout(timer);timer=setTimeout(()=>{this.pageNo=1;this.load();},450);});r.on('click','#ozf-pages button',e=>{this.pageNo=+e.currentTarget.dataset.page;this.load();});r.on('click','[data-copy]',e=>{navigator.clipboard.writeText(e.currentTarget.dataset.copy||'');frappe.show_alert({message:'已复制',indicator:'green'});});r.on('click','.ozf-bind',e=>this.bindItem({...e.currentTarget.dataset}));r.on('click','#ozf-rematch',()=>this.rematch());r.on('change','.ozf-booked-input',e=>{this.bookedChanges.set(e.currentTarget.dataset.name,e.currentTarget.checked?1:0);r.find('#ozf-save-booked').prop('disabled',false).text(`保存记账状态 (${this.bookedChanges.size})`);});r.on('click','#ozf-save-booked',()=>this.saveBookedStatus());r.on('click','#ozf-table-fullscreen',()=>this.toggleTableFullscreen());r.on('click','.ozf-type-button',e=>{const value=e.currentTarget.dataset.type||'';if(value===this.activeAccrualType)return;this.activeAccrualType=value;this.pageNo=1;this.load();});r.on('mouseenter',imageSelector,e=>this.showImagePreview(e)).on('mousemove',imageSelector,e=>this.moveImagePreview(e)).on('mouseleave',imageSelector,()=>this.hideImagePreview());this.fullscreenKeyHandler=e=>{if(e.key==='Escape'&&this.tableFullscreen)this.toggleTableFullscreen(false);};document.addEventListener('keydown',this.fullscreenKeyHandler);}
	setRange(days){const to=frappe.datetime.get_today(),from=frappe.datetime.add_days(to,-days+1),r=$(this.page.main);r.find('[data-filter=date_from]').val(from);r.find('[data-filter=date_to]').val(to);}
	filters(){const f={};$(this.page.main).find('[data-filter]').each((_,x)=>f[x.dataset.filter]=$(x).val());f.accrual_type=this.activeAccrualType;return f;}
	async load(){if(this.loading)return;this.loading=true;const r=$(this.page.main).find('.ozf-root').addClass('loading');try{const response=await frappe.call({method:'fengjing_app.fengjing_business.page.ozon_financial_stora.ozon_financial_stora.get_dashboard_data',args:{filters:this.filters(),page:this.pageNo,page_size:this.pageSize}});this.data=response.message||{};this.fillOptions();this.draw();this.loaded=true;if(this.data.summary?.limited)frappe.show_alert({message:'当前日期范围超过5万条，请缩小日期范围。',indicator:'orange'},8);}catch(e){frappe.msgprint({title:'Ozon财务页面读取失败',message:e.message||'请查看错误日志',indicator:'red'});}finally{r.removeClass('loading');this.loading=false;}}
	fillOptions(){const map={store:'stores',category:'categories',direction:'directions',currency:'currencies',status:'statuses',sync_type:'sync_types'},r=$(this.page.main);Object.entries(map).forEach(([field,key])=>{const el=r.find(`[data-filter=${field}]`),old=el.val();el.html('<option value="">全部</option>'+((this.data.options?.[key]||[]).map(v=>`<option value="${this.esc(v)}">${this.esc(v)}</option>`).join('')));el.val(old);});}
	draw(){this.renderKpis();this.renderCurrencies();this.renderCharts();this.renderStatements();this.renderProducts();this.renderTable();}
	renderKpis(){const s=this.data.summary||{},cards=[['财务记录',s.records||0,'当前筛选范围'],['商品级交易',s.product_records||0,`${s.store_records||0} 条店铺级费用`],['物料绑定率',`${s.binding_rate||0}%`,`${s.bound||0} 已绑定 / ${s.unbound||0} 未绑定`],['退款记录',s.refunds||0,'根据Ozon返回标记'],['币种',Object.keys(s.currencies||{}).length,Object.keys(s.currencies||{}).join(' / ')||'暂无'],['同步异常',s.errors||0,s.errors?'请查看明细':'当前数据正常']];$(this.page.main).find('#ozf-kpis').html(cards.map((x,i)=>`<article class="c${i}"><span>${x[0]}</span><b>${this.esc(x[1])}</b><small>${this.esc(x[2])}</small></article>`).join(''));}
	renderCurrencies(){const data=this.data.summary?.currencies||{};$(this.page.main).find('#ozf-currencies').html(Object.entries(data).map(([c,v])=>`<article><header><i>${this.flag(c)}</i><div><b>${this.esc(c)}</b><span>当地币种</span></div></header><strong class="${v.net>=0?'positive':'negative'}">${this.money(v.net,c)}</strong><div><span>流入<b>${this.money(v.inflow,c)}</b></span><span>流出<b>${this.money(v.outflow,c)}</b></span><span>销售应计<b>${this.money(v.sales,c)}</b></span><span>费用绝对值<b>${this.money(v.fees,c)}</b></span></div></article>`).join('')||'<p class="empty">暂无金额数据</p>');}
	async renderCharts(){if(typeof echarts==='undefined'){await new Promise((ok,bad)=>frappe.require('/assets/fengjing_app/js/图表-echarts.js',ok,bad));}this.charts.forEach(c=>c.dispose());this.charts=[];const daily=this.data.daily||{},dates=Object.keys(daily),currencies=[...new Set(dates.flatMap(d=>Object.keys(daily[d])))];this.chart('ozf-trend',{tooltip:{trigger:'axis',appendToBody:true},legend:{top:5,type:'scroll'},grid:{left:75,right:25,top:50,bottom:48},xAxis:{type:'category',data:dates},yAxis:{type:'value'},dataZoom:[{type:'inside'},{type:'slider',height:16,bottom:7}],series:currencies.flatMap(c=>[{name:`${c} 流入`,type:'line',smooth:true,showSymbol:false,data:dates.map(d=>daily[d][c]?.inflow||0)},{name:`${c} 流出`,type:'line',smooth:true,showSymbol:false,data:dates.map(d=>daily[d][c]?.outflow||0)},{name:`${c} 净额`,type:'bar',data:dates.map(d=>daily[d][c]?.net||0)}])});const currency=$(this.page.main).find('[data-filter=currency]').val()||Object.keys(this.data.categories||{})[0],categories=this.data.categories?.[currency]||{};this.chart('ozf-category',{tooltip:{trigger:'item',appendToBody:true},legend:{bottom:4,type:'scroll'},series:[{type:'pie',radius:['38%','68%'],center:['50%','43%'],data:Object.entries(categories).map(([name,v])=>({name,value:Math.abs(v.amount),signed:v.amount}))}]});this.bar('ozf-fees',this.data.fees?.[currency]||{},v=>Math.abs(v),'#ff7657');this.bar('ozf-stores',this.data.stores?.[currency]||{},v=>v.amount,'#356fe5');}
	bar(id,obj,value,color){const rows=Object.entries(obj).sort((a,b)=>Math.abs(value(b[1]))-Math.abs(value(a[1]))).slice(0,20);this.chart(id,{tooltip:{trigger:'axis',appendToBody:true},grid:{left:150,right:25,top:15,bottom:25},xAxis:{type:'value'},yAxis:{type:'category',data:rows.map(x=>x[0]),axisLabel:{width:138,overflow:'truncate'}},series:[{type:'bar',barMaxWidth:20,data:rows.map(x=>value(x[1])),itemStyle:{color,borderRadius:[0,8,8,0]}}]});}
	chart(id,option){const el=$(this.page.main).find('#'+id)[0];if(!el)return;const chart=echarts.init(el);chart.setOption(option);this.charts.push(chart);}
	renderStatements(){const rows=this.data.statements||[];$(this.page.main).find('#ozf-statements').html(rows.map(x=>`<div><i>结</i><span><b>${this.esc(x.statement)}</b><small>${this.esc(x.store||'未归属')} · ${x.count}条 · ${this.date(x.latest)}</small></span><strong class="${x.amount>=0?'positive':'negative'}">${this.money(x.amount,x.currency)}</strong></div>`).join('')||'<p class="empty">暂无结算批次</p>');}
	renderProducts(){const rows=(this.data.products||[]).slice(0,100);$(this.page.main).find('#ozf-products').html(rows.map((x,i)=>`<article><em>${i+1}</em>${x.image?`<img src="${this.esc(x.image)}">`:'<i>O³</i>'}<div><b>${this.esc(x.item_name||x.product_name||x.offer_id||x.sku||'未命名商品')}</b><small><button data-copy="${this.esc(x.sku||'')}">SKU ${this.esc(x.sku||'—')}</button> · ${this.esc(x.store||'未归属')}</small><small>数量 ${this.num(x.quantity)} · ${x.transactions}条财务记录</small></div><aside>${Object.entries(x.amounts||{}).map(([c,v])=>`<strong class="${v>=0?'positive':'negative'}">${this.money(v,c)}</strong>`).join('')}${x.item?`<a href="/app/item/${encodeURIComponent(x.item)}">${this.esc(x.item)}</a>`:`<button class="ozf-bind" data-store="${this.esc(x.store||'')}" data-sku="${this.esc(x.sku||'')}" data-offer_id="${this.esc(x.offer_id||'')}">绑定物料</button>`}</aside></article>`).join('')||'<p class="empty">暂无SKU级财务记录</p>');}
	renderTable(){const p=this.data.pagination||{},r=$(this.page.main),types=this.data.type_filter||{},counts=types.counts||{};if(this.activeAccrualType&&!Object.prototype.hasOwnProperty.call(counts,this.activeAccrualType))this.activeAccrualType='';const buttons=[['',`全部`,types.total||0],...Object.entries(counts).map(([name,count])=>[name,name,count])];r.find('#ozf-type-filter').html(`<span>类型</span>${buttons.map(([value,label,count])=>`<button class="ozf-type-button ${value===this.activeAccrualType?'active':''}" data-type="${this.esc(value)}"><b>${this.esc(label)}</b><em>${this.num(count)}</em></button>`).join('')}<i class="${types.valid?'valid':'invalid'}">${types.valid?`分类合计已校验：${this.num(types.sum||0)}`:`数量校验异常：${this.num(types.sum||0)} / ${this.num(types.total||0)}`}</i>`);r.find('#ozf-count').text(`共 ${this.num(p.total)} 条 · 第 ${p.page}/${p.pages} 页`);r.find('#ozf-pages').html(`<button data-page="${p.page-1}" ${p.page<=1?'disabled':''}>上一页</button><button data-page="${p.page+1}" ${p.page>=p.pages?'disabled':''}>下一页</button>`);r.find('tbody').html((this.data.rows||[]).map(x=>this.financeRows(x)).join('')||'<tr><td colspan="11" class="empty">当前条件下暂无财务记录</td></tr>');}
	financeRows(x){
		const feeId=x.posting_number||'',children=x.breakdown||[],key=String(x.name||'').replace(/[^A-Za-z0-9_-]/g,''),booked=this.bookedChanges.has(x.name)?this.bookedChanges.get(x.name):Number(x.is_booked||0),currency=x.currency_code||'';
		const related=x.related_products||[];
		const itemCell=x.corresponding_item?`<button class="ozf-copy-value" data-copy="${this.esc(x.corresponding_item)}" title="点击复制物料ID">${this.esc(x.corresponding_item_name||x.corresponding_item)}</button>`:(x.sku?`<button class="ozf-bind" data-store="${this.esc(x.store||'')}" data-sku="${this.esc(x.sku||'')}" data-offer_id="${this.esc(x.offer_id||'')}" data-product_id="${this.esc(x.product_id||'')}">绑定物料</button>`:this.relatedItems(related));
		const productCell=x.sku?`<div class="ozf-product"><span>${x.corresponding_item_image?`<img src="${this.esc(x.corresponding_item_image)}" alt="">`:'O³'}</span><div><b>${this.esc(x.product_name||x.offer_id||x.sku)}</b><small>SKU ${this.esc(x.sku)} · ${this.esc(x.order_number||'无订单号')}</small></div></div>`:this.relatedProducts(related);
		const netCell=`<button class="ozf-copy-amount ${x.net_amount>=0?'positive':'negative'}" data-copy="${this.esc(x.net_amount??0)}" title="点击复制净额"><b>${this.amountNumber(x.net_amount)}</b><small>${this.esc(currency)}</small></button>`;
		const salesCell=Number(x.accruals_for_sale||0)!==0?`<b>${this.amountNumber(x.accruals_for_sale)}</b><small>${this.esc(currency)}</small>`:'';
		const parent=`<tr class="${children.length?'ozf-has-children':''}"><td class="ozf-booked-cell"><input class="ozf-booked-input" type="checkbox" data-name="${this.esc(x.name)}" ${booked?'checked':''} aria-label="已记账"></td><td>${feeId?`<button class="ozf-operation-id" data-copy="${this.esc(feeId)}">${this.esc(feeId)}</button>`:'<span class="muted">—</span>'}</td><td>${productCell}</td><td>${itemCell}</td><td><span class="ozf-tag">${this.esc(x.transaction_category||'未分类')}</span><small>${this.esc(x.description||'-')}</small></td><td><b>${this.esc(this.accrualType(x))}</b><small>${this.esc(this.accrualReason(x))}</small></td><td class="num">${netCell}</td><td class="num">${salesCell}</td><td><b>${this.esc(x.store||'—')}</b><small>${this.esc(x.ozon_id?`Ozon ID ${x.ozon_id}`:'')}</small></td><td><b>${this.date(x.operation_date)}</b><small>${this.esc(x.payment_date?'付款 '+this.date(x.payment_date):'')}</small></td><td><b>${this.esc(x.sync_type||'—')}</b><small>${this.esc(x.sync_status||'—')} · v${x.data_version||1}</small></td></tr>`;
		const detail=children.map(child=>{const childCurrency=child.currency||currency;return `<tr class="ozf-child-row" data-parent="${key}"><td></td><td></td><td><b>${this.esc(x.product_name||'商品明细')}</b><small>SKU ${this.esc(child.sku||x.sku||'—')} · ${this.num(child.quantity||0)} 件</small></td><td>${x.corresponding_item?`<button class="ozf-copy-value" data-copy="${this.esc(x.corresponding_item)}" title="点击复制物料ID">${this.esc(x.corresponding_item_name||x.corresponding_item)}</button>`:''}</td><td><span class="ozf-tag">${this.esc(child.label)}</span></td><td><b>${this.esc(child.label)}</b><small>${this.esc(child.detail)}</small></td><td class="num ${child.amount>=0?'positive':'negative'}"><b>${this.amountNumber(child.amount)}</b><small>${this.esc(childCurrency)}</small></td><td></td><td></td><td></td><td></td></tr>`;}).join('');
		return parent+detail;
	}
	relatedProducts(products){if(!products.length)return '<span class="muted">-</span>';return `<div class="ozf-related-list"><strong>关联商品 ${products.length}</strong>${products.map(p=>`<div class="ozf-related-product">${p.image?`<img src="${this.esc(p.image)}" alt="">`:'<i>O³</i>'}<span><b>${this.esc(p.product_name||p.offer_id||p.sku||'关联商品')}</b><small>SKU ${this.esc(p.sku||'-')}${p.quantity?` · ${this.num(p.quantity)} 件`:''}</small></span></div>`).join('')}</div>`;}
	relatedItems(products){if(!products.length)return '<span class="muted">-</span>';return `<div class="ozf-related-items"><strong>关联物料 ${products.length}</strong>${products.map(p=>p.item?`<button class="ozf-copy-value" data-copy="${this.esc(p.item)}" title="关联展示，点击复制物料ID">${this.esc(p.item_name||p.item)}</button>`:'<span class="muted">-</span>').join('')}</div>`;}
	async saveBookedStatus(){if(!this.bookedChanges.size)return;const button=$(this.page.main).find('#ozf-save-booked').prop('disabled',true).text('正在保存…');try{const changes=[...this.bookedChanges].map(([name,is_booked])=>({name,is_booked}));const response=await frappe.call({method:'fengjing_app.fengjing_business.page.ozon_financial_stora.ozon_financial_stora.save_booked_status',args:{changes:JSON.stringify(changes)}});this.bookedChanges.clear();button.text('保存记账状态');frappe.show_alert({message:`已保存 ${response.message?.updated||0} 条记账状态`,indicator:'green'});await this.load();}catch(e){button.prop('disabled',false).text(`保存记账状态 (${this.bookedChanges.size})`);frappe.msgprint({title:'保存失败',message:e.message||'请查看错误日志',indicator:'red'});}}
	fullscreenIcon(open){return open?'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 4v5H4M15 4v5h5M9 20v-5H4M15 20v-5h5"/></svg>':'<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M9 4H4v5M15 4h5v5M9 20H4v-5M15 20h5v-5"/></svg>';}
	toggleTableFullscreen(force){const card=$(this.page.main).find('.ozf-table-card'),root=$(this.page.main).find('.ozf-root')[0];const open=typeof force==='boolean'?force:!this.tableFullscreen;this.tableFullscreen=open;if(open){const rect=root?.getBoundingClientRect();card.css('--ozf-fullscreen-left',`${Math.max(0,rect?.left||0)}px`).addClass('ozf-table-fullscreen');$('body').addClass('ozf-table-fullscreen-open');card.find('#ozf-table-fullscreen').attr({'title':'退出全屏','aria-label':'退出全屏'}).html(this.fullscreenIcon(true));}else{card.removeClass('ozf-table-fullscreen').css('--ozf-fullscreen-left','');$('body').removeClass('ozf-table-fullscreen-open');card.find('#ozf-table-fullscreen').attr({'title':'全屏查看','aria-label':'全屏查看'}).html(this.fullscreenIcon(false));}setTimeout(()=>this.charts.forEach(chart=>chart.resize()),80);}
	showImagePreview(e){if(!this.imagePreview)this.imagePreview=$('<div class="ozf-image-preview"><img alt="商品图片预览"></div>').appendTo(document.body);this.imagePreview.find('img').attr('src',e.currentTarget.src);this.imagePreview.show();this.moveImagePreview(e);}
	moveImagePreview(e){if(!this.imagePreview)return;const size=250,gap=18,left=e.clientX+gap+size>window.innerWidth?Math.max(8,e.clientX-size-gap):e.clientX+gap,top=Math.max(8,Math.min(window.innerHeight-size-8,e.clientY-size/2));this.imagePreview.css({left,top});}
	hideImagePreview(){this.imagePreview?.hide();}
	accrualType(x){if(x.accrual_type_label)return x.accrual_type_label;const key=String(x.operation_type_name||x.operation_type||''),description=String(x.description||'');const byName={POSTING:'商品销售与佣金',Acquiring:'收单服务费',PayPerClick:'按点击付费',RfbsGlobalDelivery:'国际配送服务',RfbsGlobalAgentFee:'Ozon代理佣金',RfbsGlobalIntermediaryService:'国际运输组织合同服务',RfbsGlobalPlatformConnectionService:'Ozon物流平台接入服务',Promotion:'推广服务',DefectFineErrors:'商品缺陷罚款'};const byDescription={'Эквайринг':'收单服务费','Оплата за клик':'按点击付费','Услуги международной доставки':'国际配送服务','Агентское вознаграждение Ozon':'Ozon代理佣金','Услуги по заключению договора на организацию международной перевозки':'国际运输组织合同服务','Электронная услуга подключения к логистической Платформе Ozon':'Ozon物流平台接入服务'};return byName[key]||byDescription[description]||description||key||'未分类应计项目';}
	accrualReason(x){const reason=String(x.description||'').trim();const translations={'Превышение индекса ошибок':'错误指数超标'};return translations[reason]||reason||'-';}
	bindItem(data){const dialog=new frappe.ui.Dialog({title:'绑定 Ozon SKU 到 ERPNext 物料',fields:[{fieldtype:'HTML',options:`<div class="ozf-dialog">SKU：${this.esc(data.sku||'—')}<br>店铺：${this.esc(data.store||'—')}</div>`},{fieldtype:'Link',fieldname:'item',label:'对应物料',options:'Item',reqd:1}],primary_action_label:'保存并回填历史记录',primary_action:async values=>{await frappe.call({method:'fengjing_app.fengjing_business.page.ozon_financial_stora.ozon_financial_stora.bind_item',freeze:true,freeze_message:'正在建立物料映射…',args:{...data,item:values.item}});dialog.hide();frappe.show_alert({message:'物料绑定成功',indicator:'green'});this.load();}});dialog.show();}
	async rematch(){const x=await frappe.call({method:'fengjing_app.fengjing_business.page.ozon_financial_stora.ozon_financial_stora.refresh_item_bindings',freeze:true,freeze_message:'正在重新匹配历史财务记录…'});frappe.msgprint(`已检查 ${x.message.total} 条，更新 ${x.message.updated} 条。`);this.load();}
	money(v,c){return `${c||''} ${Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2})}`;}
	amountNumber(v){return Number(v||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});}
	num(v){return Number(v||0).toLocaleString('zh-CN');}
	date(v){return v?String(v).replace('T',' ').replace(/\.\d+$/,'').slice(0,19):'—';}
	flag(c){return ({RUB:'🇷🇺',CNY:'🇨🇳',USD:'🇺🇸',EUR:'🇪🇺',BYN:'🇧🇾',KZT:'🇰🇿'})[c]||'💱';}
	esc(v){return frappe.utils.escape_html(String(v??''));}
}

frappe.pages["ozon_financial_stora"].on_page_hide = function (wrapper) {
	wrapper.__ozon_finance?.toggleTableFullscreen(false);
	wrapper.__ozon_finance?.imagePreview?.remove();
	if (wrapper.__ozon_finance) wrapper.__ozon_finance.imagePreview = null;
	if (wrapper.__ozon_finance?.fullscreenKeyHandler) document.removeEventListener('keydown', wrapper.__ozon_finance.fullscreenKeyHandler);
	$('body').removeClass('ozf-table-fullscreen-open');
	(wrapper.__ozon_finance?.charts||[]).forEach(chart=>chart.dispose());
};
