frappe.pages["amazon-rank-trend"].on_page_load = function (wrapper) {
	const page = frappe.ui.make_app_page({ parent: wrapper, title: "Amazon 商品排名走势", single_column: true });
	frappe.require("assets/fengjing_app/js/主体-echarts.js", () => new AmazonRankDashboard(page, wrapper));
};

class AmazonRankDashboard {
	constructor(page, wrapper) {
		this.page = page; this.wrapper = wrapper; this.rows = []; this.filtered = []; this.sampling = null; this.pageNo = 1; this.pageSize = 20;
		this.itemOptionMap = {};
		this.hideDeleted = true; this.tableSortKey = "main_rank"; this.tableSortDirection = "asc"; this.trendLegendPage = 1; this.trendLegendPageSize = 18; this.trendSeries = []; this.charts = []; wrapper.__amazon_rank_dashboard = this; this.render(); this.bind(); this.setDates(30); this.load();
	}
	render() {
		$(this.wrapper).find(".layout-main-section").html(`
		<div class="art-dashboard">
		 <section class="art-hero"><div><span class="art-eyebrow">AMAZON INTELLIGENCE</span><h2>商品排名趋势中心</h2><p>从 ASIN、SKU 到对应物料，一处掌握排名变化与商品表现。</p></div><div class="art-hero-stat"><b id="hero-products">0</b><span>监控商品</span></div></section>
		 <section class="art-filters">
		  <div class="art-filter-grid">
		   ${this.select("store","店铺")}${this.select("marketplace","站点")}${this.searchSelect("asin","ASIN")}${this.searchSelect("sku","SKU")}${this.searchSelect("item","对应物料")}
		   <label>开始日期<input id="art-from" type="date"></label><label>结束日期<input id="art-to" type="date"></label>
		  </div>
		  <div class="art-actions"><div class="art-ranges"><button data-days="7">7天</button><button data-days="30" class="active">30天</button><button data-days="90">90天</button><button data-days="365">1年</button></div><button id="art-hide-deleted" class="active">显示已删除产品</button><button id="art-reset">重置</button><button id="art-search" class="primary">查询数据</button><button id="art-export">导出 CSV</button></div>
		 </section>
		 <section class="art-kpis" id="art-kpis"></section>
		 <section class="art-chart-grid"><article class="art-card wide"><header><h3>排名走势</h3><span id="art-sampling">数值越小，排名越好</span></header><div id="art-trend" class="art-chart"></div><div id="art-trend-legend" class="art-trend-legend"></div></article><article class="art-card"><header><h3>最新排名变化</h3><span>与上次记录相比 · 向下滚动查看更多</span></header><div class="art-chart-scroll"><div id="art-change" class="art-chart"></div></div></article><article class="art-card wide"><header><h3>商品排名概览</h3><span>最新排名与历史最佳 · 向下滚动查看更多</span></header><div class="art-chart-scroll"><div id="art-overview" class="art-chart"></div></div></article><article class="art-card"><header><h3>主类目分布</h3><span>按最新商品记录</span></header><div id="art-category" class="art-chart"></div></article></section>
		 <section class="art-card art-table-card"><header><div><h3>商品明细</h3><span id="art-count"></span></div><div class="art-table-tools"><input id="art-table-search" placeholder="搜索标题、ASIN、SKU、物料…"></div></header><div class="art-table-wrap"><table><thead><tr><th>Amazon / ERPNext 图片</th><th>商品</th><th>ASIN / SKU</th><th><button class="art-sort" data-sort="item">对应物料 <i></i></button></th><th><button class="art-sort" data-sort="main_rank">主类目排名 <i>↑</i></button></th><th><button class="art-sort" data-sort="detail_rank">细分类目排名 <i></i></button></th><th>变化</th><th>站点 / 店铺</th><th>抓取时间</th></tr></thead><tbody id="art-tbody"></tbody></table></div><footer><span id="art-page-info"></span><div><button id="art-prev">上一页</button><button id="art-next">下一页</button></div></footer></section>
		 <div id="art-hover-preview" class="art-hover-preview"></div><div class="art-loading"><div class="art-spinner"></div><span>正在整理排名数据…</span></div>
		</div>`);
	}
	select(id, title) { return `<label>${title}<select id="art-${id}"><option value="">全部</option></select></label>`; }
	searchSelect(id, title) { return `<label class="art-search-picker">${title}<input id="art-${id}" class="art-filter-search art-image-filter" data-kind="${id}" placeholder="全部（可搜索或下拉选择）" autocomplete="off"><div id="art-${id}-menu" class="art-image-menu"></div></label>`; }
	bind() {
		const root=$(this.wrapper); root.on("click","[data-days]",e=>{root.find("[data-days]").removeClass("active");$(e.currentTarget).addClass("active");this.setDates(+e.currentTarget.dataset.days);this.load();});
		root.on("click","#art-search",()=>this.load()); root.on("click","#art-reset",()=>{root.find("select").val("");root.find(".art-filter-search").val("");this.setDates(30);this.load();});
		root.on("focus input",".art-image-filter",e=>this.showImageOptions(e.currentTarget.dataset.kind,e.currentTarget.value));
		root.on("mousedown",".art-image-option",e=>{e.preventDefault();const option=e.currentTarget;root.find(`#art-${option.dataset.kind}`).val(option.dataset.label||option.dataset.value);root.find(".art-image-menu").removeClass("show");});
		root.on("click",e=>{if(!$(e.target).closest(".art-search-picker").length)root.find(".art-image-menu").removeClass("show");});
		root.on("input","#art-table-search",()=>{this.pageNo=1;this.renderTable();}); root.on("click","#art-prev",()=>{if(this.pageNo>1){this.pageNo--;this.renderTable();}}); root.on("click","#art-next",()=>{if(this.pageNo*this.pageSize<this.filtered.length){this.pageNo++;this.renderTable();}});
		root.on("click","#art-hide-deleted",e=>{this.hideDeleted=!this.hideDeleted;$(e.currentTarget).toggleClass("active",this.hideDeleted).text(this.hideDeleted?"显示已删除产品":"隐藏已删除产品");this.pageNo=1;this.draw();});
		root.on("click",".art-sort",e=>{const key=e.currentTarget.dataset.sort;if(this.tableSortKey===key)this.tableSortDirection=this.tableSortDirection==="asc"?"desc":"asc";else{this.tableSortKey=key;this.tableSortDirection="asc";}root.find(".art-sort i").text("");$(e.currentTarget).find("i").text(this.tableSortDirection==="asc"?"↑":"↓");this.pageNo=1;this.renderTable();});
		root.on("click",".art-legend-item",e=>this.toggleOnlyLegend(+e.currentTarget.dataset.index));
		root.on("click","#art-legend-show-all",()=>this.setAllLegends(true));root.on("click","#art-legend-hide-all",()=>this.setAllLegends(false));
		root.on("mouseenter mousemove",".art-legend-item",e=>this.showLegendPreview(e));root.on("mouseleave",".art-legend-item",()=>root.find("#art-hover-preview").removeClass("show"));
		root.on("click","#art-legend-prev",()=>{if(this.trendLegendPage>1){this.trendLegendPage--;this.renderTrendLegend();}});root.on("click","#art-legend-next",()=>{if(this.trendLegendPage*this.trendLegendPageSize<this.trendSeries.length){this.trendLegendPage++;this.renderTrendLegend();}});
		root.on("click","#art-export",()=>this.exportCSV()); this.resize=()=>this.charts.forEach(c=>c.resize()); window.addEventListener("resize",this.resize);
	}
	setDates(days){const to=frappe.datetime.get_today(),from=frappe.datetime.add_days(to,-days);$(this.wrapper).find("#art-from").val(from).end().find("#art-to").val(to);}
	async load(){
		const root=$(this.wrapper), filters={}; ["store","marketplace","asin","sku","item"].forEach(k=>filters[k]=root.find(`#art-${k}`).val());filters.item=this.itemOptionMap[filters.item]||filters.item; filters.date_from=root.find("#art-from").val();filters.date_to=root.find("#art-to").val();root.find(".art-loading").addClass("show");
		try {const r=await frappe.call({method:"fengjing_app.fengjing_business.page.amazon_rank_trend.amazon_rank_trend.get_rank_dashboard_data",args:{filters}}),message=r.message||{};this.rows=message.rows||[];this.sampling=message.sampling||null;this.fillOptions(message.options||{});root.find("#art-sampling").text(this.sampling?`数值越小，排名越好 · ${this.sampling.label}展示 · ${this.sampling.returned_points} 个数据点`:"数值越小，排名越好");this.draw();}
		catch(e){frappe.msgprint({title:"读取失败",message:"无法读取 Amazon 排名数据，请查看错误日志。",indicator:"red"});}
		finally{root.find(".art-loading").removeClass("show");}
	}
	fillOptions(o){
		const root=$(this.wrapper);
		const selectMap={store:o.stores,marketplace:o.marketplaces};
		Object.entries(selectMap).forEach(([k,vals])=>{
			const el=root.find(`#art-${k}`),old=el.val();
			el.html('<option value="">全部</option>'+((vals||[]).map(option=>{
				const value=typeof option==="object"?option.value:option;
				const label=typeof option==="object"?option.label:option;
				return `<option value="${this.esc(value)}">${this.esc(label)}</option>`;
			}).join("")));
			el.val(old);
		});
		this.itemOptionMap={};(o.items||[]).forEach(option=>{if(typeof option==="object")this.itemOptionMap[String(option.label||option.value)]=option.value;});
	}
	productOptions(kind){const field=kind==="asin"?"商品列表api_asin":kind==="sku"?"商品列表api_sku":"绑定的物料",seen=new Set(),options=[];[...this.rows].reverse().forEach(row=>{const value=String(row[field]||"").trim();if(!value||seen.has(value))return;seen.add(value);options.push({value,label:kind==="item"?String(row.物料名称||value):value,row});});return options;}
	showImageOptions(kind,query=""){const root=$(this.wrapper),menu=root.find(`#art-${kind}-menu`),needle=String(query||"").trim().toLowerCase();root.find(".art-image-menu").not(menu).removeClass("show");const options=this.productOptions(kind).filter(option=>!needle||option.value.toLowerCase().includes(needle)||option.label.toLowerCase().includes(needle)||String(option.row.物料名称||"").toLowerCase().includes(needle)).slice(0,30);menu.html(options.map(option=>{const row=option.row,name=this.materialShortName(row),image=(src,label)=>src?`<span><img src="${this.esc(src)}" alt="${label}"><small>${label}</small></span>`:`<span><i>${label==="Amazon"?"A":"ERP"}</i><small>${label}</small></span>`;return `<button type="button" class="art-image-option" data-kind="${kind}" data-value="${this.esc(option.value)}" data-label="${this.esc(option.label)}"><span class="art-option-images">${image(row.商品列表api_主图链接||"","Amazon")}${image(row.物料图片||"","ERPNext")}</span><span class="art-option-text"><b>${this.esc(option.label)}</b><small>${kind==="item"?this.esc(option.value):this.esc(name)}</small></span></button>`;}).join("")||'<div class="art-image-empty">没有匹配商品</div>').addClass("show");}
	previewImages(row){const image=(src,label)=>`<span>${src?`<img src="${this.esc(src)}" alt="${label}">`:`<i>${label==="Amazon"?"A":"ERP"}</i>`}<small>${label}</small></span>`;return `${image(row.商品列表api_主图链接||"","Amazon")}${image(row.物料图片||"","ERPNext")}`;}
	showLegendPreview(event){const series=this.trendSeries[+event.currentTarget.dataset.index],row=series&&series._row;if(!row)return;const preview=$(this.wrapper).find("#art-hover-preview"),left=Math.min(event.clientX+14,window.innerWidth-300),top=Math.min(event.clientY+14,window.innerHeight-190);preview.html(`<div class="art-hover-images">${this.previewImages(row)}</div><b>${this.esc(this.materialShortName(row))}</b><small>${this.esc(row.商品列表api_asin||"")} · ${this.esc(row.商品列表api_sku||"无SKU")}</small>`).css({left:`${Math.max(8,left)}px`,top:`${Math.max(8,top)}px`}).addClass("show");}
	visibleRows(){return this.hideDeleted?this.rows.filter(r=>!r.亚马逊商品已删除):this.rows;}
	group(rows=this.rows){const g={};rows.forEach(r=>{const product=r.商品列表api_asin||r.商品列表api_sku||r.name,store=r.属于哪个店铺||r.店铺||"未匹配店铺",key=`${store}::${r.商品列表api_站点id||"未知站点"}::${product}`;(g[key]||(g[key]=[])).push(r);});return g;}
	draw(){const groups=this.group(this.visibleRows()),latest=Object.values(groups).map(a=>a[a.length-1]);this.charts=[];$(this.wrapper).find("#hero-products").text(latest.length);this.renderKpis(groups,latest);this.renderCharts(groups,latest);this.pageNo=1;this.renderTable();}
	renderKpis(groups,latest){let best=[],avg=[],up=0,down=0,bound=0,totalRecords=0;Object.values(groups).forEach(a=>{const row=a[a.length-1],historicalBest=+row._group_best_rank||0,current=+row._latest_rank||+row.排名api_主类目排名||0,d=this.latestChange(row);if(historicalBest)best.push(historicalBest);if(current)avg.push(current);totalRecords+=+row._group_record_count||0;if(d>0)up++;if(d<0)down++;});latest.forEach(r=>{if(r.绑定的物料)bound++;});const latestTime=latest.length?latest.map(r=>r.抓取数据的时间||"").sort().at(-1)||"—":"—";const cards=[["监控商品",latest.length,"全部 ASIN / SKU"],["排名记录",totalRecords,"原始日志总数"],["历史最佳",best.length?Math.min(...best):"—","完整范围主类目排名"],["平均排名",avg.length?Math.round(avg.reduce((a,b)=>a+b,0)/avg.length):"—","最新主类目"],["排名上升",up,"最近两次原始记录"],["排名下降",down,"最近两次原始记录"],["物料绑定率",latest.length?Math.round(bound/latest.length*100)+"%":"0%",`${bound}/${latest.length} 已绑定`],["最新抓取",latestTime,"数据更新时间"]];$(this.wrapper).find("#art-kpis").html(cards.map((c,i)=>`<article class="art-kpi k${i}"><span>${c[0]}</span><b>${this.esc(c[1])}</b><small>${this.esc(c[2])}</small></article>`).join(""));}
	chart(id,option){const el=$(this.wrapper).find(id)[0];if(!el)return;const old=echarts.getInstanceByDom(el);if(old)old.dispose();const c=echarts.init(el);c.setOption(option);this.charts.push(c);return c;}
	materialShortName(row){const name=String(row.物料名称||"").trim();if(!name)return"未绑定";const match=name.match(/【([^】]+)】/);return match?match[1].trim():name;}
	latestChange(row){const current=+row._latest_rank||+row.排名api_主类目排名||0,previous=+row._previous_rank||0;return current&&previous?previous-current:0;}
	siteLabel(row){const countries={ATVPDKIKX0DER:"美国",A2EUQ1WTGCTBG2:"加拿大",A1AM78C64UM0Y8:"墨西哥",A2Q3Y263D00KWC:"巴西",A28R8C7NBKEWEA:"爱尔兰",A1RKKUPIHCS9HS:"西班牙",A1F83G8C2ARO7P:"英国",A13V1IB3VIYZZH:"法国",AMEN7PMS3EDWL:"比利时",A1805IZSGTT6HS:"荷兰",A1PA6795UKMFR9:"德国",APJ6JRA9NG5V4:"意大利",A2NODRKZP88ZB9:"瑞典",AE08WJ6YKNBMC:"南非",A1C3SOZRARQ6R3:"波兰",ARBP9OOSHTCHU:"埃及",A33AVAJ2PDY3EV:"土耳其",A17E79C6D8DWNP:"沙特阿拉伯",A2VIGQ35RCS4UG:"阿联酋",A21TJRUUN4KGV:"印度",A19VAU5U5O7RUS:"新加坡",A39IBJ37TRP1C6:"澳大利亚",A1VC38T7YXB528:"日本"};return `${countries[row.商品列表api_站点id]||row.商品列表api_站点id||"未知站点"} · ${row.店铺||"未匹配店铺"}`;}
	productLabel(row,multiline=false){const asin=row.商品列表api_asin||row.商品列表api_sku||row.name,joiner=multiline?"\n":" | ";return `${this.siteLabel(row)}${joiner}${asin} · ${this.materialShortName(row)}`;}
	compactProductLabel(row,maxLength=10){const asin=row.商品列表api_asin||row.商品列表api_sku||row.name,name=this.materialShortName(row),store=String(row.店铺||"");return `${this.siteLabel({...row,店铺:store.length>8?store.slice(0,8)+"…":store})}\n${asin} · ${name.length>maxLength?name.slice(0,maxLength)+"…":name}`;}
	materialAxisLabel(row,maxLength=10){return this.compactProductLabel(row,maxLength);}
	copyProduct(row){const asin=row.商品列表api_asin||row.商品列表api_sku||"",text=`${asin} & ${this.materialShortName(row)}`;if(frappe.utils&&frappe.utils.copy_to_clipboard)frappe.utils.copy_to_clipboard(text);else navigator.clipboard.writeText(text);frappe.show_alert({message:`已复制：${text}`,indicator:"green"});}
	renderTrendLegend(){const root=$(this.wrapper).find("#art-trend-legend"),start=(this.trendLegendPage-1)*this.trendLegendPageSize,items=this.trendSeries.slice(start,start+this.trendLegendPageSize),pages=Math.max(1,Math.ceil(this.trendSeries.length/this.trendLegendPageSize));root.html(`<div class="art-legend-tools"><button id="art-legend-show-all">全部显示</button><button id="art-legend-hide-all">全部隐藏</button></div><div class="art-legend-items">${items.map((s,i)=>`<button class="art-legend-item${s._visible===false?' muted':''}" data-index="${start+i}" title="${this.esc(s.name)}"><i style="background:${s.itemStyle.color}"></i>${this.esc(s.name)}</button>`).join("")}</div>${pages>1?`<div class="art-legend-pages"><button id="art-legend-prev" ${this.trendLegendPage===1?"disabled":""}>上一页</button><span>${this.trendLegendPage} / ${pages}</span><button id="art-legend-next" ${this.trendLegendPage===pages?"disabled":""}>下一页</button></div>`:""}`);}
	trendChart(){const element=$(this.wrapper).find("#art-trend")[0];return element&&echarts.getInstanceByDom(element);}
	applyLegendVisibility(){const chart=this.trendChart();if(!chart)return;this.trendSeries.forEach(series=>chart.dispatchAction({type:series._visible===false?"legendUnSelect":"legendSelect",name:series.name}));this.renderTrendLegend();}
	setAllLegends(visible){this.trendSeries.forEach(series=>series._visible=visible);this.applyLegendVisibility();}
	toggleOnlyLegend(index){const selected=this.trendSeries[index];if(!selected)return;const onlyThisVisible=selected._visible!==false&&this.trendSeries.every((series,i)=>i===index||series._visible===false);if(onlyThisVisible)this.trendSeries.forEach(series=>series._visible=true);else this.trendSeries.forEach((series,i)=>series._visible=i===index);this.applyLegendVisibility();}
	renderCharts(groups,latest){
		const palette=["#2563eb","#06b6d4","#8b5cf6","#f59e0b","#10b981","#ec4899"],series=[];
		Object.values(groups).forEach((a,i)=>{const row=a[a.length-1];series.push({name:this.productLabel(row),_row:row,_visible:true,type:"line",smooth:true,showSymbol:a.length<20,data:a.filter(r=>r.排名api_主类目排名).map(r=>[r.抓取数据的时间,+r.排名api_主类目排名]),lineStyle:{width:2},itemStyle:{color:palette[i%palette.length]}});});
		this.trendSeries=series;this.trendLegendPage=Math.min(this.trendLegendPage,Math.max(1,Math.ceil(series.length/this.trendLegendPageSize)));this.chart("#art-trend",{tooltip:{trigger:"axis"},legend:{show:false,data:series.map(s=>s.name)},grid:{left:52,right:58,top:25,bottom:45},xAxis:{type:"time"},yAxis:{type:"value",inverse:true,min:1},dataZoom:[{type:"inside",xAxisIndex:0},{type:"inside",yAxisIndex:0},{type:"slider",xAxisIndex:0,height:16,bottom:12},{type:"slider",yAxisIndex:0,orient:"vertical",right:8,width:16}],series});this.renderTrendLegend();
		const changes=Object.values(groups).map(a=>{const row=a[a.length-1];return{axisLabel:this.materialAxisLabel(row,9),row,d:this.latestChange(row)};}).sort((a,b)=>Math.abs(b.d)-Math.abs(a.d));
		$(this.wrapper).find("#art-change").height(Math.max(360,changes.length*38));
		const changeChart=this.chart("#art-change",{tooltip:{trigger:"item",formatter:p=>{const row=changes[p.dataIndex].row,amazonImage=row.商品列表api_主图链接||"",erpImage=row.物料图片||"",image=(src,label)=>`<span class="art-tooltip-image">${src?`<img src="${this.esc(src)}" alt="${label}">`:`<i>${label==="Amazon"?"A":"ERP"}</i>`}<small>${label}</small></span>`;return `<div class="art-overview-tooltip"><div class="art-tooltip-images">${image(amazonImage,"Amazon")}${image(erpImage,"ERPNext")}</div><b>${this.esc(this.productLabel(row))}</b><div>排名变化：${p.value}</div><small>点击复制 ASIN & 物料名称</small></div>`;}},grid:{left:170,right:18,top:10,bottom:20},xAxis:{type:"value"},yAxis:{type:"category",data:changes.map(x=>x.axisLabel),axisLabel:{width:160,overflow:"truncate",fontSize:10,lineHeight:14}},series:[{type:"bar",data:changes.map(x=>({value:x.d,itemStyle:{color:x.d>=0?"#10b981":"#ef4444"}})),barMaxWidth:16}]});if(changeChart)changeChart.on("click",p=>this.copyProduct(changes[p.dataIndex].row));
		const overview=Object.values(groups).map(a=>{const row=a[a.length-1];return{axisLabel:this.materialAxisLabel(row,12),row,now:+row._latest_rank||+row.排名api_主类目排名||0,best:+row._group_best_rank||0};}).sort((a,b)=>a.now-b.now);
		$(this.wrapper).find("#art-overview").height(Math.max(360,overview.length*38+55));
		const overviewChart=this.chart("#art-overview",{tooltip:{trigger:"axis",formatter:params=>{const item=overview[params[0].dataIndex],row=item.row,amazonImage=row.商品列表api_主图链接||"",erpImage=row.物料图片||"",image=(src,label)=>`<span class="art-tooltip-image">${src?`<img src="${this.esc(src)}" alt="${label}">`:`<i>${label==="Amazon"?"A":"ERP"}</i>`}<small>${label}</small></span>`;return `<div class="art-overview-tooltip"><div class="art-tooltip-images">${image(amazonImage,"Amazon")}${image(erpImage,"ERPNext")}</div><b>${this.esc(this.productLabel(row))}</b><div>${params.map(p=>`${p.marker}${p.seriesName}：${p.value}`).join("<br>")}</div><small>点击复制 ASIN & 物料名称</small></div>`;}},legend:{bottom:2},grid:{left:205,right:20,top:15,bottom:65},xAxis:{type:"value",inverse:true,min:1},yAxis:{type:"category",inverse:true,data:overview.map(x=>x.axisLabel),axisLabel:{width:195,overflow:"truncate",fontSize:10,lineHeight:14}},series:[{name:"最新",type:"bar",data:overview.map(x=>x.now),itemStyle:{color:"#2563eb"},barMaxWidth:14},{name:"最佳",type:"bar",data:overview.map(x=>x.best),itemStyle:{color:"#93c5fd"},barMaxWidth:14}]});if(overviewChart)overviewChart.on("click",p=>this.copyProduct(overview[p.dataIndex].row));
		const cat={};latest.forEach(r=>{const k=r.排名api_主类目名称||"未分类";cat[k]=(cat[k]||0)+1;});this.chart("#art-category",{tooltip:{trigger:"item"},legend:{type:"scroll",bottom:2,itemGap:12},series:[{type:"pie",radius:["36%","60%"],center:["50%","38%"],label:{formatter:"{b}\n{d}%"},data:Object.entries(cat).map(([name,value])=>({name,value}))}]});}
	renderTable(){const q=$(this.wrapper).find("#art-table-search").val().toLowerCase(),groups=this.group(this.visibleRows());let rows=Object.values(groups).map(a=>{const r=a[a.length-1];r._change=this.latestChange(r);return r;});this.filtered=rows.filter(r=>(!q||JSON.stringify(r).toLowerCase().includes(q)));const direction=this.tableSortDirection==="asc"?1:-1,key=this.tableSortKey;this.filtered.sort((a,b)=>{if(key==="item")return this.materialShortName(a).localeCompare(this.materialShortName(b),"zh-CN")*direction;const field=key==="detail_rank"?"排名api_细分类目排名":"排名api_主类目排名",av=+a[field]||0,bv=+b[field]||0;if(!av!==!bv)return av?-1:1;if(!av&&!bv)return 0;return(av-bv)*direction;});const start=(this.pageNo-1)*this.pageSize,page=this.filtered.slice(start,start+this.pageSize);$(this.wrapper).find("#art-count").text(`共 ${this.filtered.length} 个商品`).end().find("#art-page-info").text(`${this.filtered.length?start+1:0}-${Math.min(start+this.pageSize,this.filtered.length)} / ${this.filtered.length}`).end().find("#art-tbody").html(page.map(r=>this.row(r)).join("")||'<tr><td colspan="9" class="art-empty">当前条件下暂无排名数据</td></tr>');}
	amazonUrl(r){const domains={ATVPDKIKX0DER:"www.amazon.com",A2EUQ1WTGCTBG2:"www.amazon.ca",A1AM78C64UM0Y8:"www.amazon.com.mx",A2Q3Y263D00KWC:"www.amazon.com.br",A28R8C7NBKEWEA:"www.amazon.ie",A1RKKUPIHCS9HS:"www.amazon.es",A1F83G8C2ARO7P:"www.amazon.co.uk",A13V1IB3VIYZZH:"www.amazon.fr",AMEN7PMS3EDWL:"www.amazon.com.be",A1805IZSGTT6HS:"www.amazon.nl",A1PA6795UKMFR9:"www.amazon.de",APJ6JRA9NG5V4:"www.amazon.it",A2NODRKZP88ZB9:"www.amazon.se",AE08WJ6YKNBMC:"www.amazon.co.za",A1C3SOZRARQ6R3:"www.amazon.pl",ARBP9OOSHTCHU:"www.amazon.eg",A33AVAJ2PDY3EV:"www.amazon.com.tr",A17E79C6D8DWNP:"www.amazon.sa",A2VIGQ35RCS4UG:"www.amazon.ae",A21TJRUUN4KGV:"www.amazon.in",A19VAU5U5O7RUS:"www.amazon.sg",A39IBJ37TRP1C6:"www.amazon.com.au",A1VC38T7YXB528:"www.amazon.co.jp"},asin=r.商品列表api_asin||"",domain=domains[r.商品列表api_站点id];return asin&&domain?`https://${domain}/dp/${encodeURIComponent(asin)}`:"";}
	row(r){const asin=r.商品列表api_asin||"",item=r.绑定的物料||"",change=r._change||0,amazonImage=r.商品列表api_主图链接||"",erpImage=r.物料图片||"",title=r.商品列表api_商品标题||r.排名api_商品名称||"未命名商品",amazonUrl=this.amazonUrl(r),asinDisplay=amazonUrl?`<a href="${this.esc(amazonUrl)}" target="_blank" rel="noopener noreferrer">${this.esc(asin)}</a>`:`<span title="当前站点尚未配置 Amazon 商城域名">${this.esc(asin||"—")}</span>`;return `<tr><td><div class="art-product-images"><span>${amazonImage?`<img src="${this.esc(amazonImage)}" alt="Amazon">`:'<i>A</i>'}<small>Amazon</small></span><span>${erpImage?`<img src="${this.esc(erpImage)}" alt="ERPNext">`:'<i>ERP</i>'}<small>ERPNext</small></span></div></td><td><div class="art-product"><div><b>${this.esc(title)}</b><small>${this.esc(r.排名api_品牌||r.商品列表api_产品类型||"")}</small>${r.亚马逊商品已删除?'<small class="art-deleted">已从 Amazon 当前列表删除</small>':""}</div></div></td><td>${asinDisplay}<small>${this.esc(r.商品列表api_sku||"—")}</small></td><td>${item?`<a class="art-item bound" href="/app/item/${encodeURIComponent(item)}">${this.esc(item)}</a><small>${this.esc(r.物料名称||"")}</small>`:'<span class="art-item empty">未绑定</span><small>对应物料为空</small>'}</td><td><b class="art-rank">#${this.esc(r.排名api_主类目排名||"—")}</b><small>${this.esc(r.排名api_主类目名称||"")}</small></td><td><b>#${this.esc(r.排名api_细分类目排名||"—")}</b><small>${this.esc(r.排名api_细分类目名称||"")}</small></td><td><span class="art-change ${change>0?"up":change<0?"down":"flat"}">${change>0?"↑ "+change:change<0?"↓ "+Math.abs(change):"—"}</span></td><td>${this.esc(r.商品列表api_站点id||"—")}<small>${this.esc(r.店铺||"未匹配店铺")}</small></td><td><a href="/app/amazon-rank-sku-log/${encodeURIComponent(r.name)}">${this.esc(r.抓取数据的时间||"—")}</a></td></tr>`;}
	exportCSV(){if(!this.filtered.length){frappe.show_alert("没有可导出的数据");return;}const cols=[["抓取时间","抓取数据的时间"],["ASIN","商品列表api_asin"],["SKU","商品列表api_sku"],["对应物料","绑定的物料"],["物料名称","物料名称"],["标题","商品列表api_商品标题"],["主类目排名","排名api_主类目排名"],["主类目","排名api_主类目名称"],["细分类目排名","排名api_细分类目排名"],["细分类目","排名api_细分类目名称"],["站点","商品列表api_站点id"],["店铺","店铺"]];const csv=[cols.map(x=>x[0]),...this.filtered.map(r=>cols.map(x=>r[x[1]]||""))].map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download=`amazon-rank-${frappe.datetime.get_today()}.csv`;a.click();URL.revokeObjectURL(a.href);}
	esc(v){return frappe.utils.escape_html(String(v??""));}
}

frappe.pages["amazon-rank-trend"].on_page_hide=function(wrapper){const d=wrapper.__amazon_rank_dashboard;if(d&&d.resize)window.removeEventListener("resize",d.resize);};
