frappe.pages["amazon-rank-trend"].on_page_load = function (wrapper) {
	const page = frappe.ui.make_app_page({ parent: wrapper, title: "Amazon 商品排名走势", single_column: true });
	frappe.require("assets/fengjing_app/js/主体-echarts.js", () => new AmazonRankDashboard(page, wrapper));
};

class AmazonRankDashboard {
	constructor(page, wrapper) {
		this.page = page; this.wrapper = wrapper; this.rows = []; this.filtered = []; this.pageNo = 1; this.pageSize = 20;
		this.hideDeleted = true; this.tableSortKey = "main_rank"; this.tableSortDirection = "asc"; this.trendLegendPage = 1; this.trendLegendPageSize = 18; this.trendSeries = []; this.charts = []; wrapper.__amazon_rank_dashboard = this; this.render(); this.bind(); this.setDates(30); this.load();
	}
	render() {
		$(this.wrapper).find(".layout-main-section").html(`
		<div class="art-dashboard">
		 <section class="art-hero"><div><span class="art-eyebrow">AMAZON INTELLIGENCE</span><h2>商品排名趋势中心</h2><p>从 ASIN、SKU 到对应物料，一处掌握排名变化与商品表现。</p></div><div class="art-hero-stat"><b id="hero-products">0</b><span>监控商品</span></div></section>
		 <section class="art-filters">
		  <div class="art-filter-grid">
		   ${this.select("store","店铺")}${this.select("marketplace","站点")}${this.searchSelect("asin","ASIN")}${this.searchSelect("sku","SKU")}${this.searchSelect("item","对应物料")}
		   <label>开始日期<input id="art-from" type="date"></label><label>结束日期<input id="art-to" type="date"></label>
		  </div>
		  <div class="art-actions"><div class="art-ranges"><button data-days="7">7天</button><button data-days="30" class="active">30天</button><button data-days="90">90天</button><button data-days="365">1年</button></div><button id="art-reset">重置</button><button id="art-search" class="primary">查询数据</button><button id="art-export">导出 CSV</button></div>
		 </section>
		 <section class="art-kpis" id="art-kpis"></section>
		 <section class="art-chart-grid"><article class="art-card wide"><header><h3>排名走势</h3><span>数值越小，排名越好</span></header><div id="art-trend" class="art-chart"></div><div id="art-trend-legend" class="art-trend-legend"></div></article><article class="art-card"><header><h3>最新排名变化</h3><span>与上次记录相比</span></header><div id="art-change" class="art-chart"></div></article><article class="art-card wide"><header><h3>商品排名概览</h3><span>最新排名与历史最佳</span></header><div id="art-overview" class="art-chart"></div></article><article class="art-card"><header><h3>主类目分布</h3><span>按最新商品记录</span></header><div id="art-category" class="art-chart"></div></article></section>
		 <section class="art-card art-table-card"><header><div><h3>商品明细</h3><span id="art-count"></span></div><div class="art-table-tools"><button id="art-hide-deleted" class="active">显示已删除产品</button><input id="art-table-search" placeholder="搜索标题、ASIN、SKU、物料…"></div></header><div class="art-table-wrap"><table><thead><tr><th>Amazon / ERPNext 图片</th><th>商品</th><th>ASIN / SKU</th><th><button class="art-sort" data-sort="item">对应物料 <i></i></button></th><th><button class="art-sort" data-sort="main_rank">主类目排名 <i>↑</i></button></th><th><button class="art-sort" data-sort="detail_rank">细分类目排名 <i></i></button></th><th>变化</th><th>站点 / 店铺</th><th>抓取时间</th></tr></thead><tbody id="art-tbody"></tbody></table></div><footer><span id="art-page-info"></span><div><button id="art-prev">上一页</button><button id="art-next">下一页</button></div></footer></section>
		 <div class="art-loading"><div class="art-spinner"></div><span>正在整理排名数据…</span></div>
		</div>`);
	}
	select(id, title) { return `<label>${title}<select id="art-${id}"><option value="">全部</option></select></label>`; }
	searchSelect(id, title) { return `<label>${title}<input id="art-${id}" list="art-${id}-options" placeholder="全部（可搜索或下拉选择）" autocomplete="off"><datalist id="art-${id}-options"></datalist></label>`; }
	bind() {
		const root=$(this.wrapper); root.on("click","[data-days]",e=>{root.find("[data-days]").removeClass("active");$(e.currentTarget).addClass("active");this.setDates(+e.currentTarget.dataset.days);this.load();});
		root.on("click","#art-search",()=>this.load()); root.on("click","#art-reset",()=>{root.find("select").val("");root.find("input[list]").val("");this.setDates(30);this.load();});
		root.on("input","#art-table-search",()=>{this.pageNo=1;this.renderTable();}); root.on("click","#art-prev",()=>{if(this.pageNo>1){this.pageNo--;this.renderTable();}}); root.on("click","#art-next",()=>{if(this.pageNo*this.pageSize<this.filtered.length){this.pageNo++;this.renderTable();}});
		root.on("click","#art-hide-deleted",e=>{this.hideDeleted=!this.hideDeleted;$(e.currentTarget).toggleClass("active",this.hideDeleted).text(this.hideDeleted?"显示已删除产品":"隐藏已删除产品");this.pageNo=1;this.renderTable();});
		root.on("click",".art-sort",e=>{const key=e.currentTarget.dataset.sort;if(this.tableSortKey===key)this.tableSortDirection=this.tableSortDirection==="asc"?"desc":"asc";else{this.tableSortKey=key;this.tableSortDirection="asc";}root.find(".art-sort i").text("");$(e.currentTarget).find("i").text(this.tableSortDirection==="asc"?"↑":"↓");this.pageNo=1;this.renderTable();});
		root.on("click",".art-legend-item",e=>{const index=+e.currentTarget.dataset.index,series=this.trendSeries[index],chart=$(this.wrapper).find("#art-trend")[0];if(!series||!chart)return;const instance=echarts.getInstanceByDom(chart);instance.dispatchAction({type:"legendToggleSelect",name:series.name});$(e.currentTarget).toggleClass("muted");});
		root.on("click","#art-legend-prev",()=>{if(this.trendLegendPage>1){this.trendLegendPage--;this.renderTrendLegend();}});root.on("click","#art-legend-next",()=>{if(this.trendLegendPage*this.trendLegendPageSize<this.trendSeries.length){this.trendLegendPage++;this.renderTrendLegend();}});
		root.on("click","#art-export",()=>this.exportCSV()); this.resize=()=>this.charts.forEach(c=>c.resize()); window.addEventListener("resize",this.resize);
	}
	setDates(days){const to=frappe.datetime.get_today(),from=frappe.datetime.add_days(to,-days);$(this.wrapper).find("#art-from").val(from).end().find("#art-to").val(to);}
	async load(){
		const root=$(this.wrapper), filters={}; ["store","marketplace","asin","sku","item"].forEach(k=>filters[k]=root.find(`#art-${k}`).val()); filters.date_from=root.find("#art-from").val();filters.date_to=root.find("#art-to").val();root.find(".art-loading").addClass("show");
		try {const r=await frappe.call({method:"fengjing_app.fengjing_business.page.amazon_rank_trend.amazon_rank_trend.get_rank_dashboard_data",args:{filters}});this.rows=(r.message&&r.message.rows)||[];this.fillOptions((r.message&&r.message.options)||{});this.draw();}
		catch(e){frappe.msgprint({title:"读取失败",message:"无法读取 Amazon 排名数据，请查看错误日志。",indicator:"red"});}
		finally{root.find(".art-loading").removeClass("show");}
	}
	fillOptions(o){
		const root=$(this.wrapper);
		const selectMap={store:o.stores,marketplace:o.marketplaces};
		Object.entries(selectMap).forEach(([k,vals])=>{
			const el=root.find(`#art-${k}`),old=el.val();
			el.html('<option value="">全部</option>'+((vals||[]).map(option=>{
				const value=typeof option==="object"?option.value:option;
				const label=typeof option==="object"?option.label:option;
				return `<option value="${this.esc(value)}">${this.esc(label)}</option>`;
			}).join("")));
			el.val(old);
		});
		const searchMap={asin:o.asins,sku:o.skus,item:o.items};
		Object.entries(searchMap).forEach(([k,vals])=>{
			root.find(`#art-${k}-options`).html((vals||[]).map(v=>`<option value="${this.esc(v)}"></option>`).join(""));
		});
	}
	group(){const g={};this.rows.forEach(r=>{const key=r.商品列表api_asin||r.商品列表api_sku||r.name;(g[key]||(g[key]=[])).push(r);});return g;}
	draw(){const groups=this.group(), latest=Object.values(groups).map(a=>a[a.length-1]);$(this.wrapper).find("#hero-products").text(latest.length);this.renderKpis(groups,latest);this.renderCharts(groups,latest);this.pageNo=1;this.renderTable();}
	renderKpis(groups,latest){let best=[],avg=[],up=0,down=0,bound=0;Object.values(groups).forEach(a=>{const ranks=a.map(r=>+r.排名api_主类目排名).filter(Boolean);if(ranks.length){best.push(Math.min(...ranks));avg.push(ranks[ranks.length-1]);}if(a.length>1){const d=(+a[a.length-2].排名api_主类目排名||0)-(+a[a.length-1].排名api_主类目排名||0);if(d>0)up++;if(d<0)down++;}});latest.forEach(r=>{if(r.绑定的物料)bound++;});const latestTime=this.rows.length?this.rows[this.rows.length-1].抓取数据的时间:"—";const cards=[["监控商品",latest.length,"全部 ASIN / SKU"],["排名记录",this.rows.length,"当前筛选范围"],["历史最佳",best.length?Math.min(...best):"—","主类目排名"],["平均排名",avg.length?Math.round(avg.reduce((a,b)=>a+b,0)/avg.length):"—","最新主类目"],["排名上升",up,"较上次改善"],["排名下降",down,"需要关注"],["物料绑定率",latest.length?Math.round(bound/latest.length*100)+"%":"0%",`${bound}/${latest.length} 已绑定`],["最新抓取",latestTime,"数据更新时间"]];$(this.wrapper).find("#art-kpis").html(cards.map((c,i)=>`<article class="art-kpi k${i}"><span>${c[0]}</span><b>${this.esc(c[1])}</b><small>${this.esc(c[2])}</small></article>`).join(""));}
	chart(id,option){const el=$(this.wrapper).find(id)[0];if(!el)return;const old=echarts.getInstanceByDom(el);if(old)old.dispose();const c=echarts.init(el);c.setOption(option);this.charts.push(c);return c;}
	materialShortName(row){const name=String(row.物料名称||"").trim();if(!name)return"未绑定";const match=name.match(/【([^】]+)】/);return match?match[1].trim():name;}
	productLabel(row,multiline=false){const asin=row.商品列表api_asin||row.商品列表api_sku||row.name;return `${asin}${multiline?"\n":" | "}${this.materialShortName(row)}`;}
	compactProductLabel(row,maxLength=10){const asin=row.商品列表api_asin||row.商品列表api_sku||row.name,name=this.materialShortName(row);return `${asin}\n${name.length>maxLength?name.slice(0,maxLength)+"…":name}`;}
	materialAxisLabel(row,maxLength=10){const name=this.materialShortName(row);return name.length>maxLength?name.slice(0,maxLength)+"…":name;}
	copyProduct(row){const asin=row.商品列表api_asin||row.商品列表api_sku||"",text=`${asin} & ${this.materialShortName(row)}`;if(frappe.utils&&frappe.utils.copy_to_clipboard)frappe.utils.copy_to_clipboard(text);else navigator.clipboard.writeText(text);frappe.show_alert({message:`已复制：${text}`,indicator:"green"});}
	renderTrendLegend(){const root=$(this.wrapper).find("#art-trend-legend"),start=(this.trendLegendPage-1)*this.trendLegendPageSize,items=this.trendSeries.slice(start,start+this.trendLegendPageSize),pages=Math.max(1,Math.ceil(this.trendSeries.length/this.trendLegendPageSize));root.html(`<div class="art-legend-items">${items.map((s,i)=>`<button class="art-legend-item" data-index="${start+i}" title="${this.esc(s.name)}"><i style="background:${s.itemStyle.color}"></i>${this.esc(s.name)}</button>`).join("")}</div>${pages>1?`<div class="art-legend-pages"><button id="art-legend-prev" ${this.trendLegendPage===1?"disabled":""}>上一页</button><span>${this.trendLegendPage} / ${pages}</span><button id="art-legend-next" ${this.trendLegendPage===pages?"disabled":""}>下一页</button></div>`:""}`);}
	renderCharts(groups,latest){
		const palette=["#2563eb","#06b6d4","#8b5cf6","#f59e0b","#10b981","#ec4899"],series=[];
		Object.values(groups).forEach((a,i)=>series.push({name:this.productLabel(a[a.length-1]),type:"line",smooth:true,showSymbol:a.length<20,data:a.filter(r=>r.排名api_主类目排名).map(r=>[r.抓取数据的时间,+r.排名api_主类目排名]),lineStyle:{width:2},itemStyle:{color:palette[i%palette.length]}}));
		this.trendSeries=series;this.trendLegendPage=Math.min(this.trendLegendPage,Math.max(1,Math.ceil(series.length/this.trendLegendPageSize)));this.chart("#art-trend",{tooltip:{trigger:"axis"},legend:{show:false,data:series.map(s=>s.name)},grid:{left:52,right:58,top:25,bottom:45},xAxis:{type:"time"},yAxis:{type:"value",inverse:true,min:1},dataZoom:[{type:"inside",xAxisIndex:0},{type:"inside",yAxisIndex:0},{type:"slider",xAxisIndex:0,height:16,bottom:12},{type:"slider",yAxisIndex:0,orient:"vertical",right:8,width:16}],series});this.renderTrendLegend();
		const changes=Object.values(groups).map(a=>{const row=a[a.length-1];return{axisLabel:this.materialAxisLabel(row,9),row,d:a.length>1?(+a[a.length-2].排名api_主类目排名||0)-(+row.排名api_主类目排名||0):0};}).sort((a,b)=>Math.abs(b.d)-Math.abs(a.d)).slice(0,12);
		const changeChart=this.chart("#art-change",{tooltip:{trigger:"item",formatter:p=>{const row=changes[p.dataIndex].row,amazonImage=row.商品列表api_主图链接||"",erpImage=row.物料图片||"",image=(src,label)=>`<span class="art-tooltip-image">${src?`<img src="${this.esc(src)}" alt="${label}">`:`<i>${label==="Amazon"?"A":"ERP"}</i>`}<small>${label}</small></span>`;return `<div class="art-overview-tooltip"><div class="art-tooltip-images">${image(amazonImage,"Amazon")}${image(erpImage,"ERPNext")}</div><b>${this.esc(this.materialShortName(row))}</b><div>排名变化：${p.value}</div><small>点击复制 ASIN & 物料名称</small></div>`;}},grid:{left:115,right:18,top:10,bottom:20},xAxis:{type:"value"},yAxis:{type:"category",data:changes.map(x=>x.axisLabel),axisLabel:{width:105,overflow:"truncate",fontSize:11}},series:[{type:"bar",data:changes.map(x=>({value:x.d,itemStyle:{color:x.d>=0?"#10b981":"#ef4444"}})),barMaxWidth:16}]});if(changeChart)changeChart.on("click",p=>this.copyProduct(changes[p.dataIndex].row));
		const overview=Object.values(groups).map(a=>{const row=a[a.length-1],ranks=a.map(r=>+r.排名api_主类目排名).filter(Boolean);return{axisLabel:this.materialAxisLabel(row,14),row,now:ranks.at(-1)||0,best:ranks.length?Math.min(...ranks):0};}).sort((a,b)=>a.now-b.now).slice(0,12);
		const overviewChart=this.chart("#art-overview",{tooltip:{trigger:"axis",formatter:params=>{const item=overview[params[0].dataIndex],row=item.row,amazonImage=row.商品列表api_主图链接||"",erpImage=row.物料图片||"",image=(src,label)=>`<span class="art-tooltip-image">${src?`<img src="${this.esc(src)}" alt="${label}">`:`<i>${label==="Amazon"?"A":"ERP"}</i>`}<small>${label}</small></span>`;return `<div class="art-overview-tooltip"><div class="art-tooltip-images">${image(amazonImage,"Amazon")}${image(erpImage,"ERPNext")}</div><b>${this.esc(this.materialShortName(row))}</b><div>${params.map(p=>`${p.marker}${p.seriesName}：${p.value}`).join("<br>")}</div><small>点击复制 ASIN & 物料名称</small></div>`;}},legend:{bottom:2},grid:{left:145,right:20,top:15,bottom:65},xAxis:{type:"value",inverse:true,min:1},yAxis:{type:"category",inverse:true,data:overview.map(x=>x.axisLabel),axisLabel:{width:135,overflow:"truncate",fontSize:11}},series:[{name:"最新",type:"bar",data:overview.map(x=>x.now),itemStyle:{color:"#2563eb"},barMaxWidth:14},{name:"最佳",type:"bar",data:overview.map(x=>x.best),itemStyle:{color:"#93c5fd"},barMaxWidth:14}]});if(overviewChart)overviewChart.on("click",p=>this.copyProduct(overview[p.dataIndex].row));
		const cat={};latest.forEach(r=>{const k=r.排名api_主类目名称||"未分类";cat[k]=(cat[k]||0)+1;});this.chart("#art-category",{tooltip:{trigger:"item"},legend:{type:"scroll",bottom:2,itemGap:12},series:[{type:"pie",radius:["36%","60%"],center:["50%","38%"],label:{formatter:"{b}\n{d}%"},data:Object.entries(cat).map(([name,value])=>({name,value}))}]});}
	renderTable(){const q=$(this.wrapper).find("#art-table-search").val().toLowerCase(),groups=this.group();let rows=Object.values(groups).map(a=>{const r=a[a.length-1],prev=a.length>1?a[a.length-2]:null;r._change=prev?(+a[a.length-2].排名api_主类目排名||0)-(+r.排名api_主类目排名||0):0;return r;});this.filtered=rows.filter(r=>(!this.hideDeleted||!r.亚马逊商品已删除)&&(!q||JSON.stringify(r).toLowerCase().includes(q)));const direction=this.tableSortDirection==="asc"?1:-1,key=this.tableSortKey;this.filtered.sort((a,b)=>{if(key==="item")return this.materialShortName(a).localeCompare(this.materialShortName(b),"zh-CN")*direction;const field=key==="detail_rank"?"排名api_细分类目排名":"排名api_主类目排名",av=+a[field]||0,bv=+b[field]||0;if(!av!==!bv)return av?-1:1;if(!av&&!bv)return 0;return(av-bv)*direction;});const start=(this.pageNo-1)*this.pageSize,page=this.filtered.slice(start,start+this.pageSize);$(this.wrapper).find("#art-count").text(`共 ${this.filtered.length} 个商品`).end().find("#art-page-info").text(`${this.filtered.length?start+1:0}-${Math.min(start+this.pageSize,this.filtered.length)} / ${this.filtered.length}`).end().find("#art-tbody").html(page.map(r=>this.row(r)).join("")||'<tr><td colspan="9" class="art-empty">当前条件下暂无排名数据</td></tr>');}
	row(r){const asin=r.商品列表api_asin||"",item=r.绑定的物料||"",change=r._change||0,amazonImage=r.商品列表api_主图链接||"",erpImage=r.物料图片||"";return `<tr><td><div class="art-product-images"><span>${amazonImage?`<img src="${this.esc(amazonImage)}" alt="Amazon">`:'<i>A</i>'}<small>Amazon</small></span><span>${erpImage?`<img src="${this.esc(erpImage)}" alt="ERPNext">`:'<i>ERP</i>'}<small>ERPNext</small></span></div></td><td><div class="art-product"><div><b>${this.esc(r.商品列表api_商品标题||"未命名商品")}</b><small>${this.esc(r.排名api_品牌||r.商品列表api_产品类型||"")}</small>${r.亚马逊商品已删除?'<small class="art-deleted">已从 Amazon 当前列表删除</small>':""}</div></div></td><td>${asin?`<a href="https://www.amazon.com/dp/${encodeURIComponent(asin)}" target="_blank">${this.esc(asin)}</a>`:"—"}<small>${this.esc(r.商品列表api_sku||"—")}</small></td><td>${item?`<a class="art-item bound" href="/app/item/${encodeURIComponent(item)}">${this.esc(item)}</a><small>${this.esc(r.物料名称||"")}</small>`:'<span class="art-item empty">未绑定</span><small>对应物料为空</small>'}</td><td><b class="art-rank">#${this.esc(r.排名api_主类目排名||"—")}</b><small>${this.esc(r.排名api_主类目名称||"")}</small></td><td><b>#${this.esc(r.排名api_细分类目排名||"—")}</b><small>${this.esc(r.排名api_细分类目名称||"")}</small></td><td><span class="art-change ${change>0?"up":change<0?"down":"flat"}">${change>0?"↑ "+change:change<0?"↓ "+Math.abs(change):"—"}</span></td><td>${this.esc(r.商品列表api_站点id||"—")}<small>${this.esc(r.店铺||"未匹配店铺")}</small></td><td><a href="/app/amazon-rank-sku-log/${encodeURIComponent(r.name)}">${this.esc(r.抓取数据的时间||"—")}</a></td></tr>`;}
	exportCSV(){if(!this.filtered.length){frappe.show_alert("没有可导出的数据");return;}const cols=[["抓取时间","抓取数据的时间"],["ASIN","商品列表api_asin"],["SKU","商品列表api_sku"],["对应物料","绑定的物料"],["物料名称","物料名称"],["标题","商品列表api_商品标题"],["主类目排名","排名api_主类目排名"],["主类目","排名api_主类目名称"],["细分类目排名","排名api_细分类目排名"],["细分类目","排名api_细分类目名称"],["站点","商品列表api_站点id"],["店铺","店铺"]];const csv=[cols.map(x=>x[0]),...this.filtered.map(r=>cols.map(x=>r[x[1]]||""))].map(a=>a.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(",")).join("\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob(["\ufeff"+csv],{type:"text/csv"}));a.download=`amazon-rank-${frappe.datetime.get_today()}.csv`;a.click();URL.revokeObjectURL(a.href);}
	esc(v){return frappe.utils.escape_html(String(v??""));}
}

frappe.pages["amazon-rank-trend"].on_page_hide=function(wrapper){const d=wrapper.__amazon_rank_dashboard;if(d&&d.resize)window.removeEventListener("resize",d.resize);};
