/* Run: node test_calculator.js */
{
 const assert=require('node:assert/strict'),{ozfcCalculate,OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const post={id:'兴远-XY-Post-RU',fixed:15,rate:34.75,min_weight:.001,max_weight:5,min_value:0,max_value:0,no_value_limit:true,max_side:60,max_sum:90,min_sorted_sides:[14,11,0]};
 const item={length:140,width:110,height:20,weight:343,value:9000};
 assert.equal(ozfcCalculate(item,post,.08).price,26.92);assert.equal(ozfcCalculate(item,post,.08).eligible,true);
 assert.equal(ozfcCalculate({...item,width:109},post,.08).eligible,false);
 assert.equal(ozfcCalculate({...item,weight:5001},post,.08).eligible,false);
 const c=Object.create(OzFreightCanvas.prototype);c.bootData={defaults:{routes:[post]}};
 const config={routes:[],guoo_snapshot:1,xy_post_snapshot:2,cel_rfbs_snapshot:1};c.prepare({nodes:[]},config);
 config.routes[0].rate=40;c.prepare({nodes:[]},config);assert.equal(config.routes.length,1);assert.equal(config.routes[0].rate,40);
 console.log('PASS: XY extra snapshot preserves edits; E-post minimum dimensions and unspecified value limit');
}
{
 const assert=require('node:assert/strict'),{ozfcCalculate,OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const hk={id:'CEL-RFBS-HK-Express',fixed:19,rate:96,min_weight:.001,max_weight:25,min_value:1,max_value:500000,max_side:150,max_sum:310,divisor:6000,volumetric_min_sum:60,step:.1};
 const item={length:200,width:200,height:200,weight:100,value:1500};
 assert.equal(ozfcCalculate(item,hk,.08).price,28.6);
 assert.equal(ozfcCalculate({...item,length:210},hk,.08).price,153.4);
 assert.equal(ozfcCalculate({...item,weight:101},hk,.08).price,38.2);
 const c=Object.create(OzFreightCanvas.prototype);c.bootData={defaults:{routes:[hk]}};
 const config={routes:[],guoo_snapshot:1,xy_post_snapshot:2};c.prepare({nodes:[]},config);
 config.routes[0].fixed=25;c.prepare({nodes:[]},config);
 assert.equal(config.routes.length,1);assert.equal(config.routes[0].fixed,25);
 console.log('PASS: CEL rFBS merge preserves edits; HK conditional volume and hundred-gram rounding');
}
{
 const assert=require('node:assert/strict'),{OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const c=Object.create(OzFreightCanvas.prototype);c.c={cny_per_rub:.08,routes:[{id:'parcel-route',enabled:true,provider:'测试',name:'按包计费',speed:'Standard',mode:'RFBS',destination:'俄罗斯',fixed:5,rate:10,min_weight:0,max_weight:20,min_value:0,max_value:10000,max_side:100,max_sum:200,divisor:12000,step:.001}]};
 const n={id:'flow-test',manual:true,manualSale:100,x:0,y:0,item:{item_code:'SIM-flow',quantity:4,value:10,value_currency:'CNY',length:100,width:100,height:100,weight:200},packing:{mode:'custom',rows:[{quantity:2,length:120,width:110,height:100,weight:500},{quantity:2,length:120,width:110,height:100,weight:500}]}};
 c.s={nodes:[n],active:n.id,focus:n.id,expanded:[n.id],view:{x:0,y:0,z:1}};c.snap=c.paint=c.change=c.status=()=>{};c.root={querySelector:()=>null};
 assert.equal(c.parcelResults(n).length,2);assert.equal(c.parcelResults(n)[0].chosen.bill,.5);
 assert.deepEqual(c.parcelFilters(n,0),{destination:'俄罗斯',mode:'RFBS',provider:'',speeds:['Standard']});
 assert.deepEqual(c.parcelFilters({parcelQuotes:[{filters:{speeds:[]}}]},0).speeds,[]);
 assert.equal(c.matchesParcelFilters({destination:'加拿大',mode:'RFBS'},c.parcelFilters(n,0)),false);
 assert.equal(c.matchesParcelFilters({destination:'俄罗斯',mode:'FBP'},c.parcelFilters(n,0)),false);
 assert.equal(c.matchesParcelFilters({name:'Standard',mode:'rFBS',destination:'俄罗斯'},{...c.parcelFilters(n,0),speeds:['Standard']}),true);
 assert.equal(c.matchesParcelFilters({name:'Economy',mode:'rFBS',destination:'俄罗斯'},{...c.parcelFilters(n,0),speeds:['Standard']}),false);
 assert.throws(()=>c.validateLogisticsFilters({speeds:'Express'}));
 assert.equal(c.combinedFreight(n).price,20);assert.equal((c.quotes(n).match(/class="fc-card fc-quotes"/g)||[]).length,2);
 const valueRoute={...c.c.routes[0],max_value:1500,value_currency:'RUB'},parcel=c.parcelResults(n)[0];
 assert.equal(c.suggestedRouteState(n,parcel,valueRoute,100).kind,'ready');
 assert.equal(c.suggestedRouteState(n,parcel,valueRoute,400).kind,'blocked');
 assert.equal(c.suggestedRouteState(n,parcel,valueRoute,undefined).kind,'pending');
 assert.match(c.suggestedRouteState(n,parcel,valueRoute,400).detail,/本包分摊货值 ¥200.00/);
 const positions=c.flowPositions(n);assert.ok(positions.packing.x>n.x&&positions.quote.x>positions.packing.x&&positions.cost.x>positions.quote.x&&positions.rivals.x>positions.sale.x);
 n.parcelQuotes=[{routeId:'parcel-route',x:740,y:0},{routeId:'not-available',x:740,y:760}];assert.equal(c.combinedFreight(n),undefined);
 n.parcelQuotes[1].routeId='parcel-route';n.packing.rows[1].quantity=1;assert.equal(c.combinedFreight(n),undefined);n.packing.rows[1].quantity=2;
 assert.doesNotThrow(()=>c.validatePacking(n));assert.throws(()=>c.validatePacking({...n,packing:{mode:'custom',rows:[{quantity:-1}]}}));
 c.copyMaterial();const snapshot=JSON.stringify(n);
 c.pasteMaterial().then(()=>{const copied=c.s.nodes[1];assert.notEqual(copied.id,n.id);assert.deepEqual(copied.packing,n.packing);assert.notEqual(copied.packing,n.packing);copied.packing.rows[0].weight=999;copied.item.value=99;copied.parcelQuotes[0].routeId='changed';assert.equal(JSON.stringify(n),snapshot);assert.equal(c.s.focus,copied.id);console.log('PASS: independent deep-copy paste, per-package actual weights, fixed fees, route selection and connected flow');}).catch(e=>{console.error(e);process.exitCode=1;});
}
{
 const assert=require('node:assert/strict'),{ozfcCalculate,ozfcCost,OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const item={length:100,width:100,height:100,weight:250,value:100,value_currency:'RUB',quantity:3};
 const r={fixed:3,rate:20,min_weight:.001,max_weight:30,min_value:1,max_value:1500,max_side:60,max_sum:90,divisor:12000,step:.001};
 const result=ozfcCalculate(item,r,.08);assert.equal(result.price,18);assert.equal(result.bill,.75);assert.equal(result.eligible,true);
 assert.equal(ozfcCalculate({...item,quantity:0},r,.08).eligible,false);
 assert.equal(ozfcCalculate({...item,value:600},r,.08).eligible,false);
 const cost=ozfcCost(8,18,35,10,{quantity:3});assert.equal(cost.cost,24);assert.equal(cost.unitCost,8);assert.equal(cost.quantity,3);
 const c=Object.create(OzFreightCanvas.prototype);assert.equal(c.normalize({item_code:'test'}).quantity,1);
 c.bootData={defaults:{routes:[{id:'GUOO-test',provider:'GUOO'}]}};const state={nodes:[]},config={routes:[],xy_post_snapshot:2};
 c.prepare(state,config);assert.equal(config.routes.length,1);c.prepare(state,config);assert.equal(config.routes.length,1);
 console.log('PASS: default quantity, aggregate parcel weight/value/cost, one fixed charge, non-destructive GUOO merge');
}
{
 const assert=require('node:assert/strict'),{OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const c=Object.create(OzFreightCanvas.prototype);c.c={cny_per_rub:.08};
 assert.match(c.competitorRmb(400,'RUB'),/人民币 ¥32.00/);
 assert.match(c.competitorRmb(12,'CNY'),/人民币 ¥12.00/);
 assert.match(c.competitorRmb(12,'USD'),/暂无人民币换算汇率/);
 c.c.cny_per_rub=0;assert.match(c.competitorRmb(400,'RUB'),/暂无人民币换算汇率/);
 console.log('PASS: individual rival quote RMB reference conversion and missing FX fallback');
}
{
 const assert=require('node:assert/strict'),{OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const c=Object.create(OzFreightCanvas.prototype);c.c={cny_per_rub:.08};
 const n={saleOverride:999,meta:{prices:[{amount:100,currency:'CNY',cny:100}]},competitors:{products:[{offers:[{price:400,currency:'RUB',rejectionReason:[]},{price:1,currency:'RUB',rejectionReason:['bad-offer-price']}]}]}};
 const html=c.briefQuoteHTML(n);assert.match(html,/RUB 400.00/);assert.match(html,/≈ ¥32.00/);assert.match(html,/CNY 100.00/);assert.doesNotMatch(html,/999/);assert.match(html,/2 条/);assert.match(html,/fc-brief-has-rivals/);
 assert.doesNotMatch(c.briefQuoteHTML({meta:n.meta}),/fc-brief-has-rivals/);
 c.c.cny_per_rub=0;assert.match(c.briefQuoteHTML(n),/暂无人民币汇率/);
 console.log('PASS: summary competition RMB conversion and raw backend price without simulation override');
}
{
 const assert=require('node:assert/strict'),{OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const c=Object.create(OzFreightCanvas.prototype);c.s={nodes:Array.from({length:123},(_,i)=>({id:'page-'+i,x:i*350,y:0})),view:{x:0,y:0,z:1}};
 assert.equal(c.tablePageNodes().length,50);c.tablePage=2;assert.equal(c.tablePageNodes().length,23);c.tablePage=99;assert.equal(c.tablePageNodes()[0].id,'page-100');
 const n=c.s.nodes[120];n.competitors={products:[{offers:[{price:9,currency:'RUB',rejectionReason:['bad-offer-price']},{price:40,currency:'RUB',rejectionReason:[]},{price:35,currency:'RUB',rejectionReason:[]},{price:5,currency:'CNY',rejectionReason:[]}]}]};
 assert.match(c.competitorBrief(n),/4 条/);assert.match(c.competitorBrief(n),/RUB 35.00 \/ CNY 5.00/);
 c.change=c.paint=()=>{};c.stage={scrollTop:9999,scrollLeft:888};c.multiSelect=true;c.jumpMaterial(n.id);
 assert.equal(c.stage.scrollTop,0);assert.equal(c.stage.scrollLeft,0);
 assert.equal(c.s.displayMode,'canvas');assert.deepEqual(c.s.expanded,[n.id]);assert.equal(c.s.focus,n.id);assert.equal(c.s.view.x,60-n.x);assert.equal(c.multiSelect,false);
 console.log('PASS: table pagination, per-currency valid competitor minimum, jump reveals and locates material');
}
{
 const assert=require('node:assert/strict'),{OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const c=Object.create(OzFreightCanvas.prototype),n={id:'arrange-test',x:100,y:200,quote:{x:999,y:888},cost:{x:1,y:2},sale:{x:3,y:4},rivals:{x:5,y:6}};
 c.s={nodes:[n],expanded:[]};c.snap=c.change=c.paint=c.status=()=>{};c.arrangeMaterialCards(n.id);
 assert.deepEqual([n.x,n.y],[100,200]);assert.deepEqual(n.packPos,{x:470,y:200});assert.deepEqual(n.quote,{x:840,y:200});assert.deepEqual(n.cost,{x:1370,y:200});
 assert.deepEqual(n.sale,{x:2410,y:200});assert.deepEqual(n.rivals,{x:2780,y:200});assert.deepEqual(c.s.expanded,[]);
 console.log('PASS: organize one material child cards without moving material or changing expansion');
}
{
 const assert=require('node:assert/strict'),{OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const canvas=Object.create(OzFreightCanvas.prototype);canvas.s={expanded:['one','two'],active:'one'};canvas.paint=()=>{};
 canvas.toggleMultiSelect();assert.deepEqual(canvas.expanded(),[]);assert.deepEqual(canvas.s.expanded,['one','two']);
 canvas.toggleMultiSelect();assert.deepEqual(canvas.expanded(),['one','two']);
 console.log('PASS: multiselect temporarily collapses children and restores original expansion');
}
{
 const assert=require('node:assert/strict'),{OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const canvas=Object.create(OzFreightCanvas.prototype),manual={id:'manual',x:0,y:10};
 canvas.s={nodes:[manual,...Array.from({length:5},(_,i)=>({id:String(i),systemGenerated:true,x:100,y:i*900,quote:{x:500,y:i*900}}))]};
 canvas.arrangeSystemCards(1000);
 assert.deepEqual(canvas.s.nodes.slice(1).map(n=>[n.x,n.y]),[[1000,0],[1350,0],[1700,0],[2050,0],[2400,0]]);
 assert.deepEqual([manual.x,manual.y],[0,10]);assert.equal(canvas.s.nodes[1].quote.x,1400);
 canvas.s.nodes.push(...Array.from({length:6},(_,i)=>({systemGenerated:true,x:0,y:0})));
 canvas.arrangeSystemCards(1000);assert.equal(canvas.s.nodes.at(-1).x,1000);assert.equal(canvas.s.nodes.at(-1).y,620);
 canvas.snap=canvas.change=canvas.paint=canvas.status=()=>{};canvas.sortCards();
 assert.deepEqual([manual.x,manual.y],[0,0]);assert.deepEqual([canvas.s.nodes[1].x,canvas.s.nodes[1].y],[0,660]);
 console.log('PASS: ten-column compact matrix, separate manual/system groups, linked cards follow');
}
{
 const assert=require('node:assert/strict');
 const {ozfcCompetitorVersion,OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const first=ozfcCompetitorVersion(null,{key:'店铺|123',offers:[{price:10}],raw:{sample:1},collectedAt:'2026-09-17T00:00:00Z'});
 const second=ozfcCompetitorVersion(first,{key:'店铺|123',offers:[{price:20}],raw:{sample:2}});
 const third=ozfcCompetitorVersion(second,{key:'店铺|123',offers:[{price:30}],raw:{sample:3}});
 assert.equal(third.version,3);assert.deepEqual(third.history.map(v=>v.offers[0].price),[10,20]);assert.equal(third.history[1].history,undefined);assert.equal(first.history.length,0);
 const restored=JSON.parse(JSON.stringify(third));assert.equal(restored.history[0].raw.sample,1);
 const legacy=ozfcCompetitorVersion({key:'old',offers:[],raw:{old:true}},{key:'old',offers:[]});assert.equal(legacy.version,2);assert.equal(legacy.history[0].version,1);
 console.log('PASS: competitor version history, flat full snapshots, legacy upgrade, JSON persistence, previous records unchanged');
}
{
 const assert=require('node:assert/strict');
 const {ozfcCanvasCollectionTargets}=require('./ozon_freight_calcula.js');
 const price={store:'店铺A',product_id:'6013264220'};
 const nodes=[{meta:{prices:[price,price,{store:'店铺B',product_id:'6013264220'}]}},{meta:{prices:[price]}},{manual:true,meta:{prices:[{store:'忽略',product_id:'123'}]}},{meta:{prices:[{store:'店铺A',product_id:'unknown'}]}}];
 assert.deepEqual(ozfcCanvasCollectionTargets(nodes),[{store:'店铺A',itemId:'6013264220'},{store:'店铺B',itemId:'6013264220'}]);
 assert.deepEqual(ozfcCanvasCollectionTargets([]),[]);
 console.log('PASS: current canvas targets only, store/product deduplication, manual/missing ID skipped');
}
// Execute the generated browser command against fake responses (no network traffic).
(async()=>{
 const assert=require('node:assert/strict'),vm=require('node:vm');
 const {ozfcCollectionCommand}=require('./ozon_freight_calcula.js');
 let calls=0,clipboard='',delay=0;
 const env={location:{hostname:'seller.ozon.ru'},window:{},URLSearchParams,AbortSignal,Date,JSON,
  console:{log(){},warn(){}},setTimeout(resolve,ms){delay+=ms;resolve();},
  navigator:{clipboard:{async writeText(text){clipboard=text;}}},
  async fetch(){calls++;return {ok:calls===1,status:calls===1?200:429,headers:{get(){return 'application/json';}},async json(){return {competitors:[],syncing:false};}}}
 };
 const products=[1,2,3].map(id=>({store:'店铺',companyId:'5617125',itemId:String(id)}));
 await vm.runInNewContext(ozfcCollectionCommand(products),env);
 const batch=JSON.parse(clipboard);assert.equal(calls,2);assert.equal(delay,1500);assert.equal(batch.results.length,2);assert.equal(batch.results[0].ok,true);assert.equal(batch.results[1].status,429);assert.ok(batch.collectedAt);assert.equal(env.window.__ozfcCollecting,false);
 env.fetch=async()=>({ok:true,status:200,headers:{get(){return 'application/json';}},async json(){return {competitors:[],syncing:false};}});
 env.navigator.clipboard.writeText=async()=>{throw Error('Clipboard denied')};env.copy=text=>{clipboard=text};
 await vm.runInNewContext(ozfcCollectionCommand(products.slice(0,1)),env);assert.equal(JSON.parse(clipboard).results.length,1);
 console.log('PASS: generated F12 command serial delay, timestamps, 429 stop, automatic clipboard and DevTools copy fallback');
 env.navigator.clipboard.writeText=async text=>{clipboard=text};
 let requested=[],counts={};env.fetch=async url=>{
  const id=new URL('https://seller.ozon.ru'+url).searchParams.get('item_id');requested.push(id);counts[id]=(counts[id]||0)+1;
  return {ok:true,status:200,headers:{get(){return 'application/json';}},async json(){return {competitors:[],syncing:id==='2'&&counts[id]<3};}};
 };
 await vm.runInNewContext(ozfcCollectionCommand(products),env);
 assert.deepEqual(requested,['1','2','3','2','2']);assert.equal(JSON.parse(clipboard).results.length,3);assert.equal(JSON.parse(clipboard).results[1].attempts,3);
 requested=[];env.fetch=async url=>{requested.push(url);return {ok:false,status:500,headers:{get(){return 'application/json';}}};};
 await vm.runInNewContext(ozfcCollectionCommand(products.slice(0,1)),env);
 assert.equal(requested.length,5);assert.equal(JSON.parse(clipboard).results[0].attemptHistory.length,5);
 console.log('PASS: complete first pass, retry pending only, latest result replaces attempt, four extra retries maximum');
})().catch(e=>{console.error(e);process.exitCode=1;});
{
 const {ozfcCollectionCommand,ozfcParseCompetitors,OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const assert=require('node:assert/strict');
 const raw={competitors:[{sku:'5514900265',itemId:'6013264220',url:'https://ozon.ru/product/5552034272/',price:{currencyCode:'RUB',units:'436',nanos:750000000},rejectionReason:['bad-offer-price'],downloadedAt:'2026-09-16T05:34:26Z'}],syncing:false};
 const parsed=ozfcParseCompetitors(raw);assert.equal(parsed.results[0].offers[0].price,436.75);assert.equal(parsed.results[0].collectedAt,null);
 assert.throws(()=>ozfcParseCompetitors({...raw,competitors:[{...raw.competitors[0],url:'javascript:alert(1)'}]}));
 assert.throws(()=>ozfcParseCompetitors({...raw,competitors:[{...raw.competitors[0],price:{currencyCode:'RUB',units:'436',nanos:1e9}}]}));
 const canvas=Object.create(OzFreightCanvas.prototype);canvas.snap=canvas.change=canvas.paint=()=>{};
 const node={id:'user-1',item:{item_code:'item-1',value:88},meta:{prices:[{store:'店铺',product_id:'6013264220'}]}};canvas.s={nodes:[node]};
 assert.equal(canvas.applyCompetitors(JSON.stringify(raw)).matched,1);assert.equal(node.item.value,88);assert.equal(node.competitors.products[0].offers[0].price,436.75);
 assert.equal(canvas.competitorHTML(node),'');
 assert.match(canvas.competitorCountHTML(node),/<b>1<\/b>/);
 canvas.s.expanded=[node.id];
 assert.match(canvas.competitorHTML(node),/https:\/\/seller.ozon.ru\/app\/prices\/manager\/6013264220\/prices/);
 assert.equal(canvas.competitorManagerLink('bad-id'),'');
 assert.ok(canvas.competitorHTML(node).includes('bad-offer-price'));assert.ok(canvas.competitorHTML(node).includes('未提供'));
 canvas.s.displayMode='table';node.rivalsHidden=true;assert.match(canvas.competitorHTML(node),/bad-offer-price/);
 canvas.s.displayMode='canvas';node.rivalsHidden=false;
 const batch={format:'ozfc-competitors-v1',collectedAt:'2026-09-17T00:00:00Z',results:[{store:'店铺',itemId:'6013264220',ok:true,data:{competitors:[],syncing:false}}]};
 canvas.applyCompetitors(batch);assert.equal(node.competitors.products[0].offers.length,0);
 assert.equal(node.competitors.products[0].history.length,1);assert.equal(node.competitors.products[0].history[0].offers[0].price,436.75);
 canvas.rivalVersions=new Map([[node.id+'|'+node.competitors.products[0].key,'1']]);
 assert.ok(canvas.competitorHTML(node).includes('436.75'));assert.ok(canvas.competitorHTML(node).includes('历史 · 第1版'));
 canvas.rivalVersions.clear();
 batch.results[0].ok=false;canvas.applyCompetitors(batch);assert.equal(node.competitors.products[0].offers.length,0);
 batch.results[0].ok=true;batch.results[0].data={...raw,syncing:true};assert.equal(canvas.applyCompetitors(batch).failed,1);assert.equal(node.competitors.products[0].offers.length,0);
 const cmd=ozfcCollectionCommand([{store:'店铺',itemId:'6013264220',companyId:'5617125'}]);
 assert.doesNotThrow(()=>new Function(cmd));assert.ok(cmd.includes('1500'));assert.ok(cmd.includes('navigator.clipboard.writeText'));assert.ok(!cmd.includes('document.cookie'));
 console.log('PASS: browser collection command, nanos decimal, safe URLs, collection time, ID matching, empty results, pending/failure preservation');
}
// Async regression: refresh uses store/product identity and preserves user estimates.
(async()=>{
 const {OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const assert=require('node:assert/strict');
 global.crypto ||= require('node:crypto').webcrypto;
 const c=Object.create(OzFreightCanvas.prototype);
 const user={id:'user-1',item:{item_code:'item-1',value:88},x:0,y:0,meta:{costs:[],prices:[],errors:[]}};
 c.s={nodes:[user]};c.snap=c.change=c.paint=c.status=()=>{};
 const product={store:'store-1',product_id:'6166309025',ozon_sku_ids:['5647274301'],offer_id:'offer-1',name:'商品',image:'/image.png',amount:10,currency:'CNY',commissions:[],item:{item_code:'item-1',item_name:'物料'}};
 c.api=async(method,args)=>!args?.store?{stores:['store-1']}:{products:[product,{...product,product_id:'other-id',ozon_sku_ids:['other-sku'],item:null}],more:false};
 await c.refreshSkus();assert.equal(c.s.nodes.length,2);assert.equal(user.item.value,88);assert.equal(user.meta.prices[0].product_id,'6166309025');
 const auto=c.s.nodes[1];assert.equal(auto.ozonOnly,true);assert.equal(auto.item.image,'/image.png');assert.ok(auto.x>user.x+330);
 await c.refreshSkus();assert.equal(c.s.nodes.length,2);assert.equal(c.s.nodes[0],user);assert.equal(user.item.value,88);assert.equal(c.skuRefreshing,false);
 c.api=async()=>{throw Error('network')};await assert.rejects(()=>c.refreshSkus());assert.equal(c.skuRefreshing,false);
 console.log('PASS: SKU refresh pagination merge, user cost preservation, unbound Ozon images, no duplicates, failure unlock');
})().catch(e=>{console.error(e);process.exitCode=1;});
const assert = require('node:assert/strict');
const {ozfcCalculate: calc, ozfcCost, OzFreightCanvas} = require('./ozon_freight_calcula.js');
const ozfcCalculate = calc;
const route={fixed:3.37,rate:39.3,min_weight:.001,max_weight:.5,min_value:1,max_value:1500,max_side:60,max_sum:90,divisor:0,step:0,battery:true,liquid:false};
const item={length:100,width:200,height:100,weight:100,value:1500};
assert.equal(calc(item,route).price,7.30);
assert.equal(calc(item,route).eligible,true);
assert.equal(calc({...item,weight:500},route).eligible,true);
assert.equal(calc({...item,weight:501},route).eligible,false);
assert.equal(calc({...item,value:1501},route).eligible,false);
assert.equal(calc({...item,length:610},route).eligible,false);
assert.equal(calc({...item,value:''},route).eligible,false);
assert.equal(calc({...item,weight:'abc'},route).eligible,false);
assert.equal(calc({...item,liquid:true},route).eligible,false);
assert.equal(calc({...item,battery:true},{...route,battery:false}).eligible,false);
const big={...route,fixed:40.44,rate:28.1,min_weight:2,min_exclusive:true,max_weight:30,min_value:1500,value_exclusive:true,max_value:7000,max_side:150,max_sum:310,divisor:12000,max_billable:31};
const box={...item,length:600,width:400,height:300,weight:3000,value:2000};
assert.equal(calc(box,big).bill,6);
assert.equal(calc(box,big).price,209.04);
assert.equal(calc({...box,weight:2000},big).eligible,false);
assert.equal(calc({...box,length:1500,width:1000,height:1000},big).eligible,false);
assert.equal(calc({...item,weight:101},{...route,step:.05}).bill.toFixed(2),'0.15');
assert.equal(calc({...box,length:1000,width:900,height:100},{...big,sorted_sides:[150,80,80]}).eligible,false);
assert.equal(calc(item,route).steps.length,5);
assert.equal(calc({...item,value_currency:'CNY',value:119.28},route,.07952).eligible,true);
assert.equal(calc({...item,value_currency:'CNY',value:120},route,.07952).eligible,false);
assert.equal(calc({...item,value_currency:'CNY'},route,0).eligible,false);
assert.equal(calc({...item,value_currency:'CNY',weight:.343,value:800},route,.07952).eligible,false);
const premium={...route,fixed:24.71,rate:28.1,max_weight:5,min_value:7000,value_exclusive:true,max_value:250000,max_side:150,max_sum:250};
const corrected=calc({...item,value_currency:'CNY',length:210,width:190,height:50,weight:343,value:800},premium,.07952);
assert.equal(corrected.eligible,true);
assert.equal(corrected.price,34.35);
const canvas=Object.create(OzFreightCanvas.prototype);
canvas.s={nodes:[],expanded:[],active:null,exclusive:true};
canvas.snap=()=>{};canvas.change=()=>{};canvas.paint=()=>{};
canvas.activate('a');canvas.activate('b');assert.deepEqual(canvas.expanded(),['b']);
canvas.s.exclusive=false;canvas.activate('a');assert.deepEqual(canvas.expanded(),['b','a']);
canvas.activate('b');assert.deepEqual(canvas.expanded(),['a']);
canvas.activate('a');assert.deepEqual(canvas.expanded(),[]);
canvas.bootData={exchange:{cny_per_rub:.07952,date:'2026-09-16'}};
const legacy={nodes:[{item:{value:1500}}],active:'a'},config={routes:[]};
assert.equal(canvas.prepare(legacy,config),true);
assert.equal(legacy.nodes[0].item.value_currency,'CNY');
assert.equal(legacy.nodes[0].item.value,'119.28');
const meta=canvas.metaHTML({id:'a',item:{weight:343},meta:{costs:[{amount:5.1,currency:'CNY',source:'库存成本'}],prices:[]}});
assert.match(meta,/5\.10/);assert.match(meta,/只读/);
console.log('PASS: calculator, CNY conversion, stock-weight regression, multi-card switch, old-canvas migration, read-only cost');
const example=ozfcCost(8.79,62.3,28,18);
assert.equal(example.total,71.09);
assert.equal(example.price,131.65);
assert.ok(example.actualMargin>=28);
assert.equal(ozfcCost(8.79,62.3,35,18).price,151.26);
assert.ok(ozfcCost(8.79,62.3,35,null).error);
assert.ok(ozfcCost(null,62.3,35,18).error);
assert.ok(ozfcCost(8.79,null,35,18).error);
assert.ok(ozfcCost(8.79,62.3,85,18).error);
assert.equal(ozfcCost(8.79,62.3,0,0).price,71.09);
canvas.c={margin_pct:35,cny_per_rub:.07952};canvas.s.nodes=[];
const costNode={id:'a',item:{},meta:{costs:[{amount:8.79,currency:'CNY'}],prices:[{store:'店铺',sku:'SKU',commissions:[{schema:'FBP',percent:11},{schema:'RFBS',percent:12}]}]},x:0,y:0};
costNode.parcelQuotes=[{filters:{destination:'',mode:'',provider:'',speeds:[]}}];
const freight=[{eligible:true,r:{id:'route',provider:'CEL',name:'Economy',mode:'FBP'},price:62.3}];
assert.match(canvas.costCard(costNode,freight),/11%/);
assert.match(canvas.costCard(costNode,freight),/data-cost="1"/);
assert.match(canvas.costCard(costNode,freight),/⑥ 利润校验/);
costNode.commissionSchema='RFBS';assert.match(canvas.costCard(costNode,freight),/12%/);
canvas.c.routes=[{...route,id:'route',provider:'CEL',name:'Economy',mode:'FBP'}];canvas.c.cny_per_rub=.07952;
costNode.item={length:210,width:190,height:50,weight:343,value:78,value_currency:'CNY'};
Object.assign(costNode.meta.prices[0],{amount:78,cny:78,currency:'CNY'});
assert.match(canvas.quotes(costNode),/fc-cost-card/);
assert.match(canvas.quotes(costNode),/用此运费计算售价/);
canvas.s.nodes=[costNode];canvas.s.expanded=['a'];let connectors='';
canvas.root={querySelector:()=>({set innerHTML(s){connectors=s;}})};
canvas.drawLines();assert.equal((connectors.match(/<path /g)||[]).length,4);
assert.equal((connectors.match(/<circle /g)||[]).length,8);
const packingTest={id:'packing',x:0,y:0,item:{quantity:6,length:100,width:40,height:20,weight:200}};
assert.equal(canvas.packingRows(packingTest).length,1);
assert.equal(canvas.packingRows(packingTest)[0].weight,1200);
assert.match(canvas.packingCard(packingTest),/不分包（默认）/);
assert.match(canvas.packingCard(packingTest),/全部运费汇总到成本计算/);
packingTest.packing={mode:'equal',perPack:2};assert.deepEqual(canvas.packingRows(packingTest).map(r=>r.quantity),[2,2,2]);
packingTest.packing.perPack=4;assert.deepEqual(canvas.packingRows(packingTest).map(r=>r.quantity),[4,2]);
packingTest.packing={mode:'custom',rows:[{quantity:3,weight:650},{quantity:2,weight:430}]};
assert.match(canvas.packingCard(packingTest),/数量不一致/);
packingTest.item.weight=343;assert.equal(canvas.setPackageQuantity(packingTest,0,4),true);assert.equal(packingTest.packing.rows[0].weight,1372);
assert.equal(canvas.setPackageQuantity(packingTest,0,0),false);assert.equal(packingTest.packing.rows[0].quantity,4);
console.log('PASS: packing preview defaults to no split, equal remainder, custom quantity validation warning');
console.log('PASS: margin pricing, null commission rejection, FBP/RFBS selection, step-by-step cost card');
const fees=ozfcCost(8.79,62.3,35,12,{acquisition:2,withdrawal:2,returns:15*.07952,lastmile:0});
assert.equal(fees.price,147.52);
assert.ok(fees.actualMargin>=35);
assert.ok(ozfcCost(1,1,95,2,{acquisition:2,withdrawal:2}).error);
assert.ok(ozfcCost(1,1,35,12,{returns:NaN}).error);
assert.deepEqual(canvas.feeParams(),{margin:35,acquisition:2,withdrawal:2,returns:15,lastmile:0,advertising:0});
assert.doesNotMatch(canvas.metaHTML(costNode),/Ozon 后台定价/);
assert.match(canvas.priceHTML(costNode),/Ozon 后台售价/);
console.log('PASS: fee switches defaults, RUB reserves, percentage fees, price placement');
assert.equal(canvas.shippingItem(costNode).value,78);
costNode.item.value=5.1;assert.equal(canvas.shippingItem(costNode).value,78);
assert.match(canvas.costCard(costNode,freight),/fc-sale-card/);
assert.match(canvas.costCard(costNode,freight),/退货费用换算/);
canvas.c.advertising_enabled=true;canvas.c.advertising_cny=10;
assert.equal(canvas.feeParams().advertising,10);
assert.equal(ozfcCost(10,10,0,0,{advertising:10}).price,30);
costNode.commissionOverride=19;
assert.match(canvas.costCard(costNode,freight),/data-edit-key="commission" value="19"/);
assert.match(canvas.costCard(costNode,freight),/恢复API原始佣金/);
assert.match(canvas.costCard(costNode,freight),/利润率35%/);
assert.doesNotThrow(()=>canvas.validateFees({advertising_cny:'',advertising_enabled:false}));
assert.throws(()=>canvas.validateFees({advertising_cny:-1}));
costNode.costEdited=true;costNode.item.value=800;
assert.match(canvas.costCard(costNode,freight),/¥800.00/);
const state={nodes:[costNode]};
canvas.prepare(state,canvas.c);assert.equal(costNode.item.value,800);
assert.equal(canvas.shippingItem(costNode).value,78);
canvas.c.lastmile_enabled=false;canvas.c.lastmile_rub=500;
canvas.c.advertising_enabled=false;canvas.c.advertising_cny=99;
let visible=canvas.costCard(costNode,freight);
assert.doesNotMatch(visible,/最后一公里换算|人民币固定费用|广告费 ¥/);
canvas.c.advertising_enabled=true;canvas.c.advertising_cny=0;
assert.doesNotMatch(canvas.costCard(costNode,freight),/人民币固定费用|广告费 ¥/);
canvas.c.returns_enabled=false;canvas.c.acquisition_enabled=false;canvas.c.withdrawal_pct=0;
visible=canvas.costCard(costNode,freight);
assert.doesNotMatch(visible,/退货费用换算|收单费校验|提现费校验/);
const oldRoot=canvas.root,oldLines=canvas.drawLines;
const moved={id:'move',x:40,y:50,quote:{x:500,y:100},cost:{x:1100,y:150},sale:{x:1600,y:200}};
const styles=[{},{},{},{}];
canvas.root={querySelectorAll:()=>[{}, {q:'1'},{cost:'1'},{sale:'1'}].map((dataset,i)=>({dataset,closest:()=>({style:styles[i]})}))};
canvas.drawLines=()=>{};
canvas.positionCards(moved);
assert.deepEqual(styles,[{left:'40px',top:'50px'},{left:'500px',top:'100px'},{left:'1100px',top:'150px'},{left:'1600px',top:'200px'}]);
canvas.root=oldRoot;canvas.drawLines=oldLines;
assert.match(canvas.dragZones(),/data-drag-zone="single"/);
assert.match(canvas.dragZones(),/data-drag-zone="group"/);
canvas.s.displayMode='table';assert.equal(canvas.isTable(),true);
canvas.s.displayMode='canvas';assert.equal(canvas.isTable(),false);
const listeners={},stageListeners={};
const dragCanvas=Object.create(OzFreightCanvas.prototype);
dragCanvas.s={nodes:[{id:'drag',x:10,y:20,item:{quantity:1}}],view:{x:0,y:0,z:2}};
dragCanvas.root={addEventListener:()=>{}};
dragCanvas.stage={addEventListener:(name,fn)=>stageListeners[name]=fn,classList:{add:()=>{},remove:()=>{}}};
dragCanvas.snap=()=>{};dragCanvas.positionCards=()=>{};dragCanvas.change=()=>{};
global.window={addEventListener:(name,fn)=>listeners[name]=fn,removeEventListener:()=>{},getSelection:()=>({removeAllRanges:()=>{}})};
dragCanvas.bind();
function drag(zoneType,kind){
 const header={dataset:{n:'drag',...(kind==='quote'?{q:'1'}:kind==='cost'?{cost:'1'}:kind==='sale'?{sale:'1'}:{})}};
 const card={querySelector:()=>header};
 stageListeners.pointerdown({button:0,clientX:0,clientY:0,target:{closest:selector=>selector==='[data-drag-zone]'?{dataset:{dragZone:zoneType}}:selector==='.fc-card'?card:null}});
 listeners.pointermove({clientX:20,clientY:40});listeners.pointerup();
}
drag('single','item');
assert.deepEqual({x:dragCanvas.s.nodes[0].x,y:dragCanvas.s.nodes[0].y},{x:20,y:40});
assert.deepEqual(dragCanvas.s.nodes[0].quote,{x:750,y:20});
const before=JSON.parse(JSON.stringify(dragCanvas.s.nodes[0]));
drag('group','sale');
assert.equal(dragCanvas.s.nodes[0].x,before.x+10);
for(const key of ['quote','cost','sale'])assert.deepEqual(dragCanvas.s.nodes[0][key],{x:before[key].x+10,y:before[key].y+20});
let briefHTML='';
global.frappe={ui:{Dialog:class{constructor(){this.$wrapper={addClass:()=>{}};this.fields_dict={brief:{$wrapper:[{set innerHTML(v){briefHTML=v;},addEventListener:()=>{}}]}};}show(){}}}};
canvas.brief();
assert.match(briefHTML,/物料/);assert.match(briefHTML,/建议售价/);assert.match(briefHTML,/data-copy-logistics/);
delete global.frappe;delete global.window;
console.log('PASS: single/group drag regions, table mode, four-column summary dialog');
const selectedCanvas=Object.create(OzFreightCanvas.prototype);
selectedCanvas.s={nodes:[],displayMode:'table'};
selectedCanvas.c={cny_per_rub:.07952,routes:[{...route,id:'cheap',provider:'LOW',name:'cheap',fixed:1},{...route,id:'selected',provider:'PICKED',name:'selected',fixed:20}]};
selectedCanvas.costCard=()=>'';selectedCanvas.logisticsQueries={};
selectedCanvas.c.routes.forEach(r=>r.speed='Standard');
const chosenNode={id:'chosen',x:0,y:0,item:{length:100,width:100,height:100,weight:100,value:5,value_currency:'CNY'},costRoute:'selected',meta:{prices:[{currency:'RUB',amount:100,cny:7.952}]}};
const html=selectedCanvas.quotes(chosenNode);
const listing=html.slice(html.indexOf('data-logistics-list'));
assert.ok(listing.indexOf('PICKED')<listing.indexOf('LOW'));
assert.equal((listing.match(/ open class=/g)||[]).length,2);
let first={scrollLeft:0},second={scrollLeft:0};
selectedCanvas.tableScroll=123;selectedCanvas.root={querySelectorAll:()=>[first,second]};
selectedCanvas.restoreTableScroll();assert.equal(first.scrollLeft,123);assert.equal(second.scrollLeft,123);
console.log('PASS: selected shipping pinned, full rules in table, synchronized scroll restoration');
const blankCanvas=Object.create(OzFreightCanvas.prototype);
blankCanvas.s={nodes:[],exclusive:true,expanded:[],view:{x:0,y:0,z:1}};
blankCanvas.c={cny_per_rub:.07952,margin_pct:35,routes:[{...route,provider:'TEST',name:'test',speed:'Standard'}]};
blankCanvas.snap=()=>{};blankCanvas.change=()=>{};blankCanvas.paint=()=>{};
blankCanvas.addBlank();
const blank=blankCanvas.s.nodes[0];assert.equal(blank.manual,true);
Object.assign(blank.item,{length:100,width:100,height:100,weight:100,value:8});
blank.manualSale=100;blank.commissionOverride=12;
assert.equal(blankCanvas.shippingItem(blank).value,100);
assert.equal(blankCanvas.estimate(blank).x.cost,8);
assert.ok(!blankCanvas.estimate(blank).x.error);
assert.match(blankCanvas.priceHTML(blank),/data-manual-sale/);
assert.match(blankCanvas.costCard(blank,[{eligible:true,r:{provider:'TEST',name:'test'},price:10}]),/商品售价/);
assert.match(blankCanvas.metaHTML(blank),/不会新建ERPNext物料/);
blankCanvas.api=()=>{throw Error('Must not query Ozon or Item for blank material');};
blankCanvas.enrich(blank.id);
blankCanvas.refresh(blank.id);
console.log('PASS: blank material estimates, manual sale/commission, no backend item lookup');
const independent={id:'independent',x:0,y:0,item:{value:10,value_currency:'CNY'},meta:{prices:[{currency:'CNY',amount:78,cny:78,commissions:[{schema:'RFBS',percent:12}]}]},saleOverride:99,fees:{margin_pct:20,acquisition_enabled:false,returns_enabled:false,advertising_enabled:false}};
assert.equal(canvas.product(independent).cny,99);
assert.equal(canvas.product(independent,true).cny,78);
assert.equal(canvas.shippingItem(independent).value,99);
assert.equal(canvas.feeParams(independent).margin,20);
assert.equal(canvas.feeParams(independent).acquisition,0);
assert.equal(canvas.feeParams(independent).returns,0);
assert.equal(canvas.feeParams().margin,35);
assert.doesNotMatch(canvas.priceHTML(independent),/≈ ¥/);
assert.ok(canvas.costCard(independent,freight).indexOf('fc-calculation-pane')<canvas.costCard(independent,freight).indexOf('fc-cost-summary'));
canvas.s.nodes=[independent];canvas.paint=()=>{};canvas.restoreTableScroll=()=>{};canvas.root={querySelector:()=>({focus(){}})};
canvas.liveEdit({dataset:{editNode:'independent',editKey:'cost'},value:'12.34'});
assert.equal(independent.item.value,'12.34');
canvas.liveEdit({dataset:{n:'independent',f:'value'},value:'17.25'});
assert.equal(independent.item.value,'17.25');
canvas.liveEdit({dataset:{editNode:'independent',editKey:'commission'},value:'18'});
assert.equal(independent.commissionOverride,18);
console.log('PASS: per-material fees, sale override/raw restore, live bidirectional cost model, editable commission');
const post={...route,id:'postal',fixed:12,rate:30,min_weight:.001,max_weight:5,min_value:0,max_value:1000,value_currency:'CNY',divisor:0,max_side:60,max_sum:90};
const parcel={length:100,width:100,height:100,weight:500,value:1000,value_currency:'CNY'};
assert.equal(ozfcCalculate(parcel,post,.08).price,27);
assert.equal(ozfcCalculate(parcel,post,.08).eligible,true);
assert.equal(ozfcCalculate({...parcel,value:1001},post,.08).eligible,false);
assert.equal(ozfcCalculate({...parcel,value:12500,value_currency:'RUB'},post,.08).eligible,true);
assert.equal(ozfcCalculate({...parcel,value:12501,value_currency:'RUB'},post,.08).eligible,false);
assert.equal(ozfcCalculate({...parcel,value:100,value_currency:'RUB'},post,0).eligible,false);
const zoomCanvas=Object.create(OzFreightCanvas.prototype);zoomCanvas.s={nodes:[],view:{x:0,y:0,z:1}};
zoomCanvas.stage={getBoundingClientRect:()=>({left:0,top:0,width:1000,height:800})};zoomCanvas.transform=()=>{};zoomCanvas.change=()=>{};
zoomCanvas.zoom(.001);assert.equal(zoomCanvas.s.view.z,.05);zoomCanvas.zoom(100);assert.equal(zoomCanvas.s.view.z,5);
assert.doesNotThrow(()=>zoomCanvas.validateCanvas(zoomCanvas.s));
const mergeCanvas=Object.create(OzFreightCanvas.prototype);mergeCanvas.bootData={defaults:{routes:[{id:'兴远-Post-ePacket',provider:'兴远',name:'ePacket',destination:'俄罗斯'}]}};
const saved={routes:[],margin_pct:35,cny_per_rub:.08},mergeState={nodes:[],expanded:[],exclusive:true};
mergeCanvas.prepare(mergeState,saved);mergeCanvas.prepare(mergeState,saved);assert.equal(saved.routes.length,1);
console.log('PASS: CNY postal limits and per-gram rates, 5%-500% zoom, one-time non-destructive lane merge');
const previousDocument=global.document,created=[];
try{
 global.document={createElement:()=>({style:{},offsetWidth:440,offsetHeight:500}),createElementNS:()=>({classList:{add(){}},attributes:{},children:[],setAttribute(k,v){this.attributes[k]=v;},append(x){this.children.push(x);}})};
 const imageCanvas=Object.create(OzFreightCanvas.prototype);
 imageCanvas.s={nodes:[{id:'pic',x:200,y:100,item:{item_name:'图片',image:'/files/example.png'}}]};imageCanvas.imageNode='pic';
 imageCanvas.stage={querySelector:()=>null,getBoundingClientRect:()=>({left:0,top:0})};
 imageCanvas.root={querySelector:()=>({getBoundingClientRect:()=>({left:200,top:100})})};
 imageCanvas.world={append(x){created.push(x);}};
 imageCanvas.imageCard();
 assert.equal(created[0].style.left,'-270px');assert.equal(created[0].style.top,'100px');
 assert.match(created[0].innerHTML,/data-close-image/);assert.equal(created[1].children[0].attributes.stroke,'#94a7e6');
 assert.match(created[1].children[0].attributes.d,/200 200/);
}finally{global.document=previousDocument;}
console.log('PASS: full-image card anchored left in canvas coordinates with connecting line');
let restoredCaret=null,focused=false;
canvas.s.nodes=[independent];canvas.root={querySelector:()=>({focus(){focused=true;},setSelectionRange(a,b,d){restoredCaret=[a,b,d];}})};
canvas.liveEdit({dataset:{editNode:'independent',editKey:'cost'},value:'123.45',selectionStart:2,selectionEnd:2,selectionDirection:'none'});
assert.equal(independent.item.value,'123.45');assert.equal(focused,false);assert.equal(restoredCaret,null);
canvas.c.acquisition_pct=9;canvas.c.acquisition_enabled=false;canvas.resetFee('acquisition');
assert.equal(canvas.c.acquisition_pct,2);assert.equal(canvas.c.acquisition_enabled,false);
canvas.c.returns_rub=50;canvas.resetFee('returns');assert.equal(canvas.c.returns_rub,15);
canvas.c.lastmile_rub=100;canvas.c.lastmile_enabled=false;canvas.resetFee('lastmile');
assert.equal(canvas.c.lastmile_rub,500);assert.equal(canvas.c.lastmile_enabled,false);
canvas.c.withdrawal_pct=9;canvas.resetFee('withdrawal');assert.equal(canvas.c.withdrawal_pct,2);
assert.equal((canvas.feeControls().match(/data-reset-fee=/g)||[]).length,4);
canvas.c.acquisition_enabled=true;canvas.c.returns_enabled=true;canvas.c.withdrawal_enabled=true;
costNode.fees={};
const checks=canvas.costCard(costNode,freight);
assert.match(checks,/② 退货费用换算/);
assert.ok(checks.indexOf('② 退货费用换算')<checks.indexOf('② 加上物流运费'));
assert.match(checks,/fc-step-check"><small>⑤ 收单费校验/);
assert.match(checks,/fc-step-check"><small>⑤ 提现费校验/);
assert.match(checks,/fc-step-profit"><small>⑥ 利润校验/);
console.log('PASS: input retains focus/caret without replacement, four reset defaults, reordered verification steps');
const perfCanvas=Object.create(OzFreightCanvas.prototype);
perfCanvas.s={nodes:[{id:'fast',item:{value:1,quantity:1}}]};perfCanvas.root={querySelectorAll:()=>[]};
perfCanvas.snap=()=>{};perfCanvas.change=()=>{};perfCanvas.paint=()=>{throw new Error('Typing must not repaint the canvas');};
let scheduled=[];perfCanvas.queueMaterialCalculation=(id,shipping)=>scheduled.push([id,shipping]);
assert.equal(perfCanvas.liveEdit({dataset:{n:'fast',f:'quantity'},value:'3'}),true);
assert.equal(perfCanvas.s.nodes[0].item.quantity,3);
perfCanvas.liveEdit({dataset:{n:'fast',f:'weight'},value:'343'});
assert.equal(perfCanvas.s.nodes[0].item.weight,'343');
assert.deepEqual(scheduled,[['fast',true],['fast',true]]);
const nativeTimeout=global.setTimeout,nativeClearTimeout=global.clearTimeout;
try{
 const callbacks=new Map();let timerId=0,updates=[];
 global.setTimeout=(fn,delay)=>{assert.equal(delay,180);callbacks.set(++timerId,fn);return timerId;};
 global.clearTimeout=id=>callbacks.delete(id);
 delete perfCanvas.queueMaterialCalculation;
 perfCanvas.updateMaterialCalculation=(id,shipping)=>updates.push([id,shipping]);
 perfCanvas.queueMaterialCalculation('fast',true);perfCanvas.queueMaterialCalculation('fast',false);
 assert.equal(callbacks.size,1);[...callbacks.values()][0]();
 assert.deepEqual(updates,[['fast',true]]);assert.equal(perfCanvas.pendingCalculations.size,0);
}finally{global.setTimeout=nativeTimeout;global.clearTimeout=nativeClearTimeout;}
console.log('PASS: typing updates model immediately without full paint, merged 180ms calculation preserves shipping refresh');
const hoverDocument=global.document,hoverWindow=global.window;
try{
 const listeners={},shown=[];
 global.window={innerWidth:1000,innerHeight:900};
 global.document={body:{append(x){shown.push(x);}},createElement:()=>({style:{},offsetWidth:560,offsetHeight:560,children:[],append(x){this.children.push(x);},remove(){this.removed=true;}})};
 const hoverCanvas=Object.create(OzFreightCanvas.prototype);
 hoverCanvas.bindImageHover({addEventListener(k,fn){listeners[k]=fn;}},'img');
 const img={src:'/files/thumbnail.png',currentSrc:'/files/original.png',contains:()=>false,getBoundingClientRect:()=>({right:100,left:20,top:50})};
 listeners.mouseover({target:{closest:()=>img}});
 assert.equal(shown.length,1);assert.equal(shown[0].children[0].src,'/files/original.png');
 assert.equal(shown[0].style.left,'116px');assert.equal(shown[0].style.top,'50px');
 listeners.scroll();assert.equal(shown[0].removed,true);assert.equal(hoverCanvas.hoverImage,null);
 assert.match(canvas.costCard(costNode,freight),/fc-pricing-note/);
}finally{global.document=hoverDocument;global.window=hoverWindow;}
console.log('PASS: original image hover uses top-level preview, viewport positioning, scroll cleanup, expandable pricing notes');
const redCanvas=Object.create(OzFreightCanvas.prototype);redCanvas.c={margin_pct:35,acquisition_pct:2,withdrawal_pct:2,returns_rub:15,lastmile_rub:500,lastmile_enabled:false,advertising_cny:'',advertising_enabled:false};
const redNode={id:'red',fees:{margin_pct:28,acquisition_pct:2,returns_enabled:false}};
assert.equal(redCanvas.feeDiff(redNode,'margin'),true);
assert.equal(redCanvas.feeDiff(redNode,'acquisition'),false);
assert.equal(redCanvas.feeDiff(redNode,'returns'),true);
assert.equal((redCanvas.nodeFees(redNode).match(/class="fc-override-dot"/g)||[]).length,2);
redNode.fees.margin_pct='35.00';assert.equal(redCanvas.feeDiff(redNode,'margin'),false);
redNode.fees.returns_enabled=true;assert.equal(redCanvas.feeDot(redNode,'returns'),'');
redCanvas.c.margin_pct=40;assert.equal(redCanvas.feeDiff(redNode,'margin'),true);
assert.equal(redCanvas.feeDiff({id:'normal'},'margin'),false);
assert.equal(redCanvas.feeDiff({fees:{advertising_cny:0}},'advertising'),false);
console.log('PASS: override red dots compare shared values and switches, normalize numeric strings, disappear on equality');
const identifierNode={id:'ident',item:{weight:100},meta:{prices:[{store:'店铺A',ozon_sku_ids:['5486534298'],offer_id:'MANG-SHOVEL-T-HEAD'},{store:'店铺B',ozon_sku_ids:['123','456'],offer_id:'货号<&'}]}};
const identifierHTML=canvas.ozonIdentifiers(identifierNode);
assert.match(identifierHTML,/data-copy-item="5486534298"/);
assert.match(identifierHTML,/data-copy-item="MANG-SHOVEL-T-HEAD"/);
assert.match(identifierHTML,/货号&lt;&amp;/);
assert.match(identifierHTML,/店铺B/);
assert.equal((identifierHTML.match(/class="fc-copy-ozon"/g)||[]).length,5);
assert.equal(canvas.ozonIdentifiers({manual:true}),'');
assert.match(canvas.ozonIdentifiers({id:'old',meta:{prices:[{offer_id:'real-offer',sku:'not-real-sku'}]}}),/查询标识/);
assert.doesNotMatch(canvas.ozonIdentifiers({id:'old',meta:{prices:[{offer_id:'real-offer',sku:'not-real-sku'}]}}),/data-copy-item="not-real-sku"/);
console.log('PASS: separate Ozon SKU/offer copy targets, multiple stores and SKUs, safe escaping, missing identifier query');
