/* Run: node test_calculator.js */
// Async regression: refresh uses store/product identity and preserves user estimates.
(async()=>{
 const {OzFreightCanvas}=require('./ozon_freight_calcula.js');
 const assert=require('node:assert/strict');
 global.crypto ||= require('node:crypto').webcrypto;
 const c=Object.create(OzFreightCanvas.prototype);
 const user={id:'user-1',item:{item_code:'item-1',value:88},x:0,y:0,meta:{costs:[],prices:[],errors:[]}};
 c.s={nodes:[user]};c.snap=c.change=c.paint=c.status=()=>{};
 const product={store:'store-1',product_id:'6166309025',ozon_sku_ids:['5647274301'],offer_id:'offer-1',name:'商品',image:'/image.png',amount:10,currency:'CNY',commissions:[],item:{item_code:'item-1',item_name:'物料'}};
 c.api=async(method,args)=>!args?.store?{stores:['store-1']}:{products:[product,{...product,product_id:'other-id',ozon_sku_ids:['other-sku'],item:null}],more:false};
 await c.refreshSkus();assert.equal(c.s.nodes.length,2);assert.equal(user.item.value,88);assert.equal(user.meta.prices[0].product_id,'6166309025');
 const auto=c.s.nodes[1];assert.equal(auto.ozonOnly,true);assert.equal(auto.item.image,'/image.png');assert.ok(auto.x>user.x+330);
 await c.refreshSkus();assert.equal(c.s.nodes.length,2);assert.equal(c.s.nodes[0],user);assert.equal(user.item.value,88);assert.equal(c.skuRefreshing,false);
 c.api=async()=>{throw Error('network')};await assert.rejects(()=>c.refreshSkus());assert.equal(c.skuRefreshing,false);
 console.log('PASS: SKU refresh pagination merge, user cost preservation, unbound Ozon images, no duplicates, failure unlock');
})().catch(e=>{console.error(e);process.exitCode=1;});
const assert = require('node:assert/strict');
const {ozfcCalculate: calc, ozfcCost, OzFreightCanvas} = require('./ozon_freight_calcula.js');
const ozfcCalculate = calc;
const route={fixed:3.37,rate:39.3,min_weight:.001,max_weight:.5,min_value:1,max_value:1500,max_side:60,max_sum:90,divisor:0,step:0,battery:true,liquid:false};
const item={length:100,width:200,height:100,weight:100,value:1500};
assert.equal(calc(item,route).price,7.30);
assert.equal(calc(item,route).eligible,true);
assert.equal(calc({...item,weight:500},route).eligible,true);
assert.equal(calc({...item,weight:501},route).eligible,false);
assert.equal(calc({...item,value:1501},route).eligible,false);
assert.equal(calc({...item,length:610},route).eligible,false);
assert.equal(calc({...item,value:''},route).eligible,false);
assert.equal(calc({...item,weight:'abc'},route).eligible,false);
assert.equal(calc({...item,liquid:true},route).eligible,false);
assert.equal(calc({...item,battery:true},{...route,battery:false}).eligible,false);
const big={...route,fixed:40.44,rate:28.1,min_weight:2,min_exclusive:true,max_weight:30,min_value:1500,value_exclusive:true,max_value:7000,max_side:150,max_sum:310,divisor:12000,max_billable:31};
const box={...item,length:600,width:400,height:300,weight:3000,value:2000};
assert.equal(calc(box,big).bill,6);
assert.equal(calc(box,big).price,209.04);
assert.equal(calc({...box,weight:2000},big).eligible,false);
assert.equal(calc({...box,length:1500,width:1000,height:1000},big).eligible,false);
assert.equal(calc({...item,weight:101},{...route,step:.05}).bill.toFixed(2),'0.15');
assert.equal(calc({...box,length:1000,width:900,height:100},{...big,sorted_sides:[150,80,80]}).eligible,false);
assert.equal(calc(item,route).steps.length,5);
assert.equal(calc({...item,value_currency:'CNY',value:119.28},route,.07952).eligible,true);
assert.equal(calc({...item,value_currency:'CNY',value:120},route,.07952).eligible,false);
assert.equal(calc({...item,value_currency:'CNY'},route,0).eligible,false);
assert.equal(calc({...item,value_currency:'CNY',weight:.343,value:800},route,.07952).eligible,false);
const premium={...route,fixed:24.71,rate:28.1,max_weight:5,min_value:7000,value_exclusive:true,max_value:250000,max_side:150,max_sum:250};
const corrected=calc({...item,value_currency:'CNY',length:210,width:190,height:50,weight:343,value:800},premium,.07952);
assert.equal(corrected.eligible,true);
assert.equal(corrected.price,34.35);
const canvas=Object.create(OzFreightCanvas.prototype);
canvas.s={nodes:[],expanded:[],active:null,exclusive:true};
canvas.snap=()=>{};canvas.change=()=>{};canvas.paint=()=>{};
canvas.activate('a');canvas.activate('b');assert.deepEqual(canvas.expanded(),['b']);
canvas.s.exclusive=false;canvas.activate('a');assert.deepEqual(canvas.expanded(),['b','a']);
canvas.activate('b');assert.deepEqual(canvas.expanded(),['a']);
canvas.activate('a');assert.deepEqual(canvas.expanded(),[]);
canvas.bootData={exchange:{cny_per_rub:.07952,date:'2026-09-16'}};
const legacy={nodes:[{item:{value:1500}}],active:'a'},config={routes:[]};
assert.equal(canvas.prepare(legacy,config),true);
assert.equal(legacy.nodes[0].item.value_currency,'CNY');
assert.equal(legacy.nodes[0].item.value,'119.28');
const meta=canvas.metaHTML({id:'a',item:{weight:343},meta:{costs:[{amount:5.1,currency:'CNY',source:'库存成本'}],prices:[]}});
assert.match(meta,/5\.10/);assert.match(meta,/只读/);
console.log('PASS: calculator, CNY conversion, stock-weight regression, multi-card switch, old-canvas migration, read-only cost');
const example=ozfcCost(8.79,62.3,28,18);
assert.equal(example.total,71.09);
assert.equal(example.price,131.65);
assert.ok(example.actualMargin>=28);
assert.equal(ozfcCost(8.79,62.3,35,18).price,151.26);
assert.ok(ozfcCost(8.79,62.3,35,null).error);
assert.ok(ozfcCost(null,62.3,35,18).error);
assert.ok(ozfcCost(8.79,null,35,18).error);
assert.ok(ozfcCost(8.79,62.3,85,18).error);
assert.equal(ozfcCost(8.79,62.3,0,0).price,71.09);
canvas.c={margin_pct:35,cny_per_rub:.07952};canvas.s.nodes=[];
const costNode={id:'a',item:{},meta:{costs:[{amount:8.79,currency:'CNY'}],prices:[{store:'店铺',sku:'SKU',commissions:[{schema:'FBP',percent:11},{schema:'RFBS',percent:12}]}]},x:0,y:0};
const freight=[{eligible:true,r:{id:'route',provider:'CEL',name:'Economy',mode:'FBP'},price:62.3}];
assert.match(canvas.costCard(costNode,freight),/11%/);
assert.match(canvas.costCard(costNode,freight),/data-cost="1"/);
assert.match(canvas.costCard(costNode,freight),/⑥ 利润校验/);
costNode.commissionSchema='RFBS';assert.match(canvas.costCard(costNode,freight),/12%/);
canvas.c.routes=[{...route,id:'route',provider:'CEL',name:'Economy',mode:'FBP'}];canvas.c.cny_per_rub=.07952;
costNode.item={length:210,width:190,height:50,weight:343,value:78,value_currency:'CNY'};
Object.assign(costNode.meta.prices[0],{amount:78,cny:78,currency:'CNY'});
assert.match(canvas.quotes(costNode),/fc-cost-card/);
assert.match(canvas.quotes(costNode),/用此运费计算售价/);
canvas.s.nodes=[costNode];canvas.s.expanded=['a'];let connectors='';
canvas.root={querySelector:()=>({set innerHTML(s){connectors=s;}})};
canvas.drawLines();assert.equal((connectors.match(/<path /g)||[]).length,3);
console.log('PASS: margin pricing, null commission rejection, FBP/RFBS selection, step-by-step cost card');
const fees=ozfcCost(8.79,62.3,35,12,{acquisition:2,withdrawal:2,returns:15*.07952,lastmile:0});
assert.equal(fees.price,147.52);
assert.ok(fees.actualMargin>=35);
assert.ok(ozfcCost(1,1,95,2,{acquisition:2,withdrawal:2}).error);
assert.ok(ozfcCost(1,1,35,12,{returns:NaN}).error);
assert.deepEqual(canvas.feeParams(),{margin:35,acquisition:2,withdrawal:2,returns:15,lastmile:0,advertising:0});
assert.doesNotMatch(canvas.metaHTML(costNode),/Ozon 后台定价/);
assert.match(canvas.priceHTML(costNode),/Ozon 后台售价/);
console.log('PASS: fee switches defaults, RUB reserves, percentage fees, price placement');
assert.equal(canvas.shippingItem(costNode).value,78);
costNode.item.value=5.1;assert.equal(canvas.shippingItem(costNode).value,78);
assert.match(canvas.costCard(costNode,freight),/fc-sale-card/);
assert.match(canvas.costCard(costNode,freight),/退货费用换算/);
canvas.c.advertising_enabled=true;canvas.c.advertising_cny=10;
assert.equal(canvas.feeParams().advertising,10);
assert.equal(ozfcCost(10,10,0,0,{advertising:10}).price,30);
costNode.commissionOverride=19;
assert.match(canvas.costCard(costNode,freight),/data-edit-key="commission" value="19"/);
assert.match(canvas.costCard(costNode,freight),/恢复API原始佣金/);
assert.match(canvas.costCard(costNode,freight),/利润率35%/);
assert.doesNotThrow(()=>canvas.validateFees({advertising_cny:'',advertising_enabled:false}));
assert.throws(()=>canvas.validateFees({advertising_cny:-1}));
costNode.costEdited=true;costNode.item.value=800;
assert.match(canvas.costCard(costNode,freight),/¥800.00/);
const state={nodes:[costNode]};
canvas.prepare(state,canvas.c);assert.equal(costNode.item.value,800);
assert.equal(canvas.shippingItem(costNode).value,78);
canvas.c.lastmile_enabled=false;canvas.c.lastmile_rub=500;
canvas.c.advertising_enabled=false;canvas.c.advertising_cny=99;
let visible=canvas.costCard(costNode,freight);
assert.doesNotMatch(visible,/最后一公里换算|人民币固定费用|广告费 ¥/);
canvas.c.advertising_enabled=true;canvas.c.advertising_cny=0;
assert.doesNotMatch(canvas.costCard(costNode,freight),/人民币固定费用|广告费 ¥/);
canvas.c.returns_enabled=false;canvas.c.acquisition_enabled=false;canvas.c.withdrawal_pct=0;
visible=canvas.costCard(costNode,freight);
assert.doesNotMatch(visible,/退货费用换算|收单费校验|提现费校验/);
const oldRoot=canvas.root,oldLines=canvas.drawLines;
const moved={id:'move',x:40,y:50,quote:{x:500,y:100},cost:{x:1100,y:150},sale:{x:1600,y:200}};
const styles=[{},{},{},{}];
canvas.root={querySelectorAll:()=>[{}, {q:'1'},{cost:'1'},{sale:'1'}].map((dataset,i)=>({dataset,closest:()=>({style:styles[i]})}))};
canvas.drawLines=()=>{};
canvas.positionCards(moved);
assert.deepEqual(styles,[{left:'40px',top:'50px'},{left:'500px',top:'100px'},{left:'1100px',top:'150px'},{left:'1600px',top:'200px'}]);
canvas.root=oldRoot;canvas.drawLines=oldLines;
assert.match(canvas.dragZones(),/data-drag-zone="single"/);
assert.match(canvas.dragZones(),/data-drag-zone="group"/);
canvas.s.displayMode='table';assert.equal(canvas.isTable(),true);
canvas.s.displayMode='canvas';assert.equal(canvas.isTable(),false);
const listeners={},stageListeners={};
const dragCanvas=Object.create(OzFreightCanvas.prototype);
dragCanvas.s={nodes:[{id:'drag',x:10,y:20}],view:{x:0,y:0,z:2}};
dragCanvas.root={addEventListener:()=>{}};
dragCanvas.stage={addEventListener:(name,fn)=>stageListeners[name]=fn,classList:{add:()=>{},remove:()=>{}}};
dragCanvas.snap=()=>{};dragCanvas.positionCards=()=>{};dragCanvas.change=()=>{};
global.window={addEventListener:(name,fn)=>listeners[name]=fn,removeEventListener:()=>{},getSelection:()=>({removeAllRanges:()=>{}})};
dragCanvas.bind();
function drag(zoneType,kind){
 const header={dataset:{n:'drag',...(kind==='quote'?{q:'1'}:kind==='cost'?{cost:'1'}:kind==='sale'?{sale:'1'}:{})}};
 const card={querySelector:()=>header};
 stageListeners.pointerdown({button:0,clientX:0,clientY:0,target:{closest:selector=>selector==='[data-drag-zone]'?{dataset:{dragZone:zoneType}}:selector==='.fc-card'?card:null}});
 listeners.pointermove({clientX:20,clientY:40});listeners.pointerup();
}
drag('single','item');
assert.deepEqual({x:dragCanvas.s.nodes[0].x,y:dragCanvas.s.nodes[0].y},{x:20,y:40});
assert.deepEqual(dragCanvas.s.nodes[0].quote,{x:380,y:20});
const before=JSON.parse(JSON.stringify(dragCanvas.s.nodes[0]));
drag('group','sale');
assert.equal(dragCanvas.s.nodes[0].x,before.x+10);
for(const key of ['quote','cost','sale'])assert.deepEqual(dragCanvas.s.nodes[0][key],{x:before[key].x+10,y:before[key].y+20});
let briefHTML='';
global.frappe={ui:{Dialog:class{constructor(){this.$wrapper={addClass:()=>{}};this.fields_dict={brief:{$wrapper:[{set innerHTML(v){briefHTML=v;},addEventListener:()=>{}}]}};}show(){}}}};
canvas.brief();
assert.match(briefHTML,/物料/);assert.match(briefHTML,/建议售价/);assert.match(briefHTML,/data-copy-logistics/);
delete global.frappe;delete global.window;
console.log('PASS: single/group drag regions, table mode, four-column summary dialog');
const selectedCanvas=Object.create(OzFreightCanvas.prototype);
selectedCanvas.s={nodes:[],displayMode:'table'};
selectedCanvas.c={cny_per_rub:.07952,routes:[{...route,id:'cheap',provider:'LOW',name:'cheap',fixed:1},{...route,id:'selected',provider:'PICKED',name:'selected',fixed:20}]};
selectedCanvas.costCard=()=>'';selectedCanvas.logisticsQueries={};
const chosenNode={id:'chosen',x:0,y:0,item:{length:100,width:100,height:100,weight:100,value:5,value_currency:'CNY'},costRoute:'selected',meta:{prices:[{currency:'RUB',amount:100,cny:7.952}]}};
const html=selectedCanvas.quotes(chosenNode);
const listing=html.slice(html.indexOf('data-logistics-list'));
assert.ok(listing.indexOf('PICKED')<listing.indexOf('LOW'));
assert.equal((listing.match(/ open class=/g)||[]).length,2);
let first={scrollLeft:0},second={scrollLeft:0};
selectedCanvas.tableScroll=123;selectedCanvas.root={querySelectorAll:()=>[first,second]};
selectedCanvas.restoreTableScroll();assert.equal(first.scrollLeft,123);assert.equal(second.scrollLeft,123);
console.log('PASS: selected shipping pinned, full rules in table, synchronized scroll restoration');
const blankCanvas=Object.create(OzFreightCanvas.prototype);
blankCanvas.s={nodes:[],exclusive:true,expanded:[],view:{x:0,y:0,z:1}};
blankCanvas.c={cny_per_rub:.07952,margin_pct:35,routes:[{...route,provider:'TEST',name:'test'}]};
blankCanvas.snap=()=>{};blankCanvas.change=()=>{};blankCanvas.paint=()=>{};
blankCanvas.addBlank();
const blank=blankCanvas.s.nodes[0];assert.equal(blank.manual,true);
Object.assign(blank.item,{length:100,width:100,height:100,weight:100,value:8});
blank.manualSale=100;blank.commissionOverride=12;
assert.equal(blankCanvas.shippingItem(blank).value,100);
assert.equal(blankCanvas.estimate(blank).x.cost,8);
assert.ok(!blankCanvas.estimate(blank).x.error);
assert.match(blankCanvas.priceHTML(blank),/data-manual-sale/);
assert.match(blankCanvas.costCard(blank,[{eligible:true,r:{provider:'TEST',name:'test'},price:10}]),/商品售价/);
assert.match(blankCanvas.metaHTML(blank),/不会新建ERPNext物料/);
blankCanvas.api=()=>{throw Error('Must not query Ozon or Item for blank material');};
blankCanvas.enrich(blank.id);
blankCanvas.refresh(blank.id);
console.log('PASS: blank material estimates, manual sale/commission, no backend item lookup');
const independent={id:'independent',x:0,y:0,item:{value:10,value_currency:'CNY'},meta:{prices:[{currency:'CNY',amount:78,cny:78,commissions:[{schema:'RFBS',percent:12}]}]},saleOverride:99,fees:{margin_pct:20,acquisition_enabled:false,returns_enabled:false,advertising_enabled:false}};
assert.equal(canvas.product(independent).cny,99);
assert.equal(canvas.product(independent,true).cny,78);
assert.equal(canvas.shippingItem(independent).value,99);
assert.equal(canvas.feeParams(independent).margin,20);
assert.equal(canvas.feeParams(independent).acquisition,0);
assert.equal(canvas.feeParams(independent).returns,0);
assert.equal(canvas.feeParams().margin,35);
assert.doesNotMatch(canvas.priceHTML(independent),/≈ ¥/);
assert.ok(canvas.costCard(independent,freight).indexOf('fc-calculation-pane')<canvas.costCard(independent,freight).indexOf('fc-cost-summary'));
canvas.s.nodes=[independent];canvas.paint=()=>{};canvas.restoreTableScroll=()=>{};canvas.root={querySelector:()=>({focus(){}})};
canvas.liveEdit({dataset:{editNode:'independent',editKey:'cost'},value:'12.34'});
assert.equal(independent.item.value,'12.34');
canvas.liveEdit({dataset:{n:'independent',f:'value'},value:'17.25'});
assert.equal(independent.item.value,'17.25');
canvas.liveEdit({dataset:{editNode:'independent',editKey:'commission'},value:'18'});
assert.equal(independent.commissionOverride,18);
console.log('PASS: per-material fees, sale override/raw restore, live bidirectional cost model, editable commission');
const post={...route,id:'postal',fixed:12,rate:30,min_weight:.001,max_weight:5,min_value:0,max_value:1000,value_currency:'CNY',divisor:0,max_side:60,max_sum:90};
const parcel={length:100,width:100,height:100,weight:500,value:1000,value_currency:'CNY'};
assert.equal(ozfcCalculate(parcel,post,.08).price,27);
assert.equal(ozfcCalculate(parcel,post,.08).eligible,true);
assert.equal(ozfcCalculate({...parcel,value:1001},post,.08).eligible,false);
assert.equal(ozfcCalculate({...parcel,value:12500,value_currency:'RUB'},post,.08).eligible,true);
assert.equal(ozfcCalculate({...parcel,value:12501,value_currency:'RUB'},post,.08).eligible,false);
assert.equal(ozfcCalculate({...parcel,value:100,value_currency:'RUB'},post,0).eligible,false);
const zoomCanvas=Object.create(OzFreightCanvas.prototype);zoomCanvas.s={nodes:[],view:{x:0,y:0,z:1}};
zoomCanvas.stage={getBoundingClientRect:()=>({left:0,top:0,width:1000,height:800})};zoomCanvas.transform=()=>{};zoomCanvas.change=()=>{};
zoomCanvas.zoom(.001);assert.equal(zoomCanvas.s.view.z,.05);zoomCanvas.zoom(100);assert.equal(zoomCanvas.s.view.z,5);
assert.doesNotThrow(()=>zoomCanvas.validateCanvas(zoomCanvas.s));
const mergeCanvas=Object.create(OzFreightCanvas.prototype);mergeCanvas.bootData={defaults:{routes:[{id:'兴远-Post-ePacket',provider:'兴远',name:'ePacket',destination:'俄罗斯'}]}};
const saved={routes:[],margin_pct:35,cny_per_rub:.08},mergeState={nodes:[],expanded:[],exclusive:true};
mergeCanvas.prepare(mergeState,saved);mergeCanvas.prepare(mergeState,saved);assert.equal(saved.routes.length,1);
console.log('PASS: CNY postal limits and per-gram rates, 5%-500% zoom, one-time non-destructive lane merge');
const previousDocument=global.document,created=[];
try{
 global.document={createElement:()=>({style:{},offsetWidth:440,offsetHeight:500}),createElementNS:()=>({classList:{add(){}},attributes:{},children:[],setAttribute(k,v){this.attributes[k]=v;},append(x){this.children.push(x);}})};
 const imageCanvas=Object.create(OzFreightCanvas.prototype);
 imageCanvas.s={nodes:[{id:'pic',x:200,y:100,item:{item_name:'图片',image:'/files/example.png'}}]};imageCanvas.imageNode='pic';
 imageCanvas.stage={querySelector:()=>null,getBoundingClientRect:()=>({left:0,top:0})};
 imageCanvas.root={querySelector:()=>({getBoundingClientRect:()=>({left:200,top:100})})};
 imageCanvas.world={append(x){created.push(x);}};
 imageCanvas.imageCard();
 assert.equal(created[0].style.left,'-270px');assert.equal(created[0].style.top,'100px');
 assert.match(created[0].innerHTML,/data-close-image/);assert.equal(created[1].children[0].attributes.stroke,'#94a7e6');
 assert.match(created[1].children[0].attributes.d,/200 200/);
}finally{global.document=previousDocument;}
console.log('PASS: full-image card anchored left in canvas coordinates with connecting line');
let restoredCaret=null,focused=false;
canvas.s.nodes=[independent];canvas.root={querySelector:()=>({focus(){focused=true;},setSelectionRange(a,b,d){restoredCaret=[a,b,d];}})};
canvas.liveEdit({dataset:{editNode:'independent',editKey:'cost'},value:'123.45',selectionStart:2,selectionEnd:2,selectionDirection:'none'});
assert.equal(independent.item.value,'123.45');assert.equal(focused,true);assert.deepEqual(restoredCaret,[2,2,'none']);
canvas.c.acquisition_pct=9;canvas.c.acquisition_enabled=false;canvas.resetFee('acquisition');
assert.equal(canvas.c.acquisition_pct,2);assert.equal(canvas.c.acquisition_enabled,false);
canvas.c.returns_rub=50;canvas.resetFee('returns');assert.equal(canvas.c.returns_rub,15);
canvas.c.lastmile_rub=100;canvas.c.lastmile_enabled=false;canvas.resetFee('lastmile');
assert.equal(canvas.c.lastmile_rub,500);assert.equal(canvas.c.lastmile_enabled,false);
canvas.c.withdrawal_pct=9;canvas.resetFee('withdrawal');assert.equal(canvas.c.withdrawal_pct,2);
assert.equal((canvas.feeControls().match(/data-reset-fee=/g)||[]).length,4);
canvas.c.acquisition_enabled=true;canvas.c.returns_enabled=true;canvas.c.withdrawal_enabled=true;
costNode.fees={};
const checks=canvas.costCard(costNode,freight);
assert.match(checks,/② 退货费用换算/);
assert.ok(checks.indexOf('② 退货费用换算')<checks.indexOf('② 加上物流运费'));
assert.match(checks,/fc-step-check"><small>⑤ 收单费校验/);
assert.match(checks,/fc-step-check"><small>⑤ 提现费校验/);
assert.match(checks,/fc-step-profit"><small>⑥ 利润校验/);
console.log('PASS: caret restoration, four reset defaults preserving switches, reordered/colored verification steps');
const hoverDocument=global.document,hoverWindow=global.window;
try{
 const listeners={},shown=[];
 global.window={innerWidth:1000,innerHeight:900};
 global.document={body:{append(x){shown.push(x);}},createElement:()=>({style:{},offsetWidth:560,offsetHeight:560,children:[],append(x){this.children.push(x);},remove(){this.removed=true;}})};
 const hoverCanvas=Object.create(OzFreightCanvas.prototype);
 hoverCanvas.bindImageHover({addEventListener(k,fn){listeners[k]=fn;}},'img');
 const img={src:'/files/thumbnail.png',currentSrc:'/files/original.png',contains:()=>false,getBoundingClientRect:()=>({right:100,left:20,top:50})};
 listeners.mouseover({target:{closest:()=>img}});
 assert.equal(shown.length,1);assert.equal(shown[0].children[0].src,'/files/original.png');
 assert.equal(shown[0].style.left,'116px');assert.equal(shown[0].style.top,'50px');
 listeners.scroll();assert.equal(shown[0].removed,true);assert.equal(hoverCanvas.hoverImage,null);
 assert.match(canvas.costCard(costNode,freight),/fc-pricing-note/);
}finally{global.document=hoverDocument;global.window=hoverWindow;}
console.log('PASS: original image hover uses top-level preview, viewport positioning, scroll cleanup, expandable pricing notes');
const redCanvas=Object.create(OzFreightCanvas.prototype);redCanvas.c={margin_pct:35,acquisition_pct:2,withdrawal_pct:2,returns_rub:15,lastmile_rub:500,lastmile_enabled:false,advertising_cny:'',advertising_enabled:false};
const redNode={id:'red',fees:{margin_pct:28,acquisition_pct:2,returns_enabled:false}};
assert.equal(redCanvas.feeDiff(redNode,'margin'),true);
assert.equal(redCanvas.feeDiff(redNode,'acquisition'),false);
assert.equal(redCanvas.feeDiff(redNode,'returns'),true);
assert.equal((redCanvas.nodeFees(redNode).match(/class="fc-override-dot"/g)||[]).length,2);
redNode.fees.margin_pct='35.00';assert.equal(redCanvas.feeDiff(redNode,'margin'),false);
redNode.fees.returns_enabled=true;assert.equal(redCanvas.feeDot(redNode,'returns'),'');
redCanvas.c.margin_pct=40;assert.equal(redCanvas.feeDiff(redNode,'margin'),true);
assert.equal(redCanvas.feeDiff({id:'normal'},'margin'),false);
assert.equal(redCanvas.feeDiff({fees:{advertising_cny:0}},'advertising'),false);
console.log('PASS: override red dots compare shared values and switches, normalize numeric strings, disappear on equality');
const identifierNode={id:'ident',item:{weight:100},meta:{prices:[{store:'店铺A',ozon_sku_ids:['5486534298'],offer_id:'MANG-SHOVEL-T-HEAD'},{store:'店铺B',ozon_sku_ids:['123','456'],offer_id:'货号<&'}]}};
const identifierHTML=canvas.ozonIdentifiers(identifierNode);
assert.match(identifierHTML,/data-copy-item="5486534298"/);
assert.match(identifierHTML,/data-copy-item="MANG-SHOVEL-T-HEAD"/);
assert.match(identifierHTML,/货号&lt;&amp;/);
assert.match(identifierHTML,/店铺B/);
assert.equal((identifierHTML.match(/class="fc-copy-ozon"/g)||[]).length,5);
assert.equal(canvas.ozonIdentifiers({manual:true}),'');
assert.match(canvas.ozonIdentifiers({id:'old',meta:{prices:[{offer_id:'real-offer',sku:'not-real-sku'}]}}),/查询标识/);
assert.doesNotMatch(canvas.ozonIdentifiers({id:'old',meta:{prices:[{offer_id:'real-offer',sku:'not-real-sku'}]}}),/data-copy-item="not-real-sku"/);
console.log('PASS: separate Ozon SKU/offer copy targets, multiple stores and SKUs, safe escaping, missing identifier query');
