/* Run: node test_calculator.js */
const assert = require('node:assert/strict');
const {ozfcCalculate: calc, ozfcCost, OzFreightCanvas} = require('./ozon_freight_calcula.js');
const route={fixed:3.37,rate:39.3,min_weight:.001,max_weight:.5,min_value:1,max_value:1500,max_side:60,max_sum:90,divisor:0,step:0,battery:true,liquid:false};
const item={length:100,width:200,height:100,weight:100,value:1500};
assert.equal(calc(item,route).price,7.30);
assert.equal(calc(item,route).eligible,true);
assert.equal(calc({...item,weight:500},route).eligible,true);
assert.equal(calc({...item,weight:501},route).eligible,false);
assert.equal(calc({...item,value:1501},route).eligible,false);
assert.equal(calc({...item,length:610},route).eligible,false);
assert.equal(calc({...item,value:''},route).eligible,false);
assert.equal(calc({...item,weight:'abc'},route).eligible,false);
assert.equal(calc({...item,liquid:true},route).eligible,false);
assert.equal(calc({...item,battery:true},{...route,battery:false}).eligible,false);
const big={...route,fixed:40.44,rate:28.1,min_weight:2,min_exclusive:true,max_weight:30,min_value:1500,value_exclusive:true,max_value:7000,max_side:150,max_sum:310,divisor:12000,max_billable:31};
const box={...item,length:600,width:400,height:300,weight:3000,value:2000};
assert.equal(calc(box,big).bill,6);
assert.equal(calc(box,big).price,209.04);
assert.equal(calc({...box,weight:2000},big).eligible,false);
assert.equal(calc({...box,length:1500,width:1000,height:1000},big).eligible,false);
assert.equal(calc({...item,weight:101},{...route,step:.05}).bill.toFixed(2),'0.15');
assert.equal(calc({...box,length:1000,width:900,height:100},{...big,sorted_sides:[150,80,80]}).eligible,false);
assert.equal(calc(item,route).steps.length,5);
assert.equal(calc({...item,value_currency:'CNY',value:119.28},route,.07952).eligible,true);
assert.equal(calc({...item,value_currency:'CNY',value:120},route,.07952).eligible,false);
assert.equal(calc({...item,value_currency:'CNY'},route,0).eligible,false);
assert.equal(calc({...item,value_currency:'CNY',weight:.343,value:800},route,.07952).eligible,false);
const premium={...route,fixed:24.71,rate:28.1,max_weight:5,min_value:7000,value_exclusive:true,max_value:250000,max_side:150,max_sum:250};
const corrected=calc({...item,value_currency:'CNY',length:210,width:190,height:50,weight:343,value:800},premium,.07952);
assert.equal(corrected.eligible,true);
assert.equal(corrected.price,34.35);
const canvas=Object.create(OzFreightCanvas.prototype);
canvas.s={nodes:[],expanded:[],active:null,exclusive:true};
canvas.snap=()=>{};canvas.change=()=>{};canvas.paint=()=>{};
canvas.activate('a');canvas.activate('b');assert.deepEqual(canvas.expanded(),['b']);
canvas.s.exclusive=false;canvas.activate('a');assert.deepEqual(canvas.expanded(),['b','a']);
canvas.activate('b');assert.deepEqual(canvas.expanded(),['a']);
canvas.activate('a');assert.deepEqual(canvas.expanded(),[]);
canvas.bootData={exchange:{cny_per_rub:.07952,date:'2026-09-16'}};
const legacy={nodes:[{item:{value:1500}}],active:'a'},config={routes:[]};
assert.equal(canvas.prepare(legacy,config),true);
assert.equal(legacy.nodes[0].item.value_currency,'CNY');
assert.equal(legacy.nodes[0].item.value,'119.28');
const meta=canvas.metaHTML({id:'a',item:{weight:343},meta:{costs:[{amount:5.1,currency:'CNY',source:'库存成本'}],prices:[]}});
assert.match(meta,/5\.10/);assert.match(meta,/只读/);
console.log('PASS: calculator, CNY conversion, stock-weight regression, multi-card switch, old-canvas migration, read-only cost');
const example=ozfcCost(8.79,62.3,28,18);
assert.equal(example.total,71.09);
assert.equal(example.price,131.65);
assert.ok(example.actualMargin>=28);
assert.equal(ozfcCost(8.79,62.3,35,18).price,151.26);
assert.ok(ozfcCost(8.79,62.3,35,null).error);
assert.ok(ozfcCost(null,62.3,35,18).error);
assert.ok(ozfcCost(8.79,null,35,18).error);
assert.ok(ozfcCost(8.79,62.3,85,18).error);
assert.equal(ozfcCost(8.79,62.3,0,0).price,71.09);
canvas.c={margin_pct:35,cny_per_rub:.07952};canvas.s.nodes=[];
const costNode={id:'a',item:{},meta:{costs:[{amount:8.79,currency:'CNY'}],prices:[{store:'店铺',sku:'SKU',commissions:[{schema:'FBP',percent:11},{schema:'RFBS',percent:12}]}]},x:0,y:0};
const freight=[{eligible:true,r:{id:'route',provider:'CEL',name:'Economy',mode:'FBP'},price:62.3}];
assert.match(canvas.costCard(costNode,freight),/11%/);
assert.match(canvas.costCard(costNode,freight),/data-cost="1"/);
assert.match(canvas.costCard(costNode,freight),/⑥ 利润校验/);
costNode.commissionSchema='RFBS';assert.match(canvas.costCard(costNode,freight),/12%/);
canvas.c.routes=[{...route,id:'route',provider:'CEL',name:'Economy',mode:'FBP'}];canvas.c.cny_per_rub=.07952;
costNode.item={length:210,width:190,height:50,weight:343,value:78,value_currency:'CNY'};
Object.assign(costNode.meta.prices[0],{amount:78,cny:78,currency:'CNY'});
assert.match(canvas.quotes(costNode),/fc-cost-card/);
assert.match(canvas.quotes(costNode),/用此运费计算售价/);
canvas.s.nodes=[costNode];canvas.s.expanded=['a'];let connectors='';
canvas.root={querySelector:()=>({set innerHTML(s){connectors=s;}})};
canvas.drawLines();assert.equal((connectors.match(/<path /g)||[]).length,3);
console.log('PASS: margin pricing, null commission rejection, FBP/RFBS selection, step-by-step cost card');
const fees=ozfcCost(8.79,62.3,35,12,{acquisition:2,withdrawal:2,returns:15*.07952,lastmile:0});
assert.equal(fees.price,147.52);
assert.ok(fees.actualMargin>=35);
assert.ok(ozfcCost(1,1,95,2,{acquisition:2,withdrawal:2}).error);
assert.ok(ozfcCost(1,1,35,12,{returns:NaN}).error);
assert.deepEqual(canvas.feeParams(),{margin:35,acquisition:2,withdrawal:2,returns:15,lastmile:0,advertising:0});
assert.doesNotMatch(canvas.metaHTML(costNode),/Ozon 后台定价/);
assert.match(canvas.priceHTML(costNode),/Ozon 后台售价/);
console.log('PASS: fee switches defaults, RUB reserves, percentage fees, price placement');
assert.equal(canvas.shippingItem(costNode).value,78);
costNode.item.value=5.1;assert.equal(canvas.shippingItem(costNode).value,78);
assert.match(canvas.costCard(costNode,freight),/fc-sale-card/);
assert.match(canvas.costCard(costNode,freight),/退货费用换算/);
canvas.c.advertising_enabled=true;canvas.c.advertising_cny=10;
assert.equal(canvas.feeParams().advertising,10);
assert.equal(ozfcCost(10,10,0,0,{advertising:10}).price,30);
costNode.commissionOverride=19;
assert.match(canvas.costCard(costNode,freight),/19%（手动）/);
assert.match(canvas.costCard(costNode,freight),/恢复API原始佣金/);
assert.match(canvas.costCard(costNode,freight),/利润率35%/);
assert.doesNotThrow(()=>canvas.validateFees({advertising_cny:'',advertising_enabled:false}));
assert.throws(()=>canvas.validateFees({advertising_cny:-1}));
costNode.costEdited=true;costNode.item.value=800;
assert.match(canvas.costCard(costNode,freight),/¥800.00/);
const state={nodes:[costNode]};
canvas.prepare(state,canvas.c);assert.equal(costNode.item.value,800);
assert.equal(canvas.shippingItem(costNode).value,78);
canvas.c.lastmile_enabled=false;canvas.c.lastmile_rub=500;
canvas.c.advertising_enabled=false;canvas.c.advertising_cny=99;
let visible=canvas.costCard(costNode,freight);
assert.doesNotMatch(visible,/最后一公里换算|人民币固定费用|广告费 ¥/);
canvas.c.advertising_enabled=true;canvas.c.advertising_cny=0;
assert.doesNotMatch(canvas.costCard(costNode,freight),/人民币固定费用|广告费 ¥/);
canvas.c.returns_enabled=false;canvas.c.acquisition_enabled=false;canvas.c.withdrawal_pct=0;
visible=canvas.costCard(costNode,freight);
assert.doesNotMatch(visible,/退货费用换算|收单费校验|提现费校验/);
const oldRoot=canvas.root,oldLines=canvas.drawLines;
const moved={id:'move',x:40,y:50,quote:{x:500,y:100},cost:{x:1100,y:150},sale:{x:1600,y:200}};
const styles=[{},{},{},{}];
canvas.root={querySelectorAll:()=>[{}, {q:'1'},{cost:'1'},{sale:'1'}].map((dataset,i)=>({dataset,closest:()=>({style:styles[i]})}))};
canvas.drawLines=()=>{};
canvas.positionCards(moved);
assert.deepEqual(styles,[{left:'40px',top:'50px'},{left:'500px',top:'100px'},{left:'1100px',top:'150px'},{left:'1600px',top:'200px'}]);
canvas.root=oldRoot;canvas.drawLines=oldLines;
assert.match(canvas.dragZones(),/data-drag-zone="single"/);
assert.match(canvas.dragZones(),/data-drag-zone="group"/);
canvas.s.displayMode='table';assert.equal(canvas.isTable(),true);
canvas.s.displayMode='canvas';assert.equal(canvas.isTable(),false);
const listeners={},stageListeners={};
const dragCanvas=Object.create(OzFreightCanvas.prototype);
dragCanvas.s={nodes:[{id:'drag',x:10,y:20}],view:{x:0,y:0,z:2}};
dragCanvas.root={addEventListener:()=>{}};
dragCanvas.stage={addEventListener:(name,fn)=>stageListeners[name]=fn,classList:{add:()=>{},remove:()=>{}}};
dragCanvas.snap=()=>{};dragCanvas.positionCards=()=>{};dragCanvas.change=()=>{};
global.window={addEventListener:(name,fn)=>listeners[name]=fn,removeEventListener:()=>{},getSelection:()=>({removeAllRanges:()=>{}})};
dragCanvas.bind();
function drag(zoneType,kind){
 const header={dataset:{n:'drag',...(kind==='quote'?{q:'1'}:kind==='cost'?{cost:'1'}:kind==='sale'?{sale:'1'}:{})}};
 const card={querySelector:()=>header};
 stageListeners.pointerdown({button:0,clientX:0,clientY:0,target:{closest:selector=>selector==='[data-drag-zone]'?{dataset:{dragZone:zoneType}}:selector==='.fc-card'?card:null}});
 listeners.pointermove({clientX:20,clientY:40});listeners.pointerup();
}
drag('single','item');
assert.deepEqual({x:dragCanvas.s.nodes[0].x,y:dragCanvas.s.nodes[0].y},{x:20,y:40});
assert.deepEqual(dragCanvas.s.nodes[0].quote,{x:380,y:20});
const before=JSON.parse(JSON.stringify(dragCanvas.s.nodes[0]));
drag('group','sale');
assert.equal(dragCanvas.s.nodes[0].x,before.x+10);
for(const key of ['quote','cost','sale'])assert.deepEqual(dragCanvas.s.nodes[0][key],{x:before[key].x+10,y:before[key].y+20});
let briefHTML='';
global.frappe={ui:{Dialog:class{constructor(){this.$wrapper={addClass:()=>{}};this.fields_dict={brief:{$wrapper:[{set innerHTML(v){briefHTML=v;},addEventListener:()=>{}}]}};}show(){}}}};
canvas.brief();
assert.match(briefHTML,/物料/);assert.match(briefHTML,/建议售价/);assert.match(briefHTML,/data-copy-logistics/);
delete global.frappe;delete global.window;
console.log('PASS: single/group drag regions, table mode, four-column summary dialog');
const selectedCanvas=Object.create(OzFreightCanvas.prototype);
selectedCanvas.s={nodes:[],displayMode:'table'};
selectedCanvas.c={cny_per_rub:.07952,routes:[{...route,id:'cheap',provider:'LOW',name:'cheap',fixed:1},{...route,id:'selected',provider:'PICKED',name:'selected',fixed:20}]};
selectedCanvas.costCard=()=>'';selectedCanvas.logisticsQueries={};
const chosenNode={id:'chosen',x:0,y:0,item:{length:100,width:100,height:100,weight:100,value:5,value_currency:'CNY'},costRoute:'selected',meta:{prices:[{currency:'RUB',amount:100,cny:7.952}]}};
const html=selectedCanvas.quotes(chosenNode);
const listing=html.slice(html.indexOf('data-logistics-list'));
assert.ok(listing.indexOf('PICKED')<listing.indexOf('LOW'));
assert.equal((listing.match(/ open class=/g)||[]).length,2);
let first={scrollLeft:0},second={scrollLeft:0};
selectedCanvas.tableScroll=123;selectedCanvas.root={querySelectorAll:()=>[first,second]};
selectedCanvas.restoreTableScroll();assert.equal(first.scrollLeft,123);assert.equal(second.scrollLeft,123);
console.log('PASS: selected shipping pinned, full rules in table, synchronized scroll restoration');
